### ISSUE TITLE
[misc]: Easter egg or mishap on 404 page?

### ISSUE THREAD

**Issue by zanzlender** [pingdotgg/uploadthing#1003]
### I understand that this issue may be closed if it should be filed in another category

- [X] I understand

### My issue

Just noticed this.... Is this supposed to be an easter egg or did you accidentally left it in? Minor thing but wanted to let you know 😂

![image](https://github.com/user-attachments/assets/eaa86e6c-be9e-4724-bbb8-c64757cbd974)

![image](https://github.com/user-attachments/assets/8819f207-fd21-4b34-ba8f-a65d9207e16e)

**Comment by juliusmarminge** [comment]
ahha not sure why, i think it migth ahve been for stylistic chagnes lol :)
