### ISSUE TITLE
> What errors are you getting?

### ISSUE THREAD

**Issue by mihirDP** [pingdotgg/uploadthing#1004]
> What errors are you getting?

I know what project he was working and I am facing the same! There is no error at all main problem occurring here is that after user clicks the upload btn, selecting it , selects it and gets out of explorer window nothing happens! The file doesn't get uploaded. Even more it doesn't even get selected! and hence no upload happens! Here are step by step images what happens>>>
![image](https://github.com/user-attachments/assets/872deffe-3dbf-449c-ace6-bfe7d267d699)
![image](https://github.com/user-attachments/assets/34a2b600-91d9-431e-966e-601fc34d1774)
![image](https://github.com/user-attachments/assets/8add4178-96e7-408d-a47d-e40998f80a37)
And below are the ss of the Product Images Uploader section: 
![image](https://github.com/user-attachments/assets/93669e3d-af8a-4eda-bae2-956e79acf451)
![image](https://github.com/user-attachments/assets/d3038234-32ac-47cf-b7a9-63486b67794d)
![image](https://github.com/user-attachments/assets/aeafd051-c76e-468f-9c2a-dd23f3f2c07f)
![image](https://github.com/user-attachments/assets/faff1baf-5328-4b60-9921-f56ef77b4904)
Here the images are getting uploaded successfully

_Originally posted by @mihirDP in https://github.com/pingdotgg/uploadthing/issues/913#issuecomment-2400266161_

**Comment by juliusmarminge** [comment]
please follow issue template and submit a reproduction for your issue, thanks
