### ISSUE TITLE
[bug]: Nuxt: Invalid server configuration

### ISSUE THREAD

**Issue by ngajhede** [pingdotgg/uploadthing#1014]
### Provide environment information

```bash
System:
    OS: Linux 6.9 Pop!_OS 22.04 LTS
    CPU: (12) x64 Intel(R) Core(TM) i5-10500 CPU @ 3.10GHz
    Memory: 4.59 GB / 15.51 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 22.9.0 - ~/.nvm/versions/node/v22.9.0/bin/node
    npm: 10.8.3 - ~/.nvm/versions/node/v22.9.0/bin/npm
    pnpm: 9.11.0 - ~/.nvm/versions/node/v22.9.0/bin/pnpm
    bun: 1.1.29 - ~/.nvm/versions/node/v22.9.0/bin/bun
  Browsers:
    Chrome: 129.0.6668.100
  npmPackages:
    uploadthing: ^7.1.0 => 7.1.0
```

### Describe the bug

After implementing via your Nuxt guide, as well as the StackBlitz example, I am getting `Invalid server configuration`.

I looked again in your StackBlitz example, and it is getting the same error out of the box.

```json
{"url":"/api/uploadthing","statusCode":500,"statusMessage":"","message":"Invalid server configuration","stack":"<pre><span class=\"stack internal\">at ./node_modules/uploadthing/h3/index.js:177:287</span>\n<span class=\"stack internal\">at cause (./node_modules/effect/src/internal/core.ts:632:41)</span></pre>"}
```

### Link to reproduction

https://stackblitz.com/github/pingdotgg/uploadthing/tree/main/examples/minimal-nuxt?file=README.md

### To reproduce

Install the minimal Nuxt example. Doesn't work out of the box.

`"@uploadthing/nuxt": "^7.0.3"`
`"uploadthing": "^7.1.0"`

https://github.com/pingdotgg/uploadthing/tree/main/examples/minimal-nuxt

https://stackblitz.com/github/pingdotgg/uploadthing/tree/main/examples/minimal-nuxt?file=README.md

### Additional information

```
timestamp=2024-10-14T20:33:58.012Z level=ERROR fiber=#11 message="Invalid log level" error="{
  \"_op\": \"InvalidData\",
  \"path\": [
    \"logLevel\"
  ],
  \"message\": \"Expected a log level but received \"
}"


 ERROR  [nuxt] [request error] [unhandled] [500] Invalid server configuration
  at ./node_modules/uploadthing/h3/index.js:177:287  
  at cause (./node_modules/effect/src/internal/core.ts:632:41)

```

### 👨‍👧‍👦 Contributing

- [x] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ngajhede** [comment]
- I can give it a go at a PR, but this is my first introduction to uploadthing.

**Comment by ngajhede** [comment]
Found a solution: Manually add `logLevel` in `nuxt.config.ts`

```
export default defineNuxtConfig({
  uploadthing: {
    routerPath: '~/server/utils/uploadthing.ts',
    logLevel: 'All',
  },
 });
 ```
 
 Is a default not set, or is it expected to be set manually? If the latter, the type and docs should be updated.

**Comment by juliusmarminge** [comment]
default level might be missing 😬

you wanna file a PR adding a default of `Info`?

**Comment by ngajhede** [comment]
Hi @juliusmarminge 

Won't have time this week for a PR - feel free to do it. :smile_cat:
