### ISSUE TITLE
[bug]: Garbage broke my code

### ISSUE THREAD

**Issue by 0x1337z** [pingdotgg/uploadthing#1024]
### Provide environment information

```bash
garbage
```

### Describe the bug

cant upload anymore since the update

### Link to reproduction

notwork

### To reproduce

cant upload anymore since the update

### Additional information

wtf broke my code

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by juliusmarminge** [comment]
Not sure how you want us to help you when you don't provide any info.

Reopen and provide appropriate info
