### ISSUE TITLE
[Bug]: Can't create project free or paid

### ISSUE THREAD

**Issue by renatogalvones** [pingdotgg/uploadthing#1025]
### What happened?

Just created my account, went to Add new project and the dropdown of servers looks buggy as Portland appears duplicated.

![image](https://github.com/user-attachments/assets/e20e628c-e421-4fae-9bc3-1d10dff8b673)

### What did you expect to happen?

To create a new free project to try the tool.

### Version

MacOS with chrome 129. Nothing fancy.

### Reproduction Steps

Login > Add new project > Create App

### Relevant log output

```bash
No output at all. No triggers or requests are fired.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Gauthamyaramasa** [comment]
I thought it's only for me. On windows it's not working.

**Comment by Konanycode1** [comment]
I've just encountered this problem when creating an application
