### ISSUE TITLE
[Bug] [urgent] [important]: create app button is not working at all

### ISSUE THREAD

**Issue by Gauthamyaramasa** [pingdotgg/uploadthing#1026]
### What happened?

After signing up as a new user, redirected to the dashboard. When I try to create a new app after filling the details, the create app button is completely not working at all...

### What did you expect to happen?

Clicking on create app button should create new app and the user can move further. If it's not working then there is no point of using this at all??

### Version

Windows 11

### Reproduction Steps

Sign Up > Create new app > create app

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Konanycode1** [comment]
I've just encountered this problem when creating an application

**Comment by renatogalvones** [comment]
Repeated. Already opened here: https://github.com/pingdotgg/uploadthing/issues/1025

**Comment by juliusmarminge** [comment]
Fixed. Sorry
