### ISSUE TITLE
[misc]: Commas in file name break the original file name upon download (and loss of file extension).

### ISSUE THREAD

**Issue by MGSimard** [pingdotgg/uploadthing#1052]
### I understand that this issue may be closed if it should be filed in another category

- [X] I understand

### My issue

For instance, I have this zip file: 
`Map049 - Skill Center (Blython, MW1).rar`

The full file name appears in dashboard, however when I go ahead and download it (click or link access), the downloaded file name cuts off as:
`Map049 - Skill Center (Blython`

The file itself remains intact and can be "recovered" putting the file extension back in - however it's still problematic for the end user, namely loss of context in both file name and file type.

**Edit: File name comes out fine if downloaded through Firefox, so perhaps a Chrome issue and potentially other browsers too? A bit of research leads me to believe this could be a content disposition formatting issue in the HTTP response headers.** _Seeing examples of this here: https://github.com/ohmage/server/pull/900/files_

**Comment by markflorkowski** [comment]
> A bit of research leads me to believe this could be a content disposition formatting issue in the HTTP response headers.

Almost certainly this. Will take a look into this later today, should be a pretty simple fix if that is the case I think.
