### ISSUE TITLE
[misc]: nextjs 15 metadata opengraph card image returns invalid content type

### ISSUE THREAD

**Issue by MajidNjozi** [pingdotgg/uploadthing#1054]
### I understand that this issue may be closed if it should be filed in another category

- [X] I understand

### My issue

working on a dynamic web app using nextjs 15, in it i have decided to use the metadata function by nextjs to bump up the seo and in it opengraph and twitter card images. here is the sample code:

` openGraph: {
    type: 'xxx',
    url: 'xxx',
    title: 'xxx',
    description:
      'xxx',
    images: [
      {
        url: 'https://utfs.io/f/NQ1UkAeyXUbIyGzw9wCFCp1Fm627bgXMD4x3c8K9zjZqvLrl',
        width: 1200,
        height: 630,
      },
      {
        url: 'https://utfs.io/f/NQ1UkAeyXUbIaxO68p167jviNgO80Zen4UQR2Yytc5Fw1fdl',
        width: 600,
        height: 315,
      },
    ],
  },
  twitter: {
    card: 'xxx',
    creator: 'xxx',
    title: 'xxx',
    description:
      'xxx',
    images: [
      'https://utfs.io/f/NQ1UkAeyXUbIyGzw9wCFCp1Fm627bgXMD4x3c8K9zjZqvLrl',
      'https://utfs.io/f/NQ1UkAeyXUbIaxO68p167jviNgO80Zen4UQR2Yytc5Fw1fdl',
    ],
  },`

unfortunately, all the metadata is visible on both twitter and sites that use opengraph except fro the images.
on using [Facebook Debugger ](https://developers.facebook.com/tools/debug/) i am told that

![SmartSelect_20241118_144958_Samsung Internet](https://github.com/user-attachments/assets/dc6e97c1-dba3-4302-9cff-62217a77b74a)

it used to work up until recently around 12th November 2024 when uploadthing.com kinda went down for a few hours and when it got back, this stopped working.

Please help.

**Comment by juliusmarminge** [comment]
content type seems fine on that url? 
![CleanShot 2024-11-18 at 13 34 51@2x](https://github.com/user-attachments/assets/6107bcc8-64bd-42ec-99e5-8bd3cef8b2ce)

> uploadthing.com kinda went down for a few hours and when it got back, this stopped working.

I am not aware of any such outage, what makes you say this?

**Comment by juliusmarminge** [comment]
This file: https://utfs.io/f/NQ1UkAeyXUbNjlp9UeyXUb7StWz0vPDscg1LOToVwhxaQY - is not in our DB which means either it never existed or it was deleted more than a week ago

That's why it cannot be used as OG cause the URL returns a 404 not found page:

![CleanShot 2024-11-18 at 13 37 04@2x](https://github.com/user-attachments/assets/e81bd705-316c-4251-a655-ed9fad8685a0)

**Comment by juliusmarminge** [comment]
Closing as I don't see the issue here from our end, existing files are properly displayed as opengrah, and non-existing ones correctly 404s. If you believe otherwise feel free to open a new issue with more details
