### ISSUE TITLE
bug: type error in route config when using input

### ISSUE THREAD

**Issue by mmmoli** [pingdotgg/uploadthing#1071]
### Describe the feature you'd like to request

Loving this lib!

Question: why does this work ✅:

```
export const ourFileRouter = {
  fileUploader: f({
    "model/gltf-binary": { maxFileSize: "256MB", maxFileCount: 4 },
  })
  …
```
and this ✅:

```
export const ourFileRouter = {
  fileUploader: f({
     image: { maxFileSize: "2MB", maxFileCount: 4 }
  })
  …
  ```

and event this ✅:

```
export const ourFileRouter = {
  // Define as many FileRoutes as you like, each with a unique routeSlug
  fileUploader: f(["image", "video"])
    .input(FileUploaderInputSchema)
 …
  ```
  
But not this ❌:
  
```
fileUploader: f({
    "model/gltf-binary": { maxFileSize: "256MB", maxFileCount: 4 },
    image: { maxFileSize: "2MB", maxFileCount: 4 },
  })
    .input(FileUploaderInputSchema)
  …
  ```

### Describe the solution you'd like to see

A sentence in the docs explaining why this doesn't work or a bug fixed if it's supposed to work as I think.

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

**Comment by juliusmarminge** [comment]
can you provide a reproduction where this is failing? All of these cases seems to work here: https://stackblitz.com/edit/vitejs-vite-68o5w7?file=ut.ts

**Comment by mmmoli** [comment]
Thanks for coming back so soon.

Regarding the `accepted` file types:

![Screenshot 2024-11-27 at 21 46 36](https://github.com/user-attachments/assets/fdc18fe0-1e88-4d90-b784-95c0435be170)

As soon as both `model/gltf-binary` and `images` are included, only image files can be picked in the picker.

To be fair, this might be an HTML thing.

**Comment by juliusmarminge** [comment]
if you inspect the html input tag, what's the value on the `accept`?
