### ISSUE TITLE
[Bug]: Clicking the profile button from the dashboard goes to 404

### ISSUE THREAD

**Issue by BrunoAseff** [pingdotgg/uploadthing#1076]
### What happened?

When logged into the UploadThing website and on the landing page, clicking on your profile picture and then selecting the profile button leads to a 404 error page. The URL generated is incorrect, showing "https://uploadthing.com/dashboard/undefined/profile".

### What did you expect to happen?

Upon clicking your profile picture and selecting the profile button, you expected to be redirected to your personal profile page where you can view and edit your account information.

### Version

7.3.0

### Reproduction Steps

Steps to reproduce:

1. Log in to the UploadThing website
2. Navigate to the landing page
3. Click on your profile picture
4. Select the "Profile" button
5. Observe that you are redirected to a 404 error page with the URL "https://uploadthing.com/dashboard/undefined/profile"

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by markflorkowski** [comment]
Good catch, looking into this now

**Comment by markflorkowski** [comment]
Should be fixed now.
