### ISSUE TITLE
[bug]: failure to upload image in upload thing

### ISSUE THREAD

**Issue by joywin2003** [pingdotgg/uploadthing#1079]
### Provide environment information

```bash
System:
    OS: macOS 15.0
    CPU: (8) arm64 Apple M1
    Memory: 53.02 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.17.0 - ~/.nvm/versions/node/v20.17.0/bin/node
    Yarn: 4.0.2 - ~/.volta/bin/yarn
    npm: 10.8.2 - ~/.nvm/versions/node/v20.17.0/bin/npm
  Browsers:
    Safari: 18.0
  npmPackages:
    @uploadthing/react: ^7.0.2 => 7.0.2 
    typescript: ^5 => 5.6.2 
    uploadthing: ^7.0.2 => 7.0.2
```

## Issue Description

The upload process intermittently fails, primarily on **mobile devices** and occasionally on **laptops**. This issue occurs during the **TEDx registration process**, where users enter details and upload images (ID card and photo).

Most of the time, the uploads work perfectly fine. However, in some instances, the uploads fail, and the renamed files (e.g., `102110191.jpg`) are not stored, indicating a failed upload.

---

### Error Message  

Below is the captured error message from the issue:  

![WhatsApp Image Dec 2 2024](https://github.com/user-attachments/assets/ac9a5490-0958-4230-9e91-8e56a78868ce)

```plaintext
Something went wrong. Please contact UploadThing and provide the following cause: FetchError  
7023-4bcb26c8ca04fb56.js:1:4007  
Upload error: UploadThingError: Something went wrong. Please report this to UploadThing.  

    NextJS 7  
    oncomplete https://checkout.razorpay.com/v1/checkout.js:1  
    setTimeout handler*oncomplete https://checkout.razorpay.com/v1/checkout.js:1  
    onmessage https://checkout.razorpay.com/v1/checkout.js:1  
    A https://checkout.razorpay.com/v1/checkout.js:1  
    Sn https://checkout.razorpay.com/v1/checkout.js:1  
    Rn https://checkout.razorpay.com/v1/checkout.js:1  
    n https://checkout.razorpay.com/v1/checkout.js:1  
    <anonymous> https://checkout.razorpay.com/v1/checkout.js:1  
    <anonymous> https://checkout.razorpay.com/v1/checkout.js:1  
    <anonymous> https://checkout.razorpay.com/v1/checkout.js:1  

Caused by: FetchError:  
    NextJS 7  
7023-4bcb26c8ca04fb56.js:1:4007  
    NextJS 2  
    overrideMethod https://website-o6pc.vercel.app/auth/signin?callbackUrl=https://website-o6pc.vercel.app/register:13851  
    NextJS 4  
    oncomplete https://checkout.razorpay.com/v1/checkout.js:1  
    (Async: setTimeout handler)  
    oncomplete https://checkout.razorpay.com/v1/checkout.js:1  
    onmessage https://checkout.razorpay.com/v1/checkout.js:1  
    (Async: EventListener.handleEvent)  
    A https://checkout.razorpay.com/v1/checkout.js:1  
    Sn https://checkout.razorpay.com/v1/checkout.js:1  
    Rn https://checkout.razorpay.com/v1/checkout.js:1  
    n https://checkout.razorpay.com/v1/checkout.js:1  
    <anonymous> https://checkout.razorpay.com/v1/checkout.js:1  
    <anonymous> https://checkout.razorpay.com/v1/checkout.js:1  
    <anonymous> https://checkout.razorpay.com/v1/checkout.js:1  
```
---

## Object Format

The following is the object format returned during the upload process:
```
{
  url: "https://seal.ingest.uploadthing.com/efK2khiKaMBXJ7nkAJsArfVN_761616f4ebb73d9fa2cdb7bb2f6aba222f3910eaa04693a90b7d8e62558",
  method: "HEAD",
  body: undefined,
  headers: {}
}

```

the code for implementation of upload thing is [here](https://github.com/TEDx-SJEC/website/blob/55cf72fff21139885ba50dc6a1d9e57bfb806447/src/components/common/registration-form.tsx#L97-L133)

### Link to reproduction

https://github.com/TEDx-SJEC/website

### Description
The issue occurs sporadically, primarily on **mobile devices**, and occasionally on **laptops**. Below are the steps to reproduce the problem. Note that the occurrence is intermittent and requires multiple attempts.

---

### Reproduction Steps:
1. Navigate to the **TEDx registration page** where user details, including **images (ID card and photo)**, are entered and uploaded using **UploadThing**.
2. Attempt to complete and submit registrations multiple times, paying attention to the upload process.
3. Observe the following pattern for the issue:
   - **On Mobile Devices**: The error typically occurs **1 in every 10 registrations**.
   - **On Laptops**: The error is less frequent, occurring approximately **1 in every 50 registrations**.
4. The upload occasionally fails, displaying an error message (refer to the [error message section](#error-message)).

---

### Note for Reproduction:
- Since the issue is intermittent, consistent reproduction may not be possible without **deployed access** to the registration system.
- A **deployment link** would need to be shared for debugging and testing purposes to observe the error in a real-world scenario. 

Let us have a furture communicate to take this forward

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by markflorkowski** [comment]
Investigating this now, however without a consistent repro, it is very difficult for us to narrow down the cause. Are you able to provide a HAR file of a session where the error occurs, or at least screenshots from the network tab of the console for the failing requests

**Comment by gdsc-sjec-github** [comment]
At the moment, we have shifted from UT to EdgeStore as the issue is urgent. We plan to conduct additional testing later.

You can reproduce the bug on the hosted site [here](https://website-o6pc-piwrd72eq-joywin-bennis-s-projects.vercel.app/). Please test it on a phone, as the error is more likely to occur there. On a laptop, the chances of encountering the issue are rare. However, since most of our users access the site via phones, the likelihood of the issue is significantly higher.

For your information, the website is currently live in production.

**Comment by markflorkowski** [comment]
When I attempted to do that yesterday, I was unable to complete the payment step with a test card. What test card should I use for it to work?
