### ISSUE TITLE
[Bug]: Profile image change failure

### ISSUE THREAD

**Issue by nmktad** [pingdotgg/uploadthing#1082]
### What happened?

I tried to change the profile image for my team but it's failing. it's an internal server error from the API endpoint. 

endpoint `/api/uploadthing?actionType=upload&slug=teamImage`
response `Missing token. Please set the UPLOADTHING_TOKEN environment variable or provide a token manually through config.'

![Screenshot 2024-12-03 143440](https://github.com/user-attachments/assets/c4744eb5-fd54-43ea-84c1-fff03e668538)

### What did you expect to happen?

To change the profile image for the team. 

### Version

Dashboard

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by juliusmarminge** [comment]
That's... embarrasing. Fixed now
