### ISSUE TITLE
docs: adding openAPI spec json/yaml to the docs

### ISSUE THREAD

**Issue by aymaneallaoui** [pingdotgg/uploadthing#1084]
### Area of Improvement

i would like to be able to download the opneapi spec so i could generate clients, using some codegen

### Link to related docs

https://docs.uploadthing.com/api-reference/openapi-spec

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR implementing the suggested changes!

**Comment by juliusmarminge** [comment]
https://api.uploadthing.com/openapi-spec.json
