### ISSUE TITLE
Feat: Add onUploadBegin prop to UploadButton

### ISSUE THREAD

**Issue by thebishalniroula** [pingdotgg/uploadthing#109]
It would be better if we could add a new prop to UpoadButton that takes a function which runs when uploadthing begins the uploading in the background.

Use case of this feature would be when I want to show some visual feedback when the upload begins.

**Comment by irtaza9** [comment]
The better should be to have all the features like onuploadprogress and onuploadbegins, etc. I think axios is offering onuploadprogress callback.

**Comment by markflorkowski** [comment]
We definitely want to add an `onUploadProgress()` callback. I'll have to think a bit more about `onUploadBegin()`, but I think it makes sense as well.

**Comment by irtaza9** [comment]
Cool, let me know if you guys need any help. I'll be happy to add my part.

**Comment by markflorkowski** [comment]
Feel free to open a PR if you have ideas on this and want to contribute! Otherwise, i have put this in our backlog to be addressed *soon*(tm)

**Comment by irtaza9** [comment]
I was thinking about it but It's tough 
![image](https://github.com/pingdotgg/uploadthing/assets/98938307/2c6ea0e6-9dab-4d30-8cb0-9b2294ab2f69)

**Comment by markflorkowski** [comment]
I am thinking if we use XHR instead of fetch, it has onprogress built in, which could work. Alternatively we could do uploads as multipart, and use the completion of each part to update the progress.

**Comment by irtaza9** [comment]
And that is what I want to suggest but I thought all the package is build around fetch may be you people don't go for XHR. btw what about axios? 

### XHR:

```javascript
   const xhr = new XMLHttpRequest();
   xhr.addEventListener("loadstart", handleEvent);
   xhr.addEventListener("load", handleEvent);
   xhr.addEventListener("loadend", handleEvent);
   xhr.addEventListener("progress", handleEvent);
   xhr.addEventListener("error", handleEvent);
   xhr.addEventListener("abort", handleEvent);
``` 

### helper-fun

```javascript
   function handleEvent(e) {
      console.log(e.loaded)
   }
``` 

I got this resource over [mdn](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/progress_event)

**Comment by Mr0Bread** [comment]
@markflorkowski onUploadBegin prop had been released. I guess this issue can be closed now

**Comment by markflorkowski** [comment]
onUploadBegin has been added as of  v5.4.0 🙌

**Comment by ryanpratama14** [comment]
onUploadBegin is not working somehow...

 "uploadthing": "^6.0.3",
"@uploadthing/react": "^6.0.2",

**Comment by Shijel** [comment]
@ryanpratama14  Same here 

"uploadthing": "^6.0.4"
"@uploadthing/react": "^6.0.2",

**Comment by markflorkowski** [comment]
Yeah looks like we broke it when we introduced multipart uploads. Will be fixed in the next release.
