### ISSUE TITLE
CORS Error

### ISSUE THREAD

**Issue by irtaza9** [pingdotgg/uploadthing#112]
### What happened?

I was checking the network requests and found that one of endpoint is throwing cross origin error when you are not logged in.

### normal usage:
![image](https://github.com/pingdotgg/uploadthing/assets/98938307/6573166c-d111-4ab5-8c53-9109dd593e29)

### using CORS EXT:
![image](https://github.com/pingdotgg/uploadthing/assets/98938307/64aa0720-95c5-413f-9cfa-92ab79518150)

### What did you expect to happen?

As earlier, I reported one issue and now that one fixed so hoping to fix it with same energy.

### Version

BETA

### Reproduction Steps

 We'll check the root cause and the expected solution and add that in the project. I thing we have to the check headers and the allowed origin at server. 

### Reproduction Repository

right now, No!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by markflorkowski** [comment]
Hmm thats an odd one, I'm able to repro, will look into this.

**Comment by t3dotgg** [comment]
Fix'd ty!

**Comment by chrhi** [comment]
![this is error](https://github.com/pingdotgg/uploadthing/assets/116351398/9dea7ef5-fe1b-46de-858c-63fa16038a6e)
why ??

**Comment by markflorkowski** [comment]
@chrhi without a repro or access to your code, i have no way to investigate this. Also, please open a new issue rather than posting on this old, unrelated one.
