### ISSUE TITLE
[Bug]: ambigious indirect export error when importing @uploadthing/solid

### ISSUE THREAD

**Issue by cs-clarence** [pingdotgg/uploadthing#113]
### What happened?

I'm getting an error when importing `@uploadthing/solid`.

```
Uncaught (in promise) SyntaxError: ambiguous indirect export: default 2 [dev.jsx:5:7](http://127.0.0.1:3000/@fs/home/rencedm112/Repositories/Mono/@taskgrove/node_modules/.pnpm/solidjs-dropzone@1.0.0_solid-js@1.7.5/node_modules/solidjs-dropzone/dist/dev.jsx?v=745a3ea6)
```

Here's the code
```tsx
import { center } from "./styles.css";
import "@uploadthing/solid/styles.css";
import { useUploadThing } from "@uploadthing/solid";

export default function FilesPage() {
  const uploadthing = useUploadThing({
    url: "http://localhost:3000",
    endpoint: "imageUploader",
  });
  return (
    <div class={center}>
      <label>
        Upload file
        <input
          type="file"
          name="uploadedFile"
          onChange={async (e) => {
            console.log("Upload");
            if (!e.currentTarget.files) return;
            uploadthing.startUpload(e.currentTarget.files);
          }}
        />
      </label>
    </div>
  );
}
```

### What did you expect to happen?

Importing the package should not produce an error

### Version

Node v20.2.0
Pnpm v8.6.0
@uploadthing/solid 3.0.5
uploadthing 4.0.0:

### Reproduction Steps

Import @uploadthing/solid into a page route
Use any import in it in the code
Navigate to that page

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by markflorkowski** [comment]
Does it make any difference if you import matching versions of `@uploadhting/solid` and `uploadthing`? 

I noticed you reported using `@uploadthing/solid: 3.0.5` and `uploadthing: 4.0.0` which may be incompatible.

**Comment by cs-clarence** [comment]
> Does it make any difference if you import matching versions of `@uploadhting/solid` and `uploadthing`?
> 
> I noticed you reported using `@uploadthing/solid: 3.0.5` and `uploadthing: 4.0.0` which may be incompatible.

I just tried it to use the same version now, same error.

**Comment by markflorkowski** [comment]
cc @OrJDev
