### ISSUE TITLE
[Bug]: Module '"@uploadthing/react"' has no exported member 'generateReactHelpers'.

### ISSUE THREAD

**Issue by junhuang-ho** [pingdotgg/uploadthing#114]
### What happened?

This

```
import { generateReactHelpers } from "@uploadthing/react";
```
fails with 

> Module '"@uploadthing/react"' has no exported member 'generateReactHelpers'.

even after restarting typescript.

### What did you expect to happen?

import success

### Version

"uploadthing": "^4.0.0",
"@uploadthing/react": "^4.0.0",

### Reproduction Steps

`import { generateReactHelpers } from "@uploadthing/react";` on 4.0.0 versions of uploadthing

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by junhuang-ho** [comment]
https://github.com/junhuang-ho/test-uploadthing

Hi @markflorkowski , here it is. Just a simple t3 app with `generateReactHelpers` imported in index.

**Comment by markflorkowski** [comment]
Interesting, it seems when you install using Yarn (and possibly npm) this happens. Using `pnpm install` did not have this issue for me when I tested in your repo. 

We'll look into this

**Comment by Lukem121** [comment]
Appending "hooks" onto the end of the generateReactHelpers import fixes this issue.

```
import { generateReactHelpers } from "@uploadthing/react/**hooks**";
import { type OurFileRouter } from "~/server/uploadthing";

export const { useUploadThing, uploadFiles } =
  generateReactHelpers<OurFileRouter>();

```

**Comment by Tagvi** [comment]
Same issue but on PNPM.
@uploadthing/react: 4.1.0
PNPM: 8.3.1
Appending /hooks also solved it for me

**Comment by juliusmarminge** [comment]
/hooks is the correct entrypoint. updating docs!
