### ISSUE TITLE
[chore] Update `@uploadthing/solid` to 4.0.0

### ISSUE THREAD

**Issue by t3dotgg** [pingdotgg/uploadthing#116]
Was not able to get this in before the 4.0.0 release. cc @OrJDev

**Comment by OrJDev** [comment]
Sure will take a look at this asap, but when implementing new features it might be worth it to dm on discord so we can get everything up to date on the same day

**Comment by OrJDev** [comment]
got everything up to date in https://github.com/pingdotgg/uploadthing/pull/125
