### ISSUE TITLE
Uploading files in to folders

### ISSUE THREAD

**Issue by duvior** [pingdotgg/uploadthing#128]
Is it possible to upload files in to folders/directories?

image route to /img
video router to /videos

**Comment by markflorkowski** [comment]
Uploadthing does not have any concept of folders at this time. We are considering adding this in the future though.

**Comment by Hacksore** [comment]
@markflorkowski understood it's not implemented yet and it's probably a butt load of work but just throwing in my two cents.

Would be really helpful to group related items like these feature release videos 🤣. It would allow us to have something like `features-announcements/<date>/<name>.mp4`.

![image](https://github.com/user-attachments/assets/9922f037-dc69-40d0-b96b-5e189463c06b)
