### ISSUE TITLE
[Bug]: Can't cancel file deletion when using uploadthing.com dashboard

### ISSUE THREAD

**Issue by Tagvi** [pingdotgg/uploadthing#132]
### What happened?

I click delete and cancel but it still deletes the files.

https://github.com/pingdotgg/uploadthing/assets/71146188/70e4e80a-7b9f-40eb-8b84-1cbd0c48550e

### What did you expect to happen?

I expect file deletion to be cancelled.

### Version

Web UI? idk
Local uploadthing 4.1.0 (Doesn't matter tho)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by markflorkowski** [comment]
Oh no 😬 I just repro'd this, will get a fix out today 👍

**Comment by markflorkowski** [comment]
Should be resolved now!
