### ISSUE TITLE
[Bug]: "dev server is now running" message in production?

### ISSUE THREAD

**Issue by dave-irvine** [pingdotgg/uploadthing#144]
### What happened?

When deployed to production, the log message:

> [UT] UploadThing dev server is now running!

appears. This message does not appear in the dev environment.

### What did you expect to happen?

The inverse of what happened.

### Version

4.1.1

### Relevant log output

```bash
[UT] UploadThing dev server is now running!
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dave-irvine** [comment]
Is the logic here just inverted?

https://github.com/pingdotgg/uploadthing/blob/main/packages/uploadthing/src/internal/handler.ts#L74-L76

**Comment by markflorkowski** [comment]
Indeed it is 😅
