### ISSUE TITLE
[Bug]: "No file found for presigned URL" error when filename contains letter «й» 

### ISSUE THREAD

**Issue by sincerely-manny** [pingdotgg/uploadthing#153]
### What happened?

UT returns error "No file found for presigned URL" when trying to upload file that contains cyrillic letter й in it’s filename. No problems with other cyrillic characters (as far as I know). In UT dashboard file appears as «Uploading» 

### What did you expect to happen?

File should be uploaded as all other files do

### Version

UT, UT/react 4.1.1
Next.js 13.4.3
React 18.2.0

### Relevant log output

```bash
Console log:

[UT] Call unsuccessful after 4 tries. Retrying in 8 seconds...
[UT] Call unsuccessful after 5 tries. Retrying in 16 seconds...
[UT] Call unsuccessful after 6 tries. Retrying in 32 seconds...
[UT] Call unsuccessful after 8 tries. Retrying in 64 seconds...
[UT] Call unsuccessful after 7 tries. Retrying in 64 seconds...
[UT] Call unsuccessful after 9 tries. Retrying in 64 seconds...
[UT] Call unsuccessful after 8 tries. Retrying in 64 seconds...
[UT] Call unsuccessful after 10 tries. Retrying in 64 seconds…


UT endpoint reply:

[{
    "presignedUrl": {
        "url": "https://uploadthing-prod.s3.us-west-2.amazonaws.com/",
        "fields": {
            "bucket": "uploadthing-prod",
            "X-Amz-Algorithm": "AWS4-HMAC-SHA256",
            "X-Amz-Credential": "XXX",
            "X-Amz-Date": "20230610T213624Z",
            "key": "c1c22697-d081-4756-a55b-8c723cc40571_Информационное_письмо_–_Май_2022.pdf",
            "Policy": "XXX",
            "X-Amz-Signature": "XXX"
        }
    },
    "name": "Информационное_письмо_–_Май_2022.pdf",
    "key": "c1c22697-d081-4756-a55b-8c723cc40571_Информационное_письмо_–_Май_2022.pdf",
    "fileType": "blob"
}]
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ig4e** [comment]
This rarely happens to me I don't really know why most of the time it works but sometimes it simply doesn't without any changes to the code. I didn't test it on production until now but I hope this error goes away on production

**Comment by markflorkowski** [comment]
This should be resolved now, as filenames are now hashed. Please re-open if you are still encountering this bug.

**Comment by EmmanuelKeifala** [comment]
i am still encountering this bug.

**Comment by markflorkowski** [comment]
> i am still encountering this bug.

@EmmanuelKeifala What version of uploadthing are you using?

**Comment by EmmanuelKeifala** [comment]
I am using "uploadthing": "^6.0.4"

**Comment by markflorkowski** [comment]
And what is the file name you are experienceing this issue with?

**Comment by EmmanuelKeifala** [comment]
> And what is the file name you are experienceing this issue with?

Filename: Physics-Book.pdf

**Comment by markflorkowski** [comment]
I am not able to reproduce that behavior on my end locally, in prod, or with an upload on the uploadthing dashboard.

Are you able to provide a minimal example reproduction repo for this?
