### ISSUE TITLE
Ability to choose s3 region for the application 

### ISSUE THREAD

**Issue by TriDvaRas** [pingdotgg/uploadthing#159]
Hi, are there any plans about adding different storage region support? Saw #28 with similar request and i understand that this is not what you are aiming your service to be, but i think having ability to choose region where your files are stored our of predefined buckets (at least US/Europe/Asia) would be nice.

**Comment by markflorkowski** [comment]
This is definitely something that we are thinking about, just have not figured out yet exactly how we would want to implement it. Also judging priority based on the number of asks 👍

**Comment by amirfakhrullah** [comment]
Any update on this? :(

**Comment by markflorkowski** [comment]
We're working on it, the infrastructure requirements were a bit more complex than we initially thought, so it is taking longer than expected. We are still working on it though!
