### ISSUE TITLE
Question: How can I retrieve uploaded files with its info

### ISSUE THREAD

**Issue by ig4e** [pingdotgg/uploadthing#169]
How can I retrieve uploaded files with their info with information just like the uploadthing dashboard?
I want to make a page where the admin manages the uploaded content and can see its size, upload date, key, URL, filename, callBackSlug (upload slug), metadata, and type but as far as I'm aware there's currently no way of achieving this so far by looking at the  [utapi docs](https://docs.uploadthing.com/api-reference/server#utapi)

**Comment by markflorkowski** [comment]
Correct, at this time there is only a method to retrieve the file url using the file key. 

We currently don't have any plans to expose additional information via the utapi functions, so you would need to store this information in your own DB
