### ISSUE TITLE
Feature Request: Enhanced Privacy Mode

### ISSUE THREAD

**Issue by JordanStuckings** [pingdotgg/uploadthing#173]
Upload Thing has proved to be an efficient and effective solution for setting up file uploads in my project. However, I am currently facing a challenge with user privacy. The application I am developing requires users to upload files that are intended to be private. As it stands, these files are openly accessible on S3, which does not suit my needs.

I propose the implementation of an **Enhanced Privacy Mode** for file uploads. This could be achieved by adding a **`private: true`** flag to uploads, which would restrict file access only to authenticated download requests. The access to these files should be limited to the server that contains the **`UPLOADTHING_SECRET`**.

**Comment by markflorkowski** [comment]
Yup. this is on our [roadmap](https://t3-tools.notion.site/776334c06d814dd08d450975bb983085?v=a04ee69d18a047859717b279df504a6b)!

**Comment by p6l-richard** [comment]
Would this mean that if we pass along an `{ access: "private" }` option, the files uploaded to S3 would be accessible only from the nextjs server that uploaded the files?
I guess if the user is the owner of the file can still be handled in a middleware, but would be nice to have the files be protected on S3's side.

**Comment by markflorkowski** [comment]
This would require having the files be protected on S3 (or whichever backing provider) otherwise requesting the files from s3 (or other provider) would bypass the "security".

We do have plans on how we are going to support this, it has just been a bit more work than initially anticipated 😅

**Comment by markflorkowski** [comment]
Unfortunately not, it is purely an infrastructural thing. We are working on it though, hoping to have something out for end of year

**Comment by AndyClausen** [comment]
This seems to have been implemented now?

**Comment by markflorkowski** [comment]
Yup! Sorry I forgot to circle back here!
