### ISSUE TITLE
[Bug]: "@uploadthing/react" has no exported member 'generateComponents' .

### ISSUE THREAD

**Issue by alifares10** [pingdotgg/uploadthing#174]
### What happened?

This

`import { generateComponents } from "@uploadthing/react";`

fails with

> Module '"@uploadthing/react"' has no exported member 'generateComponents'.

i restarted the IED and reinstalled uploadnothing but still get this error 

### What did you expect to happen?

import success

### Version

4.1.3

### Reproduction Steps

import { generateReactHelpers } from "@uploadthing/react";

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by shaunkickbusch** [comment]
Getting this as well. Pretty major issue.

**Comment by markflorkowski** [comment]
Import path in the docs is incorrect. Import from `@uploadthing/react/hooks`. I'll update the docs now.

**Comment by markflorkowski** [comment]
We forgot to cut a release 🤦 v5.0.0 should have the correct export. Sorry for the confusion.
