### ISSUE TITLE
[Request]: Allow deletion of account via Clerk

### ISSUE THREAD

**Issue by boringContributor** [pingdotgg/uploadthing#208]
### What happened?

You use Clerk for auth which I appreciate, however, you disabled the option to allow your account deletion through the <UserButton /> component. 

At least in EU this is not legal sadly so I'd appreciate if you'd add that option :)

thanks!!

### What did you expect to happen?

Allow account deletion through clerk user account.

### Version

latest

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by markflorkowski** [comment]
Not sure how we missed that one 😅 I'm on it!

**Comment by markflorkowski** [comment]
Account deletion should now be enabled 👍
