### ISSUE TITLE
[Bug]: MIME Type Error on File Extensions

### ISSUE THREAD

**Issue by btahir** [pingdotgg/uploadthing#212]
### What happened?

Trying to restrict files based on extension. I tried

```
'audio/mpeg': { maxFileSize: '16MB', maxFileCount: 1 },
```

but it gave me the following error

<img width="395" alt="Screenshot 2023-07-07 at 6 47 59 PM" src="https://github.com/pingdotgg/uploadthing/assets/10962432/43ba6cf1-f12e-4402-b835-f1c02ad4ff18">

Similar errors for audio/mp3, audio/wav and video/mpeg etc

Additionally I also got a Type error for audio/mp3 or wav

```
Argument of type '{ 'audio/mp3': { maxFileSize: string; maxFileCount: number; }; video: { maxFileSize: "16MB"; maxFileCount: number; }; }' is not assignable to parameter of type 'FileRouterInputConfig'.
  Object literal may only specify known properties, and ''audio/mp3'' does not exist in type 'FileRouterInputConfig'.ts(2345)
```

### What did you expect to happen?

Expected it to restrict uploaded files based on the MIME Types I listed.

### Version

5.1.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Mr0Bread** [comment]
@btahir 

For wav you can try to use MIME type `audio/x-wav`
For mp3 `audio/mpeg` MIME Type should be used

**Comment by Mr0Bread** [comment]
Can't say anything specific regarding runtime issue you are having though

**Comment by Mr0Bread** [comment]
@markflorkowski There is definitely a bug. I opened a PR. Please take a look #215
