### ISSUE TITLE
[Bug]: onUpload - Failed to get Presigned URLs

### ISSUE THREAD

**Issue by Ironessence** [pingdotgg/uploadthing#216]
### What happened?

Hello! I have configured a basic example where I upload a photo, and on the local environment (localhost:3000) it seems to work without issues, the files do appear inside the UploadThing dashboard.

However, after pushing to github in production, and deploying on Vercel, when I press the button and select the image, it immediately says "Failed to get Presigned URLs". I have of course added the secret keys and ids into the variables fields inside Vercel. I also need to mention I have a custom domain on Vercel.

I have simply copied everything from docs in terms of code (core.ts, route.ts and the Button component).

### What did you expect to happen?

The files should have been uploaded directly

### Version

5.1.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by markflorkowski** [comment]
Do you get any additional errors in either the browser console, or in the Vercel log dashboard?

**Comment by markflorkowski** [comment]
Closing for now, feel free to reopen with additional info/reproduction.
