### ISSUE TITLE
Can't find a way to access uploaded file url

### ISSUE THREAD

**Issue by thebishalniroula** [pingdotgg/uploadthing#23]
The uploaded file url logs on the console but I cant find a way to access it.

**Comment by pavankpdev** [comment]
To access the uploaded files, you can navigate to the dashboard, then go to the "Files" section. 
Locate your uploaded file and click on it. This will open a new tab where you can copy the URL from the address bar.
@thebishalniroula

**Comment by kj-1809** [comment]
**To access the uploaded file url in the code :** 
You upload the file using the startUpload() function.
You can easily await that and get the url as it returns a promise.
`const data = await startUpload()`

`data` is an array of all the files uploaded.

So you can map through the array and access the fileUrl property.

`data.forEach((file) => {
    console.log(file.fileUrl)
    // do whatever you want with the url 
})`

Hope this helped !

**Comment by kj-1809** [comment]
Please close this issue if this fixed solved your issue !
Thanks

**Comment by kj-1809** [comment]
Please close this issue if this solved your issue !
Thanks

**Comment by thebishalniroula** [comment]
@kj-1809   Can you tell me where I can import the startUpload or useUploadThing hook from in the latest version of uploadthing?

**Comment by kj-1809** [comment]
Well , it was supported in uploadThing 1.x i guess now the version has already reached 3.x and an upload button has been added so checkout the docs for the latest syntax and features . Don't use `startUpload()`
