### ISSUE TITLE
[Bug]: Module '"@uploadthing/react"' has no exported member 'generateComponents'.

### ISSUE THREAD

**Issue by JuaniSilva** [pingdotgg/uploadthing#232]
### What happened?

I had a fully working app with uploadthing, suddnely I started to had some problems because I forgot to make public the webhook routes for uploadthing. Before realising that, I updated the dependencies since I noticed that it didn't match what the docs said for the installation.

When I tried to create the `uploadthing.ts` utils file with the react components the error `Module '"@uploadthing/react"' has no exported member 'generateComponents'.` appeared.

### What did you expect to happen?

I expected it to work since I was just following the [docs](https://docs.uploadthing.com/nextjs/appdir#creating-the-uploadthing-components-optional)

### Version

Version: `"@uploadthing/react": "^4.1.3", "uploadthing": "^4.1.3",`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by decca-dev** [comment]
same thing here

**Comment by markflorkowski** [comment]
Are you able to link a repository where you can reproduce this behaviour? Also, have you tried deleting your `node_modules` and `.next` and re-installing? What package manager are you using?

**Comment by JuaniSilva** [comment]
Im using npm and I've tried deleting those directory but it keeps throwing the same error

**Comment by markflorkowski** [comment]
Can you try using the latest `uploadthing@5.2.1`.

Also a simple reproduction repo (or if the repository you're working on is public, feel free to link it) would make it much easier for me to assist you

**Comment by markflorkowski** [comment]
Closing for now, Feel free to reopen with a repro if you are still running into this issue.
