### ISSUE TITLE
[Docs]: Introduction section uses outdated syntax for FileRouter input

### ISSUE THREAD

**Issue by Mr0Bread** [pingdotgg/uploadthing#236]
Here is the screenshot with exact spot
![image](https://github.com/pingdotgg/uploadthing/assets/55754540/e1143d52-d26e-472c-8f5c-907a410a1cfe)

While such option is still present, both Next.js and SolidStart guides refer to new syntax
![image](https://github.com/pingdotgg/uploadthing/assets/55754540/6657f414-318d-4b0f-8078-23a429ad536d)

So I guess it just tiny inconsistency

**Comment by markflorkowski** [comment]
These are both valid methods of using the FileRouter. The array is used if you don't want to specify any options, object if you do. 

cc @t3dotgg can you confirm that I am remembering this correctly?

**Comment by t3dotgg** [comment]
This is intentional. The introduction page has the simplest possible syntax, and the other pages show a bit more customization. The api docs show that both are valid :)
