### ISSUE TITLE
Trying to upload images with api

### ISSUE THREAD

**Issue by TejasBhovad** [pingdotgg/uploadthing#237]
I am trying to host user images using UploadThing 
here is the function I am using 
```js
  const handleImageUpload = async () => {
    try {
      // Send the image data to the server
      const response = await fetch("/api/uploadthing?slug=images", {
        method: "POST",
        body: uploadedImage,
        headers: {
          "Content-Type": "image/jpeg", // Adjust the content type as needed
        },
      });

      if (response.ok) {
        console.log("Image uploaded successfully!");
        // Handle any further actions after successful upload
      } else {
        console.error("Failed to upload image.");
      }
    } catch (error) {
      console.error("Error uploading image:", error);
    }
  };
```
I have never done this before, any clue on how can I upload the images via the api passing an id [I have it stored in `id`] and retrieve it using a fetch function?
Following the docs I have created core, route file in /uploadthing and installed necessary dependencies

**Comment by markflorkowski** [comment]
> any clue on how can I upload the images via the api passing an id

If I understand correctly, I think you are trying to pass metadata from the frontend to be used in middleware/server-side? If so, I think that [this example](https://github.com/pingdotgg/uploadthing/blob/76bfd39ecdc41a792ea32ceddb8760f3d4bce073/examples/appdir/src/app/sink/page.tsx#L27) is what you are looking for.

The endpoints are not really intended to be used directly without our components/hook, but if you do want to do that, I would suggest looking at the respective implementations to see how the fetch should work.

**Comment by TejasBhovad** [comment]
Is it necessary to use the UploadButton or UploadDropZone or we can declare custom components? It would be nice to know how these two work internally too.

**Comment by markflorkowski** [comment]
You can absolutely make your own custom components if you want. Check out [these docs](https://docs.uploadthing.com/api-reference/react#generatereacthelpers) for how to get started there. 

> It would be nice to know how these two work internally too.

The components are all open source in this repo. Here's the React ones:

https://github.com/pingdotgg/uploadthing/blob/main/packages/react/src/component.tsx

**Comment by TejasBhovad** [comment]
Thanks 😊 I will lok into it.
