### ISSUE TITLE
Question: About HIPAA Compliance

### ISSUE THREAD

**Issue by tdugan-vbtech** [pingdotgg/uploadthing#241]
Is Uploadthing HIPAA compliant? Is there potential to sign a BAA to certify HIPAA Compliance?

I'm building a health-fin-tech app that needs the ability to upload/ingest PII and PHI . If this uses S3 in the background then I think it should be possible bc AWS signs BAAs with companies to certify. I'll be building out the upload functionality for my app soon and was starting to research solutions, I'd much rather use Uploadthing than S3 directly.

**Comment by markflorkowski** [comment]
Uploadthing is not HIPAA compliant at this time. It is something that we may consider for the future, but given our current size, the required effort is currently to great for us to be able to justify.
