### ISSUE TITLE
Named export 'useDropzone' not found

### ISSUE THREAD

**Issue by JackRKelly** [pingdotgg/uploadthing#244]
### What happened?

I am receiving 
```
SyntaxError: Named export 'useDropzone' not found. The requested module 'react-dropzone' is a CommonJS module, which may not support all module.exports as named exports.
--
CommonJS modules can always be imported via the default export, for example using:
 
import pkg from 'react-dropzone';
const { useDropzone } = pkg;
 
at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)
at async ModuleJob.run (node:internal/modules/esm/module_job:190:5)
 
> Build error occurred
Error: Failed to collect page data for /settings
at /vercel/path0/node_modules/next/dist/build/utils.js:1156:15 {
type: 'Error'
}
```
a similar issue to https://github.com/pingdotgg/uploadthing/issues/42. I have made sure to include:
```
experimental: {
    esmExternals: false, // THIS IS THE FLAG THAT MATTERS
},
```

in my `next.config.cjs` which looks as follows:
```
import { withContentlayer } from "next-contentlayer"

await import("./env.mjs")

/** @type {import("next").NextConfig} */
const config = {
  reactStrictMode: true,
  images: {
    domains: ["d1kfeng928x8ln.cloudfront.net"],
  },
  i18n: {
    locales: ["en"],
    defaultLocale: "en",
  },
  experimental: {
    esmExternals: false,
  },
}

export default withContentlayer(config)
```

I have deleted and reinstalled/generated my `yarn.lock`, `node_modules`.

I am using `react-dropzone@14.2.3` & `@uploadthing/react@5.2.0`, `uploadthing@^5.3.0`  `next@^13.4.12`

Following https://github.com/pingdotgg/uploadthing/issues/42#issuecomment-1544397914 does resolve my issue, but obviously isn't sustainable.

Is there any requirement for the next.config to not be a commonjs file? I am using Next.js Pages directory

The concept of this library is great, thanks in advance for any help here!

### Version

`@uploadthing/react@^5.2.0`
`uploadthing@^5.3.0`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by juliusmarminge** [comment]
Reproduction repo plzzz

**Comment by JackRKelly** [comment]
For anyone encountering this issue, after building, make sure you see
```
- warn You have enabled experimental feature (esmExternals) in next.config.js.
```

Otherwise the 
```
  experimental: {
    esmExternals: false,
  },
```

flag isn't being picked up. I found the issue to be that my next config was `next.config.cjs` and for some reason, it was getting any of the flags passed there, so after converting it to off of commonjs. 

```
const withContentlayer = require("next-contentlayer").withContentlayer

require("./env.js")

/** @type {import("next").NextConfig} */
const config = {
  reactStrictMode: true,
  images: {
    domains: ["d1kfeng928x8ln.cloudfront.net"],
  },
  i18n: {
    locales: ["en"],
    defaultLocale: "en",
  },
  experimental: {
    esmExternals: false,
  },
}

module.exports = withContentlayer(config)
```
