### ISSUE TITLE
redirects problem when accessing files.

### ISSUE THREAD

**Issue by MohamedElguarir** [pingdotgg/uploadthing#282]
![image](https://github.com/pingdotgg/uploadthing/assets/120427922/8b0fb28e-f853-4e9d-b92a-3428939acdfc)

is there any way to access the files directly without this redirect ?

**Comment by markflorkowski** [comment]
No. Is there a particular reason you need this?

**Comment by markflorkowski** [comment]
Actually, I am not sure where you are running into this, are you getting files via `uploadthing.com/f/...` or `utfs.io/f/...`?

**Comment by MohamedElguarir** [comment]
> Actually, I am not sure where you are running into this, are you getting files via `uploadthing.com/f/...` or `utfs.io/f/...`?

it's not that big of a deal but, the redirect only happens if you access the image through `https://uploadthing.com/f`, which is the one returned by the onUploadComplete callback, but when accessed through `utfs.io/f/` the image is available directly.
the thing is even if the image is cached it won't be available until the redirect completes.

#### here when accessing the image through the `uploadthing.com/f/` with a slower network:

![image](https://github.com/pingdotgg/uploadthing/assets/120427922/e1b8a77c-0082-4918-9f17-ecbdc832edd1)
see it needs to be redirected first then the image will be available.

------
#### here when accessing the image through the `utfs.io/f/` with a slower network:

![image](https://github.com/pingdotgg/uploadthing/assets/120427922/4208a470-ae67-4381-a721-68d17c1c9e96)

the images are available instantly after the page is rendered, and also when cached.

**Comment by markflorkowski** [comment]
Latest versions of the package should be returning utfs.io links in the onUploadComplete

**Comment by MohamedElguarir** [comment]
Great, a lot man!
