### ISSUE TITLE
Feature request: ability to manually set upload progress

### ISSUE THREAD

**Issue by jthrilly** [pingdotgg/uploadthing#308]
In our NextJS app we want to do quite a bit of additional processing once a file has finished uploading (including triggering further uploads with uploadthing). Because the additional processing needs to happen server side, we are setting off this processing in the `onUploadComplete` callback of the file router, which works. What sucks is that the client side UI state of the built in components (as well as the data in the hook callbacks) just reflects that the _initial_ upload completed - not that we are still doing 'stuff'. 

It would be amazing if there were some way that we could control the progress (or even just the complete state) to allow us to factor our processing into the calculation. That way, anything using the `useUploadThing` hook, or the built-in components, would be able to benefit from more accurate UI state.

Should we be thinking about this a different way?

**Comment by juliusmarminge** [comment]
The order of execution and of the clientside and serverside onUploadComplete callbacks are currently undeterministic.

Maybe we should have a way to stall onClientUploadComplete until the server callback is done 🤔 I dont think this is straight forward but should be doable

**Comment by Mr0Bread** [comment]
@juliusmarminge From what I can see in the code, onClientUploadComplete should be called after server's callback
https://github.com/pingdotgg/uploadthing/blob/0f2c25ecf67dcb14c69d30f4c056fe7bf3b1fb64/packages/uploadthing/src/client.ts#L248-L249

Is it now working as intended right now or I'm missing something?

**Comment by Mr0Bread** [comment]
@juliusmarminge I'm not sure what happens on the server-side of UT, but I guess it returns the state of the file in the UTFS. So once file is fully uploaded, polling will be done and client-side callback invoked. Basically, state of file upload should be set to "DONE" only when server's onUploadComplete done it's work. Whether the webhook request should wait for response and change the state once it is received or another request to UT API should be done that will inform about the completion of server's onUploadComplete
cc @markflorkowski

**Comment by Mr0Bread** [comment]
@juliusmarminge do you mean that both client and server relies on polling? What the purpose of webhook than? I thought onUploadComplete on server is triggered by the webhook. It's the part about timings that confuse me.

I believe only the client should rely on polling since the server can be called by the UT. And if the client is the only relying on polling, there won't be any race conditions. It's just a matter of server to return proper response only when onServerUploadComplete is done

**Comment by Mr0Bread** [comment]
Ah, I see, it's about the dev mode

**Comment by Mr0Bread** [comment]
Hm, since the client is also aware of the upload progress and polls state of uploading from UT api, is it possible to trigger the webhook from the client? In dev mode only ofc

**Comment by markflorkowski** [comment]
That seems like 

> Hm, since the client is also aware of the upload progress and polls state of uploading from UT api, is it possible to trigger the webhook from the client? In dev mode only ofc

That seems a bit strange with the indirection, but we could do that, and i guess it would be a bit closer to the behaviour in prod since it would be a "real" webhook.

**Comment by Mr0Bread** [comment]
@markflorkowski @juliusmarminge I made a PR and a quick check. Seems to be working. Please take a look at https://github.com/pingdotgg/uploadthing/pull/313

**Comment by markflorkowski** [comment]
As of 6.0.0 clientside onUploadComplete is guaranteed to run after serverside onUploadComplete
