### ISSUE TITLE
[Feature]: Looking for bulk uploadFilesFromUrl 

### ISSUE THREAD

**Issue by Duckinm** [pingdotgg/uploadthing#323]
### What happened?

-

### What did you expect to happen?

Bulk operations on uploading from external url to uploadthing

### Version

-

### Link to reproduction

-

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by juliusmarminge** [comment]
What do you mean by bulk? You can send multiple URLs.

**Comment by Duckinm** [comment]
Oh my apologize! since I looked at the type and there nothing remind that it can accept array. This can be close now

Thank you
![Screenshot 2566-09-06 at 19 37 53](https://github.com/pingdotgg/uploadthing/assets/29366271/6e84fbef-5fb4-40cc-9561-3ab1b27c4616)

**Comment by juliusmarminge** [comment]
I'll update docs!
