### ISSUE TITLE
Why do I keep getting "[UT] Call unsuccessful after X tries" logged out?

### ISSUE THREAD

**Issue by tiagoinaba** [pingdotgg/uploadthing#328]
I don't know if I'm doing something wrong, but does anyone know what's happening? I followed the docs to implement it.

Next: 13.4.19
React: 18.2.0
UT: 5.5.0

![image_2023-09-06_130150228](https://github.com/pingdotgg/uploadthing/assets/122808226/22222162-5bb5-4ad5-8820-82a4d03b69dd)

**Comment by juliusmarminge** [comment]
Our webhook simulation in dev is a bit broken which is what causes this...

**Comment by tiagoinaba** [comment]
Got it! Thank you!

**Comment by juliusmarminge** [comment]
Hey - can you confirm your API endpoint is using the edge runtime? i.e. do you have `export const runtime = "edge"` in your `api/uploadthing/route.ts` file?

**Comment by tiagoinaba** [comment]
Hi, it is not. To set it up I just copy  pasted the code from the docs.

**Comment by juliusmarminge** [comment]
Huh - then it could be that you're trying to upload a too large file to s3? Can you check the response in the network tab of the s3 call?

**Comment by tiagoinaba** [comment]
Weird, I'm not able to replicate it anymore. I'll post again if it happens. Thank you @juliusmarminge!

**Comment by tiagoinaba** [comment]
> Huh - then it could be that you're trying to upload a too large file to s3? Can you check the response in the network tab of the s3 call?

Yup, this was it. Sorry for the facepalm.

**Comment by jackblanc** [comment]
> Hey - can you confirm your API endpoint is using the edge runtime? i.e. do you have `export const runtime = "edge"` in your `api/uploadthing/route.ts` file?

I'm encountering this issue in development only when using the edge runtime. It works fine in production on the edge runtime, just not in development. I was able to fix it by setting the runtime to `nodejs` for the upload thing api route.

```
// src/app/api/uploadthing/route.ts
export const runtime = "nodejs";
```

**Comment by juliusmarminge** [comment]
> I'm encountering this issue in development only when using the edge runtime

This is a Next.js limitation since they dont allow edge functions to fetch themselves, which is what the dev hook is doing (in prod the callback request comes from UT server). We have tried getting the Next.js team to provide an option to override this behavior but they havent done so

**Comment by glennhkm** [comment]
i got same problem for development, anyone can help me?

**Comment by TrentFleet** [comment]
Same issue here :(

**Comment by kenta23** [comment]
i have the same issue here, does this issue already addressed ? my application works fine in production but not when already deployed in vercel the upload callbacks didnt work
