### ISSUE TITLE
Feature request - CLI like ix.io

### ISSUE THREAD

**Issue by thecmdrunner** [pingdotgg/uploadthing#33]
`ix.io` is like pastebin used through CLI.
The CLI for `ix.io` lets you upload contents with just one command and spits out a public link.

I think it'd be great if UploadThing allows uploading files via CLI too, for example:

```zsh
upth index.js
```

Output:

```shell
https://uploadthing.com/.../index.js
```

Here's a YT short on the `ix.io` CLI
https://youtu.be/7S46krsF1KI

**Comment by t3dotgg** [comment]
This is cool but doesn't feel super aligned w/ what we're trying to build. Like imo this would be cooler w/ a google drive plugin than an UploadThing one. Our focus is making file upload authorization, authentication and distribution easier

Ty for sharing, will keep this in mind!

**Comment by CryogenicPlanet** [comment]
made a tiny one for myself here https://github.com/CryogenicPlanet/upt-cli (only works with bun)
