### ISSUE TITLE
Issue: Cannot read properties of undefined (reading 'GET') (Vercel Build Error)

### ISSUE THREAD

**Issue by RavenWits** [pingdotgg/uploadthing#331]
Hi there I am trying to implement this on Next 13 with app route. Everything working fine on dev environment, I can build on my dev environment too and everything works as expected until I try to deploy my app on Vercel. 

Please see the error on attached build log:
[builderror .txt](https://github.com/pingdotgg/uploadthing/files/12543562/builderror.txt)

This is my app/api/uploadthing/route.ts file:
```typescript
import { NextResponse } from "next/server";
import { createNextRouteHandler } from "uploadthing/next";
import { utapi } from "uploadthing/server";

import { auth } from "@acme/auth";

import { uploadFileRouter } from "./core";

// Export routes for Next App Router
export const { GET, POST } = createNextRouteHandler({
  router: uploadFileRouter,
  config: {
    uploadthingId: process.env.UPLOADTHING_APP_ID,
    uploadthingSecret: process.env.UPLOADTHING_SECRET,
  },
});

export async function DELETE(req: Request) {
  try {
    const { user } = await auth();
    const urls = await req.json();

    if (!user) {
      return new NextResponse("Unauthorized", { status: 403 });
    }

    const res = await utapi.deleteFiles(urls);

    return NextResponse.json(res);
  } catch (error) {
    console.log("[UPLOADTHING_DELETE]", error);
    return new NextResponse("Internal error", { status: 500 });
  }
}

``` 

As I've mentioned that everything is OK on my local. If I try to go to localhost:3000/api/uploadthing it returns my router as expected:
```javascript
[{"slug":"imageUploader","config":{"image":{"maxFileSize":"4MB","maxFileCount":5}}}]
``` 

If anyone has encountered such a situation before, I would appreciate it if they can point me to the right direction.

Thanks

**Comment by juliusmarminge** [comment]
Do you have a reproduction repo we can look at? The code you put here looks solid so I don't see a problem there, so without a repro it's hard to investigate further.

**Comment by RavenWits** [comment]
I am also using t3-turbo-app of course with tRPC but I don't think it is relevant to this issue though. I will try to provide a repro as soon as I can.

**Comment by RavenWits** [comment]
Edit: Actually I've updated my trpc and migrated to v10 from v9 solved the issue. I don't know how its related but in case anyone using tRPC with uploadthing encounters this error on build phase I suggest them to update tRPC to latest version. Thanks.
