### ISSUE TITLE
Error while importing type FileRouter in core.ts

### ISSUE THREAD

**Issue by Rishabh-Singh-Codes** [pingdotgg/uploadthing#337]
Coming across the above error in app/api/uploadthing/core.ts file while importing.
`import { createUploadthing, type FileRouter } from "uploadthing/next";`

Complete core.ts code: 
```
import { auth } from "@clerk/nextjs";
import { createUploadthing, type FileRouter } from "uploadthing/next";
 
const f = createUploadthing();
 
const handleAuth = () => {
  const { userId } = auth();
  if (!userId) throw new Error("Unauthorized");
  return { userId: userId };
}

export const ourFileRouter = {
  serverImage: f({ image: { maxFileSize: "4MB", maxFileCount: 1}})
  .middleware(() => handleAuth())
  .onUploadComplete(() => {}),
  messageFile: f(["image", "pdf"])
  .middleware(() => handleAuth())
  .onUploadComplete(() => {})
} satisfies FileRouter;
 
export type OurFileRouter = typeof ourFileRouter;
```

Errors: 
1. Individual declarations in merged declaration 'FileRouter' must be all exported or all local.ts(2395)
2. Variable 'satisfies' implicitly has an 'any' type.ts(7005)
3. Variable 'FileRouter' implicitly has an 'any' type.ts(7005)
<img width="875" alt="Screenshot 2023-09-09 at 12 58 24 PM" src="https://github.com/pingdotgg/uploadthing/assets/86565216/b67c70cd-91a9-4315-b729-ec4b78d22eab">

Versions:
```
    "uploadthing": "^5.3.3",
    "@uploadthing/react": "^5.3.0",
    "react-dropzone": "^14.2.3",
```

Even with latest versions, I'm getting the same issues.

**Comment by Mr0Bread** [comment]
What is your typescript version? Have you tried to reinstall node modules? Have you tried to restart TS server?

**Comment by markflorkowski** [comment]
> Variable 'satisfies' implicitly has an 'any' type.ts(7005)

This sounds like you are on a version of typescript older than 4.9, where `satisfies` was introduced.

**Comment by Rishabh-Singh-Codes** [comment]
> > Variable 'satisfies' implicitly has an 'any' type.ts(7005)
> 
> This sounds like you are on a version of typescript older than 4.9, before `satisfies` was introduced.

"typescript": "5.2.2",

**Comment by juliusmarminge** [comment]
Do you have a repro we can use to debug?

**Comment by Rishabh-Singh-Codes** [comment]
> Do you have a repro we can use to debug?

I'm using uploadThing in [Baate](https://github.com/Rishabh-Singh-Codes/baate).

**Comment by Rishabh-Singh-Codes** [comment]
> Do you have a repro we can use to debug?

I'm using uploadThing in [Baate](https://github.com/Rishabh-Singh-Codes/baate).

**Comment by juliusmarminge** [comment]
I don't see this error when cloning your repo:

<img width="813" alt="CleanShot 2023-09-12 at 17 55 24@2x" src="https://github.com/pingdotgg/uploadthing/assets/51714798/6e91bf70-9bc4-43cc-9c43-6d8ed6752772">

Maybe your IDE isn't using TypeScript >= 4.9. You can check what version your VSCode is using by

`CMD+Shift+P` => Search `Select Type...` => Choose `TypeScript: Select TypeScript version...` => Check what version is selected:

<img width="664" alt="CleanShot 2023-09-12 at 17 56 46@2x" src="https://github.com/pingdotgg/uploadthing/assets/51714798/99cc26a1-41df-4e7b-b42c-1602996f232d">

<img width="725" alt="CleanShot 2023-09-12 at 17 56 02@2x" src="https://github.com/pingdotgg/uploadthing/assets/51714798/e2811338-c278-4801-9d80-c9828fb1a6f1">

**Comment by Rishabh-Singh-Codes** [comment]
Thank you @juliusmarminge, that was the issue indeed.
