### ISSUE TITLE
utapi uploadFiles error

### ISSUE THREAD

**Issue by ziming-yuan** [pingdotgg/uploadthing#338]
The uploadFiles api gave the following error when I deployed it to Vercel and tried to upload files there:
```
(node:9) ExperimentalWarning: buffer.File is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
Promise {
  <pending>,
  [Symbol(async_id_symbol)]: 2708,
  [Symbol(trigger_async_id_symbol)]: 2594,
  [Symbol(kResourceStore)]: {
    requestId: '2',
    serverId: '2d4e7759-f84b-4b12-bff7-09fad562acde',
    n1RequestId: undefined,
    vercelId: 'iad1::wnrsc-1694405713521-a6b657fedbd4'
  },
  [Symbol(kResourceStore)]: {
    headers: [Getter],
    cookies: [Getter],
    mutableCookies: [Getter],
    draftMode: [Getter]
  },
  [Symbol(kResourceStore)]: {
    isStaticGeneration: false,
    pathname: '/edit/[path]',
    originalPathname: '/edit/[path]/page',
    incrementalCache: IncrementalCache {
      locks: Map(0) {},
      unlocks: Map(0) {},
      dev: false,
      minimalMode: true,
      requestHeaders: [Object],
      requestProtocol: 'https',
      allowedRevalidateHeaderKeys: undefined,
      prerenderManifest: [Object],
      fetchCacheKeyPrefix: '',
      cacheHandler: [FetchCache]
    },
    isRevalidate: false,
    isPrerendering: undefined,
    fetchCache: undefined,
    isOnDemandRevalidate: false,
    isDraftMode: false,
    fetchMetrics: [ [Object] ],
    tags: [ '/edit/[path]/page' ],
    revalidate: 0,
    nextFetchId: 2
  },
  [Symbol(kResourceStore)]: undefined,
  [Symbol(kResourceStore)]: { isAction: true }
}

```
This is the code I used, the website is accessible [here](https://alignment-calendar.vercel.app/upload-plain):
```
import { utapi } from "uploadthing/server";

async function uploadFiles(formData) {
    "use server";
    try {
        const files = await formData.getAll("files");
        const response = await utapi.uploadFiles(files);
    } catch (e) {
        console.log(e);
    }
    //    ^? UploadedFileResponse[]
}

export default function MyForm() {
    return (
        <form action={uploadFiles}>
            <input name="files" type="file" multiple />
            <button type="submit">Upload</button>
        </form>
    );
}
```
This is my current uploadthing version:
```
 "@uploadthing/react": "^5.5.0",
 "uploadthing": "^5.5.3"
 ```

**Comment by Mr0Bread** [comment]
It seems to be a warning, not an error. Is your server action failing?

**Comment by ziming-yuan** [comment]
Yes, the file is never uploaded. The only thing I got was this warning on the Vercel log.

**Comment by Mr0Bread** [comment]
Locally working fine? What runtime are you using? Serverless or edge?

**Comment by ziming-yuan** [comment]
It works locally. I'm using Nextjs 13 so I think it's serverless?

**Comment by markflorkowski** [comment]
What version of Node? Does it work correctly locally and only fails on Vercel, or do you get the same issue in local dev?

**Comment by ziming-yuan** [comment]
I am on node v18.17.1

**Comment by markflorkowski** [comment]
cc @juliusmarminge any ideas on this one? Got one other report of this from another user

**Comment by juliusmarminge** [comment]
> I am on node v18.17.1

Is this your node version or the version on the deployed lambda?

**Comment by t3dotgg** [comment]
I was unable to repro using your exact code :( are you sure you have the env variables set up correctly?

<img width="559" alt="image" src="https://github.com/pingdotgg/uploadthing/assets/6751787/91b23fab-35bd-443e-920d-bdf8ea50f582">

**Comment by t3dotgg** [comment]
Source for my working example: https://github.com/t3dotgg/ut-url-upload-example/blob/main/src/app/form/page.tsx

Please make sure you're running the latest Node 18 version and that your env variables are set correctly

**Comment by ziming-yuan** [comment]
Thanks so much for the example. It turned that I installed uploadthing as dev-dependencies rather than dependencies. That caused the deployment to fail.
