### ISSUE TITLE
Multiple file upload with uploadButton

### ISSUE THREAD

**Issue by kj-1809** [pingdotgg/uploadthing#37]
Apparently , it's not possible to add multiple files while using uploadButton.

**Comment by Gaurav-r-a-j** [comment]
To upload multiple files using uploadbutton or uploaddropzone you need to set maxFilecount here 


export const ourFileRouter = {
  // Define as many FileRoutes as you like, each with a unique routeSlug
  imageUploader: f({ image: { maxFileSize: "4MB"  , maxFileCount:10} }) // setting maxfilecoutn to allow mulitple file upload
    // Set permissions and file types for this FileRoute
    .middleware(async ({ req }) => {
      // This code runs on your server before upload
      const user = await auth(req);

      // If you throw, the user will not be able to upload
      if (!user) throw new UploadThingError("Unauthorized");

      // Whatever is returned here is accessible in onUploadComplete as `metadata`
      return { userId: user.id };
    })
    .onUploadComplete(async ({ metadata, file }) => {
      // This code RUNS ON YOUR SERVER after upload
      console.log("Upload complete for userId:", metadata.userId);

      console.log("file url", file.url);

      // !!! Whatever is returned here is sent to the clientside `onClientUploadComplete` callback
      return { uploadedBy: metadata.userId };
    }),
} satisfies FileRouter;
