### ISSUE TITLE
[Bug]:  TypeError: Cannot read properties of undefined (reading 'url')

### ISSUE THREAD

**Issue by Fares-Fuad** [pingdotgg/uploadthing#372]
### What happened?

When I try to upload an image I get this error msg 
`- error TypeError: Cannot read properties of undefined (reading 'url')
    at eval (webpack-internal:///(rsc)/./node_modules/uploadthing/dist/chunk-LQBAB5WK.mjs:257:36)
    at Object.POST (webpack-internal:///(rsc)/./node_modules/uploadthing/dist/chunk-66XXRAVC.mjs:285:32)
`

### What did you expect to happen?

should upload without any issue

### Version

```
  "uploadthing": "^5.6.1"
  "@uploadthing/react": "^5.6.1",
```

### Reproduction Steps

the files like this 
app/api/uploadthing/core.ts
```
import { createUploadthing, type FileRouter } from 'uploadthing/next';

const f = createUploadthing();

// FileRouter for your app, can contain multiple FileRoutes
export const ourFileRouter = {
	// Define as many FileRoutes as you like, each with a unique routeSlug
	imageUploader: f({ image: { maxFileSize: '4MB' } }).onUploadComplete(
		async ({ metadata, file }) => {
			// This code RUNS ON YOUR SERVER after upload
			console.log('Upload complete for userId:');

			console.log('file url', file.url);
		}
	),
} satisfies FileRouter;

export type OurFileRouter = typeof ourFileRouter;
```

app/api/uploadthing/route.ts

```
import { createNextRouteHandler } from 'uploadthing/next';

import { ourFileRouter } from './core';

// Export routes for Next App Router
export const { GET, POST } = createNextRouteHandler({
	router: ourFileRouter,
	
});


```

utils/uploadthing.ts

```
import { generateComponents } from '@uploadthing/react';

import type { OurFileRouter } from '@/app/api/uploadthing/core';

export const { UploadButton, UploadDropzone, Uploader } =
	generateComponents<OurFileRouter>();

```

and the component like this: 

```
'use client'
import {  UploadDropzone } from '@/utils/uploadthing';

import '@uploadthing/react/styles.css';

const Uploader = () => {
	return (
    <UploadDropzone
        endpoint="imageUploader"
        onClientUploadComplete={(res) => {
          // Do something with the response
          console.log("Files: ", res);
          alert("Upload Completed");
        }}
        onUploadError={(error: Error) => {
          // Do something with the error.
          alert(`ERROR! ${error.message}`);
        }}
      />
	);
};

export default Uploader;

```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by juliusmarminge** [comment]
Works for me, can you provide a reproduction repo please?

<img width="793" alt="CleanShot 2023-09-19 at 14 33 10@2x" src="https://github.com/pingdotgg/uploadthing/assets/51714798/722ea3eb-8b2c-43bb-8ea5-3dc1c7b7c88e">

**Comment by St1ggy** [comment]
I have the same problem

**Comment by Fares-Fuad** [comment]
> Works for me, can you provide a reproduction repo please?
> <img alt="CleanShot 2023-09-19 at 14 33 10@2x" width="793" src="https://user-images.githubusercontent.com/51714798/268955344-722ea3eb-8b2c-43bb-8ea5-3dc1c7b7c88e.png">

just follow the docs

**Comment by Fares-Fuad** [comment]
> I have the same problem

try to downgrade to [5.3.0]

**Comment by St1ggy** [comment]
> > Works for me, can you provide a reproduction repo please?
> > <img alt="CleanShot 2023-09-19 at 14 33 10@2x" width="793" src="https://user-images.githubusercontent.com/51714798/268955344-722ea3eb-8b2c-43bb-8ea5-3dc1c7b7c88e.png">
> 
> just follow the docs

I did.



> > I have the same problem
> 
> try to downgrade to [5.3.0]

That breaks some types.

**Comment by juliusmarminge** [comment]
Working minimal repo here: https://github.com/juliusmarminge/ut-repro

Without a consistent reproduction repo, unfortunately we will not be able to help you any further. Feel free to reopen with a link to a repo where you can reproduce this error.

**Comment by St1ggy** [comment]
Not minimal, but anyway bugged: https://github.com/St1ggy/discord-clone/tree/uploadthing-bug
1. `git clone https://github.com/St1ggy/discord-clone/tree/uploadthing-bug`
2. `git checkout uploadthing-bug`
3. Create a .env and put in your secrets
4. `bun i`
5. `bun dev`
6. Upload file. Meet the bug.

**Comment by juliusmarminge** [comment]
Works fine on my machine

<img width="829" alt="CleanShot 2023-09-19 at 21 33 25@2x" src="https://github.com/pingdotgg/uploadthing/assets/51714798/f36a3b8c-69e3-4ae8-afc2-39437086f12e">
