### ISSUE TITLE
Some sort of UI bug in Next JS Pages

### ISSUE THREAD

**Issue by kj-1809** [pingdotgg/uploadthing#38]
When I upload a file it show me this : 
![Screen Shot 2023-05-11 at 6 18 18 PM](https://github.com/pingdotgg/uploadthing/assets/88274406/49ac3d4e-62e6-4670-acdd-6a373e454f93)

**Comment by markflorkowski** [comment]
Looks like you're not importing the styles for the components

**Comment by markflorkowski** [comment]
Updated pagedir docs to include style imports and a comment about them
