### ISSUE TITLE
[bug]: React Button component isn't keyboard-focusable

### ISSUE THREAD

**Issue by HugeLetters** [pingdotgg/uploadthing#391]
### Provide environment information

```bash
...
```

### Describe the bug

Since the input element inside has a [hidden](https://github.com/pingdotgg/uploadthing/blob/a421df3b26236f939ea569c80c6472da07895049/packages/react/src/components/button.tsx#L108) class keyboard navigation for it is disabled. 

My fix suggestion would be to either replace `hidden` with `absolute w-0 h-0 opacity-0` or put `tabindex=0` on the root div like you do for Dropbox component. 

### Link to reproduction

https://stackblitz.com/edit/github-jvitfq?file=src%2Fapp%2Fpage.tsx

### To reproduce

I've added a red background to focused elements in the link above to showcase the issue more clearly - dropbox and native input have the background when using TAB to navigate, button component does not.

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by markflorkowski** [comment]
Good callout! Will get a pr up for this soon

**Comment by markflorkowski** [comment]
Will be in the next release!
