### ISSUE TITLE
`pnpm dev` fails the first time you run it

### ISSUE THREAD

**Issue by t3dotgg** [pingdotgg/uploadthing#4]
ONLY WHEN WORKING ON THIS REPO TO BE CLEAR

This bug is because `@uploadthing/react` depends on `uploadthing`, but you can't block in dev or it will block forever. I tried hacking this with a `prebuild` step before but it was buggy as hell. Surprised there's no recommendations here

**Comment by Nazeeh21** [comment]
Can I give this a shot?
