### ISSUE TITLE
generateReactHelpers is not exported from '@uploadthing/react'

### ISSUE THREAD

**Issue by Caketime** [pingdotgg/uploadthing#40]
<img width="1053" alt="image" src="https://github.com/pingdotgg/uploadthing/assets/85681889/ad4f410b-9e0a-4927-9c6e-71afa2f3f41e">

I just updated from 2.0.5 to 3.0.1 and now I'm getting this error.

It seems to be there in the uploadthing code, but somehow it's not exported correctly? I don't quite know what's the issue
<img width="632" alt="image" src="https://github.com/pingdotgg/uploadthing/assets/85681889/8f0f75e5-cfa0-4d11-bc3b-45389d58c889">

<img width="501" alt="image" src="https://github.com/pingdotgg/uploadthing/assets/85681889/f1a6f350-5328-4b6b-8fa8-07c4583805b1">

**Comment by MichaelSmithAI** [comment]
Seeing a similar issue when importing UploadButton in the way the docs suggested on the latest update.
![image](https://github.com/pingdotgg/uploadthing/assets/125163302/12d31fba-bee2-4320-aec7-1df7a2178c64)

**Comment by t3dotgg** [comment]
Anyone have a repro in a codesandbox? Would make this much easier for us to debug

**Comment by Caketime** [comment]
Sorry, I've tried and failed to put it in a codesandbox (ngl, i've never used a codesandbox for anything other than basic css/html stuff but I'll keep trying ...) @MichaelSmithAI Maybe you could reproduce it in a codesandbox? 😅 🤔 

Maybe I can help you by providing additional information though?

I've been using pnpm. When I import @uploadthing/react it links to this file:
`node_modules/.pnpm/@uploadthing+react@3.0.2-canary.9ebcffa_react-dropzone@14.2.3_react@18.2.0_uploadthing@3.0.2-canary.9ebcffa/node_modules/@uploadthing/react/dist/index.d.ts`

Which looks like this:
<img width="1290" alt="image" src="https://github.com/pingdotgg/uploadthing/assets/85681889/0769f42e-06dc-4056-8d74-12b647602e28">

Using npm instead I get different path (obviously) but the same file:
`node_modules/@uploadthing/react/dist/index.d.ts`

<img width="1029" alt="image" src="https://github.com/pingdotgg/uploadthing/assets/85681889/75e5777b-96f5-4d6c-aad6-2c95084f07a8">

Deleting node_modules and the lock file and reinstalling didn't help 😕 

pnpm version: `8.5.0`
npm version: `8.5.5`

These are my dependencies:
```
"dependencies": {
    "@clerk/nextjs": "^4.17.3",
    "@prisma/client": "^4.11.0",
    "@t3-oss/env-nextjs": "^0.2.1",
    "@tanstack/react-query": "^4.28.0",
    "@trpc/client": "^10.18.0",
    "@trpc/next": "^10.18.0",
    "@trpc/react-query": "^10.18.0",
    "@trpc/server": "^10.18.0",
    "@uploadthing/react": "3.0.2-canary.9ebcffa",
    "@upstash/ratelimit": "^0.4.2",
    "@upstash/redis": "^1.20.6",
    "dayjs": "^1.11.7",
    "next": "^13.2.4",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-dropzone": "^14.2.3",
    "react-hook-form": "^7.43.9",
    "react-hot-toast": "^2.4.1",
    "superjson": "1.12.2",
    "uploadthing": "3.0.2-canary.9ebcffa",
    "zod": "^3.21.4"
  },
  "devDependencies": {
    "@types/eslint": "^8.21.3",
    "@types/node": "^18.15.5",
    "@types/prettier": "^2.7.2",
    "@types/react": "^18.0.28",
    "@types/react-dom": "^18.0.11",
    "@typescript-eslint/eslint-plugin": "^5.56.0",
    "@typescript-eslint/parser": "^5.56.0",
    "autoprefixer": "^10.4.14",
    "eslint": "^8.36.0",
    "eslint-config-next": "^13.2.4",
    "postcss": "^8.4.21",
    "prettier": "^2.8.6",
    "prettier-plugin-tailwindcss": "^0.2.6",
    "prisma": "^4.11.0",
    "tailwindcss": "^3.3.0",
    "typescript": "^5.0.2"
  },
  "ct3aMetadata": {
    "initVersion": "7.12.1"
  }
```

**Comment by Caketime** [comment]
Wait. I'm just reading the examples on npmjs.com (https://www.npmjs.com/package/@uploadthing/react)

I suppose you completely broke the previous way of using uploadthing with version >3.0.0? 😓 😅

**Comment by Arechii** [comment]
This is how you can import generateReactHelpers for now, since it's not re-exported through index (yet):
```ts
import { generateReactHelpers } from "@uploadthing/react/hooks";
```

**Comment by Caketime** [comment]
You're a hero. Thank you!

**Comment by Caketime** [comment]
I think this is the solution. @MichaelSmithAI hope you don't mind me closing this issue. 🙏🏼
