### ISSUE TITLE
[bug]: When uploaded file name is Chinese, node fetch download will get error :"HPE_INVALID_HEADER_TOKEN"

### ISSUE THREAD

**Issue by ezingme** [pingdotgg/uploadthing#402]
### Provide environment information

```bash
System:
    OS: macOS 13.3.1
    CPU: (8) x64 Intel(R) Core(TM) i7-8569U CPU @ 2.80GHz
    Memory: 1.97 GB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 18.17.1 - ~/.nvm/versions/node/v18.17.1/bin/node
    npm: 9.6.7 - ~/.nvm/versions/node/v18.17.1/bin/npm
    pnpm: 8.7.5 - ~/.nvm/versions/node/v18.17.1/bin/pnpm
  Browsers:
    Chrome: 117.0.5938.92
    Safari: 16.4
  npmPackages:
    @uploadthing/react: ^5.6.1 => 5.6.1 
    typescript: ^5.1.3 => 5.2.2 
    uploadthing: ^5.6.1 => 5.6.1
```

### Describe the bug

When uploaded file name is Chinese, node fetch download will get error :"HPE_INVALID_HEADER_TOKEN"

I think Content-Disposition filename  should be encoded.

### Link to reproduction

no

### To reproduce

upload a unicode name file  and download it using node fetch.

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

**Comment by opti21** [comment]
Getting the same error except the file name has a Dash in it: YouTube – GA4 Downloads v2.png

```
Content-Disposition:
inline; filename="YouTube  GA4 Downloads v2.png
```

**Comment by markflorkowski** [comment]
> I think Content-Disposition filename should be encoded.

Seems likely. Will take a look in the morning.

**Comment by markflorkowski** [comment]
Fix has been merged, everything seems to be alright on my end, but feel free to reopen if you are still running into issues. 

Previously uploaded files will still be broken, but if you DM me (markr) with the file keys on discord (or email mark@ping.gg) I can correct them for you. All new file uploads should work without issue though.
