### ISSUE TITLE
[Bug]: Can't create Application in Dashboard

### ISSUE THREAD

**Issue by Averbea** [pingdotgg/uploadthing#418]
### What happened?

Signed up via GitHub and wanted to create a new Application.
Nothing happened.

### What did you expect to happen?

New Application should be created 

### Version

current version from uploadthing.com. (I don't see any version number here)

### Reproduction Steps

- Go to https://uploadthing.com/dashboard/new
- Enter Application name 
- Press button "Create App"
- Nothing happens on Page. Console output:
![image](https://github.com/pingdotgg/uploadthing/assets/42838519/21d3ec7d-528e-49aa-a324-db60475baf61)

### Relevant log output

```bash
see "Reproduction Steps"
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by heyitsnate** [comment]
Yes, experiencing the same issue right now as well. I have the same error.

**Comment by juliusmarminge** [comment]
Sorry about that, Fixed on latest deploy

Same as https://github.com/pingdotgg/uploadthing/issues/419
