### ISSUE TITLE
not able to create new app

### ISSUE THREAD

**Issue by KartikDevarde2601** [pingdotgg/uploadthing#419]
am experiencing difficulties while attempting to create a new app .The app creation process is failing, and I need assistance to resolve this issue. 
<img width="953" alt="image" src="https://github.com/pingdotgg/uploadthing/assets/126013799/80cdf5dc-c9d9-4720-9573-3a6be8c50e58">

**Comment by ProfNuru** [comment]
Same here

**Comment by juliusmarminge** [comment]
Sorry bout this, it's fixed now
