### ISSUE TITLE
[bug]: This is the bug I am facing with uploadthing

### ISSUE THREAD

**Issue by susanta96** [pingdotgg/uploadthing#423]
### Provide environment information

```bash
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.18.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.4.2 - /usr/local/bin/npm
    pnpm: 8.6.12 - /usr/local/bin/pnpm
  npmPackages:
    @uploadthing/react: ^5.6.2 => 5.6.2 
    typescript: 5.2.2 => 5.2.2 
    uploadthing: ^5.7.1 => 5.7.1
```

### Describe the bug

Whenever I try to upload the image , previously tried with pdf also. its failing for no reason.

### Link to reproduction

https://stackblitz.com/edit/stackblitz-starters-c1zkek?file=utils%2Fuploadthing.ts

### To reproduce

Just change, the env with your credential and try ... I tried with the above link, and you can see, If a simple basic application without any other major change. just like docs. 

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by markflorkowski** [comment]
Stackblitz uses deprecated Node 16 which has known issues. Can you test it out locally and make sure you're using Node 18?

```npx degit pingdotgg/uploadthing/examples/minimal-appdir ut-test```

For me it works just fine.

**Comment by markflorkowski** [comment]
I also downloaded the code from your stackblitz and ran it locally with no issue.

**Comment by susanta96** [comment]
Okay. I will try it locally & see ..

**Comment by markflorkowski** [comment]
We merged a fix yesterday so it should now work in stackblitz as well. Just tested your example and it worked for me. 

Feel free to reopen if you are still running into issues.
