### ISSUE TITLE
[bug]: onUploadComplete not being called in production environment

### ISSUE THREAD

**Issue by jcappel** [pingdotgg/uploadthing#427]
### Provide environment information

```bash
System:
    OS: macOS 12.3
    CPU: (10) arm64 Apple M1 Pro
    Memory: 5.56 GB / 32.00 GB
    Shell: 3.5.1 - /opt/homebrew/bin/fish
  Binaries:
    Node: 19.4.0 - ~/.nvm/versions/node/v19.4.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v19.4.0/bin/yarn
    npm: 9.2.0 - ~/.nvm/versions/node/v19.4.0/bin/npm
  Browsers:
    Chrome: 118.0.5993.70
    Safari: 15.4
  npmPackages:
    @uploadthing/react: ^5.6.2 => 5.6.2 
    typescript: 5.2.2 => 5.2.2 
    uploadthing: ^5.7.1 => 5.7.1
```

### Describe the bug

The `onUploadComplete` function is not being executed in a Next.js production environment.

The callback works fine in a next.js dev environment but as a soon as its being run in a production environment the callback won't execute, although the file is uploaded successful.

I reproduced the error using the uploadthing [minimal-appdir](https://github.com/pingdotgg/uploadthing/tree/main/examples/minimal-appdir) as well as the [minimal-pagedir](https://github.com/pingdotgg/uploadthing/tree/main/examples/minimal-pagedir) example.

### Link to reproduction

https://github.com/pingdotgg/uploadthing/tree/main/examples/minimal-appdir

### To reproduce

Work either with the [minimal-appdir](https://github.com/pingdotgg/uploadthing/tree/main/examples/minimal-appdir) or the [minimal-pagedir](https://github.com/pingdotgg/uploadthing/tree/main/examples/minimal-pagedir) example. 

1. Build the project. I reproduced the problem using either `bun` or `npm`. 
2. Start the build.
3. Upload a file
4. The console log `console.log("upload completed", file);` won't appear although the its uploaded successful.
5. (The middleware runs normal).

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by juliusmarminge** [comment]
This only happens for running a production build locally, since the UT server can't hit your `localhost` endpoint.
