### ISSUE TITLE
This links dont redirect to nothing, shows 404 next page error. 

### ISSUE THREAD

**Issue by LeoCaprile** [pingdotgg/uploadthing#428]
https://github.com/pingdotgg/uploadthing/blob/cc6ba5161c4361d7d08717d7ece91544e2072a80/docs/src/pages/backend-adapters/express.mdx#L94

**Comment by juliusmarminge** [comment]
Fixed in #425

**Comment by LeoCaprile** [comment]
You might need to validate all links 
![image](https://github.com/pingdotgg/uploadthing/assets/71847541/06b88466-980e-4e96-9eac-db62f9082a4e)

In all of these pages, because is failing in express the link to solid, in fastify all links, in Lambda solid, and in H3 all links.
![image](https://github.com/pingdotgg/uploadthing/assets/71847541/c556161f-4d3f-4626-98fd-bbdb71bbd5a0)
