### ISSUE TITLE
feat: Failed uploads should not be returned via utapi.listfiles()

### ISSUE THREAD

**Issue by JEK58** [pingdotgg/uploadthing#429]
### Describe the feature you'd like to request

Failed uploads should not be returned when calling `utapi.listfiles()` or `utapi.getFileUrls(failedUploadKey)`
Right now there is no way to see if a file url actually works, or not.

### Describe the solution you'd like to see

Either do not return failed uploads, or add a status property to filter them out.

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

**Comment by markflorkowski** [comment]
Good call. Will get this out today 👍

**Comment by markflorkowski** [comment]
listFiles should now include a `status` field, matching with what shows on the dashboard

**Comment by JEK58** [comment]
You guys are impressively fast! Thanks!

**Comment by JEK58** [comment]
I opened a PR for this types of `listFiles`: https://github.com/pingdotgg/uploadthing/pull/430
