### ISSUE TITLE
feat: Inconsistent hostnames for files between getFileUrls() and onUploadComplete()

### ISSUE THREAD

**Issue by JEK58** [pingdotgg/uploadthing#431]
### Describe the feature you'd like to request

At the moment `getFileUrls()` returns a URL with `utfs.io` as hostname while `onUploadComplete()` returns a file URL with `uploadthing.com` as hostname.

### Describe the solution you'd like to see

Consistent hostnames throughout the service.

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

**Comment by markflorkowski** [comment]
Can you confirm which version of the uploadthing packages you are using?

**Comment by juliusmarminge** [comment]
pretty sure this is fixed since a while back

**Comment by JEK58** [comment]
This is what I'm using:

```    
"@uploadthing/react": "^5.6.2",
"uploadthing": "^5.7.1",
```

I only started using UT like two or three days ago. But even if I now upload something it gives me different host names.

**Comment by juliusmarminge** [comment]
hmm i get utfs.io links in onUploadComplete:

![CleanShot 2023-10-19 at 10 36 21@2x](https://github.com/pingdotgg/uploadthing/assets/51714798/ff85c4ce-c6dc-41f8-9c5c-995558631f8c)

**Comment by JEK58** [comment]
Hm, for the moment I also only get back `utfs.io` urls. Maybe close for now, I will monitor this further:)
