### ISSUE TITLE
feat: Disable billing tab when no app is selected

### ISSUE THREAD

**Issue by kevinanielsen** [pingdotgg/uploadthing#437]
### Describe the feature you'd like to request

When an account is first created and there are no apps, the user can still press the billing tab under the account dropdown menu. This sends the user to https://uploadthing.com/dashboard/undefined/billing which is a 404 page.

### Describe the solution you'd like to see

I suggest that until the user has an app created in their profile, the billing button should be disabled, possibly with a tooltip describing why it is disabled.

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

**Comment by juliusmarminge** [comment]
Whoops - got the logic in place to handle this but missed a return 😅 

![CleanShot 2023-10-21 at 16 04 12@2x](https://github.com/pingdotgg/uploadthing/assets/51714798/3de26900-0a2f-4992-88fc-1cab5d78c01c)
