### ISSUE TITLE
Add support for "multiple: false" option when uploading files

### ISSUE THREAD

**Issue by bmaggiano** [pingdotgg/uploadthing#44]
Hey, currently, I don't see a way to limit the number of files that can be uploaded using UploadThing. Am I missing something or is there a different way to do this?

Thanks!

**Comment by markflorkowski** [comment]
No this is a good point, will add this!

**Comment by kj-1809** [comment]
Can i allow multiple file uploads ? In the current version ?

**Comment by juliusmarminge** [comment]
This was part of the 4.0.0 release a while back.
