### ISSUE TITLE
[bug]: Express adapter broken. Dynamic require of "path" is not supported.

### ISSUE THREAD

**Issue by decipher-cs** [pingdotgg/uploadthing#443]
### Provide environment information

```bash
System:
    OS: Linux 6.5 Fedora Linux 38 (KDE Plasma)
    Memory: 1.27 GB / 5.65 GB
    Container: Yes
    Shell: 5.2.15 - /bin/bash
  Binaries:
    Node: 18.17.1 - ~/.nvm/versions/node/v18.17.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.17.1/bin/yarn
    npm: 9.6.7 - ~/.nvm/versions/node/v18.17.1/bin/npm
    pnpm: 8.9.2 - ~/.nvm/versions/node/v18.17.1/bin/pnpm
  npmPackages:
    uploadthing: ^5.7.2 => 5.7.2
```

### Describe the bug

Followed the express adapter docs to spec. Still got an error in my node app.
```
file:///home/person/uploadthing-node-example/node_modules/uploadthing/dist/chunk-T2XS
27LC.mjs:12
  throw new Error('Dynamic require of "' + x + '" is not supported');

Error: Dynamic require of "path" is not supported

```

### Link to reproduction

https://stackblitz.com/edit/stackblitz-starters-hbqrbs?file=index.js

### To reproduce

- create a node+express app.
- Exactly follow the docs for [express adapter](https://docs.uploadthing.com/backend-adapters/express)
- run the program using `node index.js`

### Additional information

Here's what `index.js` looks like.
```js
import { createUploadthingExpressHandler } from 'uploadthing/express'
import dotenv from 'dotenv'
import express from 'express'

dotenv.config()
const app = express()

const f = createUploadthing()

export const uploadRouter = {
    videoAndImage: f({
        image: {
            maxFileSize: '4MB',
            maxFileCount: 4,
        },
        video: {
            maxFileSize: '16MB',
        },
    }).onUploadComplete(data => {
        console.log('upload completed', data)
    }),
}

app.use(
    '/api/uploadthing',
    createUploadthingExpressHandler({
        router: uploadRouter,
    })
)

app.listen(process.env.PORT, () => console.log('listining on', process.env.PORT))

```

`package.json`
```json
{
  "type": "module",
  "name": "uploadthing-node-example",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "dependencies": {
    "express": "^4.18.2",
    "uploadthing": "^5.7.2",
    "zod": "^3.22.4"
  },
  "devDependencies": {
    "dotenv": "^16.3.1"
  }
}
```

### 👨‍👧‍👦 Contributing

- [X] I agree to follow this project's Code of Conduct
- [X] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

**Comment by juliusmarminge** [comment]
Probably not UT related, but some node thing... Works if you run it with Bun for example: https://github.com/juliusmarminge/express-ut

**Comment by markflorkowski** [comment]
Can confirm that I get the same error when running this code locallty, strangely, the [example in this repo](https://github.com/pingdotgg/uploadthing/blob/main/examples/backend-adapters/server/src/express.ts) works just fine.

**Comment by Ashutoshbind15** [comment]
Same error while using the express adapter here as well.

**Comment by Mr0Bread** [comment]
On it
