### ISSUE TITLE
feat: add a request headers object in the uploadFiles that we get from generateReactHelpers 

### ISSUE THREAD

**Issue by alaminShaheen** [pingdotgg/uploadthing#444]
### Describe the feature you'd like to request

Currently we can only set a URL in the 2nd parameter of uploadFiles which we get from generateReactHelpers in this way:

```
// Note: this is IMPORTED FROM YOUR CODEBASE using the `generateReactHelpers` function
import { uploadFiles } from "~/utils/uploadthing";

const res = await uploadFiles({
    files,
    endpoint: "imageUploader",
  }, {url: "https://some-external-url"});

```
It would be amazing if we could add request headers as well.

### Describe the solution you'd like to see

```
import { uploadFiles } from "~/utils/uploadthing";

const res = await uploadFiles({
    files,
    endpoint: "imageUploader",
  }, {
      url: "https://some-external-url", 
      headers: {
           authorization: .....
     }
});
```
Instead of just URL, it would be nice to be able to add custom request headers as well.

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

**Comment by juliusmarminge** [comment]
What's the usecase?

**Comment by markflorkowski** [comment]
Closing for now without a clear use case. Feel free to reopen with an explanation of what you would use this feature for.

**Comment by GaetanoMondelli** [comment]
It seems obvious from the example it is for authorization purposes

```
      headers: {
           authorization: .....
     }
```
