### ISSUE TITLE
Issue with the file delete button in dashboard

### ISSUE THREAD

**Issue by jaredthecomputerguy** [pingdotgg/uploadthing#46]
I went to delete an image I uploaded using the button on the right, but nothing happened on click even after refreshing the page.

If I select the checkbox and delete using the Delete Selected everything still seems to work however.

Here's a screen shot of the console error, my network tab didn't show a request when I clicked either. I'm using Firefox if that's helpful.

![uploadthing](https://github.com/pingdotgg/uploadthing/assets/109820632/b6d2297c-a25f-4ea8-9e66-d100ca5b909a)

**Comment by markflorkowski** [comment]
Should be fixed now!
