### ISSUE TITLE
After updating to next 14.0.2 with uploadthing 6.0, UploadThing seems to be broken

### ISSUE THREAD

**Issue by TreNgheDiCode** [pingdotgg/uploadthing#468]
![image](https://github.com/pingdotgg/uploadthing/assets/88233797/9260a1ee-85aa-43f1-8f91-a7536199e1c8)
[packages-json.txt](https://github.com/pingdotgg/uploadthing/files/13361079/packages-json.txt)
![image](https://github.com/pingdotgg/uploadthing/assets/88233797/2a333efe-c710-4451-8680-06b732ba5d75)

**Comment by juliusmarminge** [comment]
Gonna need some more info than that, do you have a repro?

**Comment by TreNgheDiCode** [comment]
I have, but currently it is private show forgive me for not sharing that, some more information:  When I do update packages, the newer version of my package send UploadThing to error. (currently I keeping at the old version left side and its working very well)
![image](https://github.com/pingdotgg/uploadthing/assets/88233797/cde15c8e-56eb-438b-84e8-faccdf99133b)

**Comment by greyyT** [comment]
I am also experiencing the same issue. When I click the upload button, it does upload to uploadthing Files but it returns an error as the author of this issue shows.

**Comment by juliusmarminge** [comment]
Ok was able to repro in our minimal example, will have a fix up momentarily

**Comment by juliusmarminge** [comment]
if you wanna fix in the interim make sure to just return `null` or `{}` from the onUploadComplete callback in your file router
