### ISSUE TITLE
[bug]: installing with bun causes issue where "INTERNAL_DO_NOT_USE__fatalClientError" is not an import from uploadthing/client

### ISSUE THREAD

**Issue by GWSzeto** [pingdotgg/uploadthing#473]
### Provide environment information

```bash
System:
    OS: Linux 6.5 Pop!_OS 22.04 LTS
    CPU: (12) x64 AMD Ryzen 5 5600G with Radeon Graphics
    Memory: 4.06 GB / 14.98 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 18.18.2 - ~/.nvm/versions/node/v18.18.2/bin/node
    npm: 9.8.1 - ~/.nvm/versions/node/v18.18.2/bin/npm
    bun: 1.0.11 - ~/.bun/bin/bun
  Browsers:
    Brave Browser: 119.1.60.114
    Chrome: 119.0.6045.123
  npmPackages:
    @uploadthing/react: latest => 6.0.0 
    typescript: ^5.1.6 => 5.2.2 
    uploadthing: latest => 6.0.1
```

### Describe the bug

updated the uploadthing package from 5.7.4 to 6.0.0 using bun. Doing so resulted in the error mentioned in the title.

Afterwards, clearing node_modules and bun.lockb and installing with npm resolved this issue

### Link to reproduction

https://docs.uploadthing.com/getting-started/appdir

### To reproduce

Upgrade to the latest version of uploadthing using bun

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Jarred-Sumner** [comment]
is this a bug in bun? it feels like it might be

**Comment by sgalanb** [comment]
Got this error after updating from v6.4.1 to v6.5.2 (all with npm). Fixed by deleting node_modules and package-lock.json.

**Comment by markflorkowski** [comment]
Unable to repro this on latest version. Judging from @sgalanb's comment, it seems like this was likely an issue with cached dependencies.

Closing for now, feel free to reopen if you encounter this issue again, and have repro steps to share.
