### ISSUE TITLE
[bug]: Issue with Package in Production Environment

### ISSUE THREAD

**Issue by realzam** [pingdotgg/uploadthing#474]
### Provide environment information

```bash
System:
    OS: Linux 5.10 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (6) x64 Intel(R) Xeon(R) CPU @ 2.20GHz
    Memory: 9.80 GB / 13.66 GB
    Container: Yes
    Shell: 5.1.4 - /bin/bash
  Binaries:
    Node: 20.8.1 - /usr/bin/node
    npm: 10.2.3 - /usr/bin/npm
    pnpm: 8.9.0 - ~/.local/share/pnpm/pnpm
  npmPackages:
    @uploadthing/react: ^6.0.0 => 6.0.0 
    typescript: ^5.2.2 => 5.2.2 
    uploadthing: ^6.0.1 => 6.0.1
```

### Describe the bug

While the package works seamlessly in development mode, allowing successful file uploads with the associated onUploadComplete callback execution, the same functionality fails in production mode.

In the production environment, the package successfully uploads the file; however, the onUploadComplete callback does not execute as expected. Additionally, the request seems to linger in a pending state without progressing further.

![image](https://github.com/pingdotgg/uploadthing/assets/49417931/055cff3b-68fc-4b2e-9cf4-672aa913fffb)

### Link to reproduction

https://docs.uploadthing.com/getting-started/appdir

### To reproduce

Excecute in Production

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by markflorkowski** [comment]
Is this a production build on your local machine or is it deployed to Vercel/similar?

**Comment by realzam** [comment]
> Is this a production build on your local machine or is it deployed to Vercel/similar?
In Both, local machine and vercel

**Comment by markflorkowski** [comment]
It will never work locally unless you use something like ngrok, and manually specify the url when generating the hook/components. Otherwise, there is no way for our infra to call back to your server to let it know the upload finished. In dev it works because we simulate this callback for you with polling. 

Deployed on Vercel though it definitely should work.... Are you on discord? If so, mind DMing me (markr) the appId so I can check the logs?

**Comment by markflorkowski** [comment]
latest release should resolve this. https://github.com/pingdotgg/uploadthing/releases
