### ISSUE TITLE
apply the encodeURIComponent(file.name) when not english?  

### ISSUE THREAD

**Issue by tendertree** [pingdotgg/uploadthing#494]
### Describe the feature you'd like to request

I found when I try to upload file which is not the english name make fail 
and searching for a while . I think only solution is change file name before I upload or before sending 

so I try to apply 

`the encodeURIComponent(file.name);`

something but fail 

I try to add this code inside of input() before the middleware but not work 

is therer a way to handle not engilsh file name can use too? 

### Describe the solution you'd like to see

people can upload their file regardless their file name language 

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

**Comment by juliusmarminge** [comment]
Can you give an example of a filename that fails? Swedish åäö works just fine and we've tested german as well. I even think @markflorkowski tried chinese file names in the past and our key handles all of them just fine, here's an example of an upload with swedish åäö in filename:

https://github.com/pingdotgg/uploadthing/assets/51714798/9e2f1f56-b926-456d-a36c-ff805db0a51c

**Comment by juliusmarminge** [comment]
will look into this, i can repro even on swedish characters now which i know have worked in the past...
