### ISSUE TITLE
feat: Allow option to enforce a name for the uploaded file

### ISSUE THREAD

**Issue by flavienbonvin** [pingdotgg/uploadthing#495]
### Describe the feature you'd like to request

There are cases where having a predictable URL is important (image generated in an email, for example). The current solution doesn't allow enforcing URLs (a random UID is used), making the solution not suitable for those aforementioned use cases.

### Describe the solution you'd like to see

Adding an option in the `onBeforeUploadBegin` callback function could be an option. Instead of returning a list of files, the method could accept either a list of files or a list of files and options.

Currently, the method signature is as follows: `(files: File[]) => File[]` instead it could become `(files: File[]) => File[] | { files: File[]; options: {keepName: boolean}}`

On the server, the option would mean that URLs would be simpler and look something like this: `https://uploadthing.com/${secret}/${fileName}`. 

The `secret` in the URL being a secret identifier generated in the uploadthing dashboard to ensure that it's unique across all users.

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

**Comment by juliusmarminge** [comment]
filenames aren't very url friendly which is why we hash them as part of the key generation
