### ISSUE TITLE
[bug]: 

### ISSUE THREAD

**Issue by jonathan-medeiros** [pingdotgg/uploadthing#498]
### Provide environment information

```bash
System:
    OS: macOS 14.1.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 676.30 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.17.0 - ~/.nvm/versions/node/v18.17.0/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - ~/Projetos/14- AI ChatGpt/prepare2sell/node_modules/.bin/npm
    Watchman: 2023.06.12.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 119.0.6045.199
    Safari: 17.1
  npmPackages:
    @uploadthing/react: ^6.0.2 => 6.0.2 
    typescript: 5.2.2 => 5.2.2 
    uploadthing: ^6.0.3 => 6.0.3
```

### Describe the bug

When my application try to upload a file that has accentuation (example: Resumé.pdf), I got a s3Error: TypeError: Failed to execute 'setRequestHeader' on 'XMLHttpRequest': String contains non ISO-8859-1 code point.

In the version ^5.6.1 this situation was working.

### Link to reproduction

https://docs.uploadthing.com/getting-started/pagedir

### To reproduce

Just try to upload a file with accentuation, example: Resumé.pdf

You can use the example provided by: https://docs.uploadthing.com/getting-started/pagedir

<img width="1506" alt="image" src="https://github.com/pingdotgg/uploadthing/assets/50887873/390dccc1-349d-48de-95b8-7799de727850">

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by juliusmarminge** [comment]
Duplicate #494
