### ISSUE TITLE
[bug]: (Next.js 14)  maxFileSize default or any value in input is not restricting larger files uploading. Larger files than specified can be uploaded

### ISSUE THREAD

**Issue by chavus** [pingdotgg/uploadthing#504]
### Provide environment information

```bash
next@14.0.1
uploadthing@6.0.3
@uploadthing/react@6.0.2
tailwindcss@3.3.3
react@18.2.0
```

### Describe the bug

Files larger than the size specified on maxFileSize  key/config in the Input object can be uploaded. There is no error thrown. Even the default value, 4 MB for an image, has no affect.

### Link to reproduction

https://stackblitz.com/github/pingdotgg/uploadthing/tree/main/examples/minimal-appdir

### To reproduce

Can be replicated following [Getting Started steps for Next/js (app/)](https://docs.uploadthing.com/getting-started/appdir) or also using reproduction template, by just uploading a larger image/file than specified in the  maxFileSize:

0.- Install the packages and Add env variables
`npm install uploadthing @uploadthing/react`
1. Create File Route:
```
import { createUploadthing, type FileRouter } from "uploadthing/next";
 
const uploader = createUploadthing();
  
export const ourFileRouter = {

    imageUploaderRep: uploader(['image'])   // Also tried with ->  image: { maxFileSize: "1MB" } 
    .onUploadComplete(async ({metadata, file })=>{
      console.log('Upload complete: ', file.url)
      return {fileUrl: file.url}
  })

} satisfies FileRouter;
 
export type OurFileRouter = typeof ourFileRouter;

```
2. CreateNext.js API route using the FileRouter

```
import { createNextRouteHandler } from "uploadthing/next";
 
import { ourFileRouter } from "./core";
 
// Export routes for Next App Router
export const { GET, POST } = createNextRouteHandler({
  router: ourFileRouter,
});
```
[3. Add UploadThing's Styles](https://docs.uploadthing.com/getting-started/appdir#add-uploadthings-styles)
[4. Create The UploadThing Component](https://docs.uploadthing.com/getting-started/appdir#create-the-uploadthing-components-recommended)
[5. Mount UploadButton](https://docs.uploadthing.com/getting-started/appdir#mount-a-button-and-upload)
[6. UploadThing SSR Plugin](https://docs.uploadthing.com/getting-started/appdir#optional-uploadthing-ssr-plugin)

When uploading file larger than specified or default, for example, 5 MB file, server log shows:
![image](https://github.com/pingdotgg/uploadthing/assets/30852571/3116a6e9-62e8-45f8-b966-2fd58dc864ff)

And eventually image is uploaded to Files and displayed in the dashboard:

![image](https://github.com/pingdotgg/uploadthing/assets/30852571/e043d9eb-6113-4cc8-970c-9c97e56d1729)

### Additional information

File used for testing: (5MB) https://sample-videos.com/img/Sample-jpg-image-5mb.jpg

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by markflorkowski** [comment]
Looking into this. Looks liek a bug may have been introduced with multipart uploads

**Comment by juliusmarminge** [comment]
Fixed 👍🏼
