### ISSUE TITLE
[bug]: File Upload Failure if the file name has the Character "｜" (Character Code 65372)

### ISSUE THREAD

**Issue by realzam** [pingdotgg/uploadthing#505]
### Provide environment information

```bash
System:
    OS: Linux 5.10 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (6) x64 Intel(R) Xeon(R) CPU @ 2.20GHz
    Memory: 11.22 GB / 13.66 GB
    Container: Yes
    Shell: 5.1.4 - /bin/bash
  Binaries:
    Node: 20.8.1 - /usr/bin/node
    npm: 10.2.3 - /usr/bin/npm
    pnpm: 8.9.0 - ~/.local/share/pnpm/pnpm
  npmPackages:
    @uploadthing/react: ^6.0.2 => 6.0.2 
    typescript: ^5.3.2 => 5.3.2 
    uploadthing: ^6.0.3 => 6.0.3
```

### Describe the bug

When attempting to upload a file whose name contains the character "｜" (Character Code 65372), the upload process fails or becomes stuck in the uploading status. This issue occurs whether using the API or attempting to upload directly from the dashboard on the official site.

### Link to reproduction

https://uploadthing.com/dashboard

### To reproduce

Steps to Reproduce:
Attempt to upload a file with the character "｜" in its name.
Observe that the upload fails or gets stuck during the uploading process.

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by markflorkowski** [comment]
Seems likely this is the same issue as #494 cc @juliusmarminge

**Comment by markflorkowski** [comment]
Will be resolved in next release.
