### ISSUE TITLE
docs: Contribution Guide

### ISSUE THREAD

**Issue by tlarnold10** [pingdotgg/uploadthing#506]
### Area of Improvement

Would be great if there were a contribution guide of some kind. Not sure if that is needed at this point, but it might get more people interested in contributing as well. Just a through, and I would be open to assisting if you need it.

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR implementing the suggested changes!

**Comment by markflorkowski** [comment]
Do you have any examples of questions which a contribution guide might address? Or potentially some examples of particularly good contribution guides you have come across in other projects?
