### ISSUE TITLE
feat: Better Support for Environment Configuration in Cloudflare Workers

### ISSUE THREAD

**Issue by kristiankauffeld** [pingdotgg/uploadthing#515]
### Describe the feature you'd like to request

Cloudflare Workers runtime doesn't natively support the Node.js global process object, even in nodejs_compat mode. The lack of this support currently results in "ReferenceError: process is not defined" errors when attempting to use Uploadthing in a Cloudflare Worker environment.

### Describe the solution you'd like to see

Pass environment variables (maybe developer mode flags?) to the library's initialization.

Here is a link to a related discussion around Prisma's adaptation to this model: 
https://community.cloudflare.com/t/how-to-access-environment-variables-from-libraries/480041

### Additional information

@juliusmarminge have been very helpful with troubleshooting on discord!

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

**Comment by juliusmarminge** [comment]
There is a canary version in #514 that lets you pass isDev flag, but I just ran into a new issue once i no longer got the process is not defined error :///

**Comment by kristiankauffeld** [comment]
@juliusmarminge so your changes in #514 solves the multiple retry attempts:

![image](https://github.com/pingdotgg/uploadthing/assets/43569402/06dc1b4c-839b-4351-bbc3-3036cee72045)

**Comment by kristiankauffeld** [comment]
hi @julius, I have downloaded the UT repository and used the debugger in VS-code to troubleshoot further. 
At this execution point: 

https://github.com/pingdotgg/uploadthing/blob/ea0f3c96f5db2fa945592d5efc06bf84811c5525/packages/uploadthing/src/internal/handler.ts#L239-L242 

I get the following error:
"Your worker created multiple branches of a single stream (for instance, by calling response.clone() or request.clone()) but did not read the body of both branches. This is wasteful, as it forces the system to buffer the entire stream of data in memory, rather than streaming it through. This may cause your worker to be unexpectedly terminated for going over the memory limit. If you only meant to copy the request or response headers and metadata (e.g. in order to be able to modify them), use the appropriate constructors instead (for instance, new Response(response.body, response), new Request(request), etc)."

**Comment by juliusmarminge** [comment]
Yea we clone here: https://github.com/pingdotgg/uploadthing/blob/main/packages/shared/src/utils.ts#L231
