### ISSUE TITLE
satisfies keyword not working in server/uploadthing.ts

### ISSUE THREAD

**Issue by michelsafi** [pingdotgg/uploadthing#53]
i get the following error: 

',' expected

**Comment by ericwaetke** [comment]
what did you do to fix this? I've got the same error.

**Comment by ericwaetke** [comment]
Huh, tried the same thing, but I still get the error
<img width="743" alt="Bildschirmfoto 2023-05-22 um 19 07 47" src="https://github.com/pingdotgg/uploadthing/assets/8260492/636815e6-6233-4b9e-86f4-ace7dd3d57c3">

**Comment by michelsafi** [comment]
Then maybe you should update your project's typescript version to 5.x.x

**Comment by ericwaetke** [comment]
Huh. Still happening with ts 5.0.4.
Maybe it's because I'm still on Nextjs 12?

I'm also trying to use the Hook, which currently has no real documentation I can find

**Comment by ericwaetke** [comment]
Alright, until I find the correct solution, it works to export the FileRouter in the server/uploadthing.ts `as FileRouter` instead of `satisfies FileRouter`
