### ISSUE TITLE
Clarification Needed: Security of Authenticated Uploads to S3 Buckets

### ISSUE THREAD

**Issue by MendyLanda** [pingdotgg/uploadthing#531]
Many users, especially those new to the platform and following recommendations from influencers like @t3dotgg, might not be aware that their uploaded files are publicly accessible. This misunderstanding is partly because there's an authentication process in uploading files, which can give a false sense of privacy.

I suggest we first update the documentation to clearly inform users about this public nature, similar to the explicit warnings AWS gives for exposed S3 buckets. It's crucial to prevent users from learning about this public access the hard way.

Also, this isn’t just about the docs. In the future, as we hopefully get support for private file uploads, it would be great to have files set to private by default. Just a thought to keep user security a priority!

**Comment by MendyLanda** [comment]
I've gone through the documentation and noticed there isn't a single mention of the public nature of file uploads. Although it might seem obvious to the average developer that files are public when there's no authentication required to view them, this isn't necessarily clear to everyone. Considering the current hype and the influx of beginners experimenting with the platform, this oversight has likely already led to unintentional exposure of sensitive data. We definitely need to address this gap in information.

**Comment by juliusmarminge** [comment]
We will release private files support in the near future which should clear this up immensely

**Comment by t3dotgg** [comment]
The nature of returning a URL makes the "public" nature of files pretty clear. This is the default for _everything other than S3_. I've yet to see a user genuinely confused by this as the default.

Addition of private files + docs around them will make this even clearer.
