### ISSUE TITLE
feat: allow async on onBeforeUploadBegin on Dropzone

### ISSUE THREAD

**Issue by Martoxdlol** [pingdotgg/uploadthing#544]
### Describe the feature you'd like to request

Currently if you use the `useUploadThing` you can pass the option `onBeforeUploadBegin` with the type `(files: File[]) => Promise<File[]> | File[]`. But if you use the `Dropzone` component the type doesn't allow to return a promise (it has the type `(files: File[]) => File[]`).

It would be nice to be able to use a promise on `onBeforeUploadBegin` using the dropzone component.

### Describe the solution you'd like to see

Change the type on `https://github.com/pingdotgg/uploadthing/blob/main/packages/react/src/types.ts` from `(files: File[]) => File[]` to `(files: File[]) => Promise<File[]> | File[]` an maybe run `setUploading(true)` before ` const files = (await opts?.onBeforeUploadBegin?.(args[0])) ?? args[0]` if it is necessary to prevent the ui from having lag.

## useUploadThing

![image](https://github.com/pingdotgg/uploadthing/assets/35405382/9052f9a9-2a70-4d7c-afcd-87fcb8fd5e43)

![image](https://github.com/pingdotgg/uploadthing/assets/35405382/108c96a1-7655-45f4-a623-5077ceeeea0b)

## Component

![image](https://github.com/pingdotgg/uploadthing/assets/35405382/6af42b73-11af-4e17-aa8d-c0cc488d1ea2)

![image](https://github.com/pingdotgg/uploadthing/assets/35405382/579fcddc-9a26-40bd-a0e4-180f6eab2d08)

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

**Comment by juliusmarminge** [comment]
Did you wanna file a PR for this @Martoxdlol?

**Comment by Martoxdlol** [comment]
Sure, I will do it.
