### ISSUE TITLE
feat: allow possibility to delete an uploaded image

### ISSUE THREAD

**Issue by Complexlity** [pingdotgg/uploadthing#546]
### Describe the feature you'd like to request

Let's say I have a route (or function) that does the following:
1. uploaded images to uploadthing
2. Upload metadata and other text content to db

Now the image upload could be successful but the other content could fail which would mean the function was not successful. It would be good to be able to revert this image upload since this file would never be accessed as saving the metadata of the file was not successful

### Describe the solution you'd like to see

`
const uploadImage = await startUpload([image!]).catch((err) => uploadError = err)

const uploadMetadata = await myDb.create({image: uploadImage[0].url}).catch(err=> uploadImage.delete()
 //reverts the image upload)
`

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

**Comment by markflorkowski** [comment]
You can already do this using the UTApi function:

https://docs.uploadthing.com/api-reference/server#deletefiles

**Comment by mendykrauss** [comment]
> You can already do this using the UTApi function:
> 
> https://docs.uploadthing.com/api-reference/server#deletefiles

Quick fix: https://docs.uploadthing.com/api-reference/ut-api#deletefiles

**Comment by Complexlity** [comment]
Thank you!. @markflorkowski let me know before. And it worked well when I used it
