### ISSUE TITLE
docs: List of supported MIME/file types.

### ISSUE THREAD

**Issue by Sturlen** [pingdotgg/uploadthing#551]
### Area of Improvement

Add a list of supported MIME/file types. Currently, MIME-types are only mentioned once in a code example:
[Server#Input](https://docs.uploadthing.com/api-reference/server#input )
```js
type MimeType = /** any web mime-type */
```

Having a list of MIME-types and an explanation of how use them could help answer a lot of "Does UploadThing support X filetype?" questions I regularly see on the Discord server.

### Link to related docs

https://docs.uploadthing.com/api-reference/server#input

### Additional information

All supported MIME-types seems to be defined in https://github.com/pingdotgg/uploadthing/blob/main/packages/mime-types/src/db.ts This could either be used a reference in the docs or linked to.

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR implementing the suggested changes!

**Comment by markflorkowski** [comment]
> Having a list of MIME-types

There are hundreds of these, so it really is not feasible to put a list that is readable anywhere. We could link to the [`db.ts`]( https://github.com/pingdotgg/uploadthing/blob/main/packages/mime-types/src/db.ts) file you pointed out, however, that isn't really helpful if you don't already know what a MIME type is. I think giving people the correct name of what they should google search if they don't know what a MIME type is already is sufficient. 

Also if someone uses a MIME type that for some reason is not in our list, we would like them to reach out and let us know so we can add it. I realize that some people will give up if they encounter this scenario, but at this time, we can't really optimize for that. 

Perhaps a sentence about MIME types being valid keys for the router, and a link to the MDN page about them (similar to what we do for (`Content-Disposition`) could be good?
