### ISSUE TITLE
docs: Generic usage docs

### ISSUE THREAD

**Issue by markomitranic** [pingdotgg/uploadthing#552]
### Area of Improvement

Uploadting docs start with:

> "Right now we're mostly just wrapping S3 with caching and callbacks"

But I don't see this reflected in the docs at all. What I see is the docs focusing exclusively on client uploads.  They keep talking about very specific things like front-end upload buttons and framework-related implementations, even Tailwind styling lol. In fact after reading them I stand confused regarding if i even need to install the npm package or not. Which API should I use if I used a simple HTTP call etc. I would like a section of the docs that focuses on a very generic, old school usage example, possibly even without any deps.

Lets have a getting started page, with a code sample, that explains how to stream a file from the disk into Uploadthing, and then echo the result (a publicly available URL, ID and metadata) - in a single script.

Then, to expand, let's have the same with a bulk upload. Only after these basics does it make sense to dive into special cases like user-facing uploads, auth, cache control, rendering and serving, styling  etc. A page like this would be useful to everyone who wishes to do anything with Uploadthing and comes from backend or S3 compatibile object storage services.

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR implementing the suggested changes!

Edit: typos and added forgotten words.

**Comment by markflorkowski** [comment]
We're working on [adding an API spec to the docs](https://github.com/pingdotgg/uploadthing/pull/555) for anyone who is interested in utilizing uploadthing without our libraries.

**Comment by markomitranic** [comment]
@markflorkowski Thank you for your response, but this is not at all what I meant. It isn't nice to close an Issue simply because you think it is answered.

Your docs focus on uploading and components. They sound like they are made with FE developers in mind only. They have literally 0% focus on actually working with files.

How do upload from disk? dunno.
Delete rename? dunno.
How do get url? dunno.
How to make it private? dunno.
Housekeeping practices? dunno.

Actually https://docs.uploadthing.com/api-reference/ut-api page is the only one that even remotely mentions actually working with files. And even with that, I've had to read the source code, in order to figure out how to do the most basic thing - upload a file.

Since I don't see anyone doing it, I guess I'll open a PR.
