### ISSUE TITLE
is this only for next js?

### ISSUE THREAD

**Issue by Anass-Lamiri** [pingdotgg/uploadthing#56]
Hey there! I'm curious to know if this tool is exclusive to Next.js or if it can be used with vanilla JavaScript in the backend with Node.js and Express. I'm currently in the learning phase and I want to strengthen my JavaScript fundamentals. I'm not yet familiar with frameworks and libraries, so I'm focusing on building a strong foundation first. Sorry if my question seems basic, but I'm still a beginner and I'm just trying to learn. Thank you!

( also great project and thank you for your effort )

**Comment by markflorkowski** [comment]
No worries, we were all beginners once! Right now we only really support Next, but we do plan to add additional framework support/make it more agnostic in the future!
