### ISSUE TITLE
[misc]: Error: Failed to alert UT of upload completion

### ISSUE THREAD

**Issue by benjaminlim00** [pingdotgg/uploadthing#560]
### I understand that this issue may be closed if it should be filed in another category

- [X] I understand

### My issue

May I please enquire what this error means?

I am currently using UT to upload audio files from my NextJS application using the uploadFiles helper. This error does not give me any clue as to what is causing the error and how I should mitigate it.

Thank you 🙏 

Edit: I meant to say NextJS instead of NestJS

**Comment by benjaminlim00** [comment]
"uploadthing": "^6.1.1",
"@uploadthing/react": "^6.1.0",

I am using the latest version of uploadthing

**Comment by markflorkowski** [comment]
That error occurs if the fetch to the UT server to confirm that the multipart is completed fails. Typically this is due to invalid input. Can you share a file key of a file where you saw this error?

**Comment by markflorkowski** [comment]
Are you still encountering this issue?

**Comment by markflorkowski** [comment]
Closing for now. If you are still encountering this issue, please feel free to reopen with additional details.

**Comment by benjaminlim00** [comment]
Sorry for the late response. I have moved on from this issue
