### ISSUE TITLE
[misc]: Uploadthing callback error when using 'withAuth' next-auth middleware

### ISSUE THREAD

**Issue by dwalker93** [pingdotgg/uploadthing#561]
### I understand that this issue may be closed if it should be filed in another category

- [X] I understand

### My issue

Without middleware no errors in console. But files successfully uploading to uploadthing With or without next-auth middleware. Only callback issue.

Without next-auth middleware
![image](https://github.com/pingdotgg/uploadthing/assets/65861708/d617a966-c84c-4535-bf2b-7f2571c4d451)

With next-auth middleware
![image](https://github.com/pingdotgg/uploadthing/assets/65861708/59163d42-1548-4132-a267-e07b4fc23ef3)

[Github repo](https://github.com/dwalker93/uploadthing-test)

**Comment by markflorkowski** [comment]
https://docs.uploadthing.com/faq#when-i-upload-files-i-get-the-error-failed-to-simulate-callback-for-file-is-your-webhook-configured-correctly

Make sure you are not requiring auth on the `/api/uploadthing` route

**Comment by AnujSsStw** [comment]
probably add matcher
