### ISSUE TITLE
[misc]: unable to fetch 

### ISSUE THREAD

**Issue by Abhijeet-Tathod** [pingdotgg/uploadthing#563]
### I understand that this issue may be closed if it should be filed in another category

- [X] I understand

### My issue

1. Well  i can upload doc normal 
2. But at time of fetch 403 Error 
3. Also there was no problem fetching 2 days ago all works fine

**** 

Error msg = 

```
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>GEQBVABNESRZWR9Q</RequestId>
<HostId>Nah431u6mXXvTKAIX/sQMa/d2wM4qR9RlivmxWTzKlaXqhpIVzBH+2jh3GBQYMcBlwtkW8nt+Xxzgl9XShFqNw==</HostId>
</Error>
```

Well I know its Auth error but why suddenly not before

**Comment by markflorkowski** [comment]
Are you seeing this with all files, or just specific ones? Can you share the file key of a file that is having this issue?

**Comment by Abhijeet-Tathod** [comment]
```
Request URL:
https://uploadthing-prod.s3.us-west-2.amazonaws.com/a62396f0-838e-4a30-bce9-daab368a4992-1uy2qb.pdf

```
```
  const response = await fetch(
      `https://uploadthing-prod.s3.us-west-2.amazonaws.com/${file.key}`
    )

```

File Type = PDF 

File is Accessible for Website (Link = https://utfs.io/f/a62396f0-838e-4a30-bce9-daab368a4992-1uy2qb.pdf)

![Screenshot 2024-01-20 103243](https://github.com/pingdotgg/uploadthing/assets/116875447/af411bd6-b143-45f5-a601-fa284901e420)

I think i need to add  some header or token to get request during fetch Probably

**Comment by markflorkowski** [comment]
> https://uploadthing-prod.s3.us-west-2.amazonaws.com/${file.key}

This is not a valid url. 

Use ``` `https:/utfs.io/${file.key}` ```

**Comment by Abhijeet-Tathod** [comment]
**Thank you for your time and efforts brother**
