### ISSUE TITLE
docs: Next.js (app/) UploadThingError is not present in installed packages

### ISSUE THREAD

**Issue by WolfgangVing** [pingdotgg/uploadthing#589]
### Area of Improvement

I don't know if UploadThingError should be inside of any of the installed packages that the [documentation](url) instructs by the line
`npm install uploadthing @uploadthing/react` or not. Also there are somethings that leads to somewhat ambiguity.
 
1. Though UploadThingError is used, there is no line indicating from where you imported.
2. In the Next.js (pages/) docs it's using the Error from Node itself, so you can't really try to guess.
3. In the [Error Handling](https://docs.uploadthing.com/errors) section there is a line for importing the function  `import { UploadThingError } from "uploadthing/server";` But there is not UploadThingError inside, at least it's not showing in TS.

![image](https://github.com/pingdotgg/uploadthing/assets/44654440/d71b0004-acbf-4866-8780-926be62d5b12)

### Link to related docs

https://docs.uploadthing.com/getting-started/appdir#creating-your-first-fileroute

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR implementing the suggested changes!

**Comment by petter** [comment]
`UploadThingError` was added to the "Getting Started" example in #582, which is the PR that enables passing error messages to users through `UploadThingError`. The "Error Handling" example, which also uses app dir, was also updated in the same PR, so the missing import should likely be `import { UploadThingError } from "uploadthing/server";`.

I just updated `uploadthing` to v6.3.3, and `UploadThingError` is present (showing in TS as well) in `"uploadthing/server"` in that version at least.
