### ISSUE TITLE
[bug]: express adapter breaks when using `body-parser`

### ISSUE THREAD

**Issue by juliusmarminge** [pingdotgg/uploadthing#590]
### Provide environment information

```bash
System:
    OS: macOS 14.2.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 106.48 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.11.0 - ~/Library/Caches/fnm_multishells/30733_1706613602105/bin/node
    npm: 10.2.4 - ~/Library/Caches/fnm_multishells/30733_1706613602105/bin/npm
    pnpm: 8.14.1 - ~/Library/Caches/fnm_multishells/30733_1706613602105/bin/pnpm
    bun: 1.0.25 - ~/.bun/bin/bun
  Browsers:
    Chrome: 121.0.6167.85
    Safari: 17.2.1
  npmPackages:
    typescript: ^5.3.3 => 5.3.3
```

### Describe the bug

this breaks:

![CleanShot 2024-01-30 at 09 32 33@2x](https://github.com/pingdotgg/uploadthing/assets/51714798/4c68ff73-163c-4b86-9714-1033c97ad463)

move the bodyparser middleware below the uploadthing route handler to fix it. the new logs helps narrow down the issue but we can probably make this scenario work

### Link to reproduction

👇👇👇

### To reproduce

see #586 

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by juliusmarminge** [comment]
if anyone using express would like to take a deeper dive feel free - I probably wont spend time on this for a while unless it becomes a higher priority issue

**Comment by MustafaEminn** [comment]
The issue cannot be reproduced anymore

**Comment by juliusmarminge** [comment]
I cannot reproduce it either, guess we fixed it somehow wihtout knowing :)
