### ISSUE TITLE
[Bug]: Unable to email addresses to account

### ISSUE THREAD

**Issue by Unisane123** [pingdotgg/uploadthing#595]
### What happened?

I am trying to add some of my developers by email and when I do it does not add their email to the email addresses list. This is what I see
![uploadthingissue](https://github.com/pingdotgg/uploadthing/assets/144530230/f371c636-4d3b-4651-a5e7-fcc592469e91)

### What did you expect to happen?

For it to be able to send an email for a dev to verify their email.

### Version

Dashboard

### Reproduction Steps

I am logging in. Pressing the top right user icon > Profile > Add Email Address > Type in an email address for one of my devs > Add email > then that is the console log
No coding. Just trying to add devs so they can check our uploads

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by markflorkowski** [comment]
That setting is to add additional email addresses to your account, not to invite them to access your org. 

To invite users to your org, you will need to be on a paid plan, and invite them from the org settings on the dashboard:

https://github.com/pingdotgg/uploadthing/assets/11494384/cc8b9e13-847a-4b1e-bad1-185e42216534


That being said, You definitely shouldn't be getting that error there, I will look into that.

**Comment by markflorkowski** [comment]
Closing for now. Feel free to reopen with more details.
