### ISSUE TITLE
docs: Uploadthing with React

### ISSUE THREAD

**Issue by void-hr** [pingdotgg/uploadthing#599]
### Area of Improvement

It would be great if there will be React + uploadthing walk-through, similar to Nextjs inside docs. I have gone through docs and still not sure we can use uploadthing with React, do add begineer friendly docs regarding the same.

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR implementing the suggested changes!

**Comment by markflorkowski** [comment]
This is something we have discussed, just have not yet had a chance to get to it. If you take a look at the `examples/backend adapters` I believe there is an example of a plain react app with an express backend
