### ISSUE TITLE
feat: Free darkmode

### ISSUE THREAD

**Issue by bdsqqq** [pingdotgg/uploadthing#606]
### Describe the feature you'd like to request

come on

### Describe the solution you'd like to see

just stop using server components lol

### Additional information

don't take me down ok? Someone is doing this PR, now you can link to here and say it's duplicate

### 👨‍👧‍👦 Contributing

- [x] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

**Comment by RealPacket** [comment]
don't close it

**Comment by t3dotgg** [comment]
It already is free (if you're already paying for the 100gb tier or higher) 😄

**Comment by RealPacket** [comment]
> @t3dotgg Hey why you closed this? I will unsubscribe from your channel (just joking bro).
> 
> but for anyone who wants a dark mode in any website [just use this one](https://chromewebstore.google.com/detail/dark-reader/eimadpbcbfnmbkopoojfekhnkhdbieeh)

Could've just linked to <https://darkreader.org>, not everyone uses Chrome (I use Firefox btw).

**Comment by ZeyadMoustafaKamal** [comment]
> > @t3dotgg Hey why you closed this? I will unsubscribe from your channel (just joking bro).
> > but for anyone who wants a dark mode in any website [just use this one](https://chromewebstore.google.com/detail/dark-reader/eimadpbcbfnmbkopoojfekhnkhdbieeh)
> 
> Could've just linked to https://darkreader.org, not everyone uses Chrome (I use Firefox btw).

Umm I didn't know that they have a website so thanks for giving me thier website
