### ISSUE TITLE
[bug]: Changing file type causes hydration error in Next.js

### ISSUE THREAD

**Issue by lawrencecchen** [pingdotgg/uploadthing#608]
### Provide environment information

```bash
System:
    OS: macOS 14.3
    CPU: (10) arm64 Apple M1 Max
    Memory: 4.08 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.5.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 10.2.4 - /opt/homebrew/bin/npm
    pnpm: 8.10.5 - ~/Library/pnpm/pnpm
    bun: 1.0.26 - ~/.bun/bin/bun
  Browsers:
    Brave Browser: 108.1.46.144
    Chrome Canary: 123.0.6283.0
    Safari: 17.3
  npmPackages:
    @uploadthing/react: ^6.2.2 => 6.2.2 
    typescript: ^5 => 5.3.3 
    uploadthing: ^6.3.3 => 6.3.3
```

### Describe the bug

Changing file type causes hydration error in Next.js. Killing and re-running the dev server fixes things, but this isn't ideal.

Toggle between the different `publicUploader`s while the dev server is running.

```ts
import { createUploadthing, type FileRouter } from "uploadthing/next";

const f = createUploadthing();

export const ourFileRouter = {
  // publicUploader: f(["image", "blob"])
  publicUploader: f(["blob"])
    // publicUploader: f(["image", "video", "audio", "blob"])
    // publicUploader: f(["image", "video", "audio", "blob"])
    // publicUploader: f(["image", "video", "audio", "blob", "pdf", "text"])
    .middleware(() => {
      return {};
    })
    .onUploadComplete(() => {
      return {};
    }),
} satisfies FileRouter;

export type OurFileRouter = typeof ourFileRouter;
```

https://github.com/pingdotgg/uploadthing/assets/54008264/203b34e3-b540-4ed7-93bf-6acca3e3ac2e

### Link to reproduction

https://github.com/lawrencecchen/uploadthing-multi-content-type-repro

### To reproduce

1. Run dev server
2. Open localhost
3. Change file type
4. Go back to localhost

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by juliusmarminge** [comment]
This is due to the SSR plugin where a global is set on the server once and since layouts never re-run that global wont be updated...

Curious how we could fix it, I've seen it since the start but never got a report of anyone finding it annoying until now...

**Comment by Kinfe123** [comment]
Does configuring the SWR or any other plugins there for ssr there (i have not checked it out) wont help ?
