### ISSUE TITLE
[Bug]: Selecting an element in the Files Tab selects multiple elements

### ISSUE THREAD

**Issue by XavierFabregat** [pingdotgg/uploadthing#610]
### What happened?

When selecting image files in my File Tab on the dashboard, them same list item in the next page of files would also be selected.

https://github.com/pingdotgg/uploadthing/assets/101363604/9c9d2f46-98e8-4247-bab4-3f50d86b5c90

### What did you expect to happen?

For only the selected file to be marked as selected.

### Version

6.3.3

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by juliusmarminge** [comment]
already have a PR pending for this - should be merged shortly
