### ISSUE TITLE
[bug]: UTFiles does not exist

### ISSUE THREAD

**Issue by theNamellessOne** [pingdotgg/uploadthing#613]
### Provide environment information

```bash
System:
    OS: Linux 6.2 KDE neon 5.27 5.27
    CPU: (8) x64 AMD Ryzen 5 3350G with Radeon Vega Graphics
    Memory: 6.65 GB / 13.57 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 21.5.0 - ~/.nvm/versions/node/v21.5.0/bin/node
    npm: 10.2.4 - ~/.nvm/versions/node/v21.5.0/bin/npm
  npmPackages:
    @uploadthing/react: 6.2.2 => 6.2.2 
    typescript: ^5.3.3 => 5.3.3 
    uploadthing: 6.3.3 => 6.3.3
```

### Describe the bug

based off of the documentation i should be able to add customId to uploaded file using UTFiles like this

```
    .middleware(({ req, files }) => {
      // Check some condition based on the incoming requrest
      req;
      //^?
      // if (!req.headers.get("x-some-header")) {
      //   throw new Error("x-some-header is required");
      // }

      // (Optional) Label your files with a custom identifier
      const filesWithMyIds = files.map((file, idx) => ({
        ...file,
        customId: `${idx}-${randomUUID()}`,
      }));

      // Return some metadata to be stored with the file
      return { foo: "bar" as const, [UTFiles]: filesWithMyIds };
    })
```

but when trying to import UTFiles i get an error
```
//Module '"uploadthing/next"' has no exported member 'UTFiles'.(2305)
import { createUploadthing, UTFiles } from "uploadthing/next"; 
```

this even happens in provided minimal example
![image](https://github.com/pingdotgg/uploadthing/assets/145769204/88960716-5cfd-44a9-a802-a69f855487bb)

when going inside node_modules/uploadthing/dist/next.d.ts those are the only exports
![image](https://github.com/pingdotgg/uploadthing/assets/145769204/49a9eadd-6cd9-4973-8077-46ad77f896a4)

### Link to reproduction

https://stackblitz.com/github/pingdotgg/uploadthing/tree/main/examples/minimal-appdir?file=src%2Fserver%2Fuploadthing.ts

### To reproduce

no additional steps required

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by theNamellessOne** [comment]
in fact dist directory does not seem to include anything with "UTFiles"
![image](https://github.com/pingdotgg/uploadthing/assets/145769204/866b5de5-f32b-4492-98a2-035b75d9c8d8)

**Comment by juliusmarminge** [comment]
sorry it's not released yet - will be next update

**Comment by juliusmarminge** [comment]
I've added a version tag in the docs about it too. Thanks for bringing it up, we strive to always put the version things are added but forgot that here...

**Comment by januarionclx** [comment]
> I've added a version tag in the docs about it too. Thanks for bringing it up, we strive to always put the version things are added but forgot that here...

Hey! am I missing something? the docs say v6.4, I'm using 6.4.1 and I'm still getting "Attempted import error: 'UTFiles' is not exported from 'uploadthing/server' (imported as 'UTFiles')"

Assuming is not released yet, there's currently no say to attach metadata to files, right?

I'm having the need to split my files into "projects", and was planning to use customId to do so.

Appreciate the efforts beforehand, pretty cool/useful project! 👍

**Comment by juliusmarminge** [comment]
whoops looks like it's exported from everything but the server entrypoint xd

you can import it from any other framework entrypoint, it's the same thing realyl...

```ts
import { UTFiles } from "uploadthing/next";
```

will also make sure to export it from the server entrypoint

**Comment by januarionclx** [comment]
> whoops looks like it's exported from everything but the server entrypoint xd
> 
> you can import it from any other framework entrypoint, it's all the same thing just re-exported
> 
> ```ts
> import { UTFiles } from "uploadthing/next";
> ```
> 
> will also make sure to export it from the server entrypoint

Hey! thanks, that's basically what I was doing (although I was importing it from internals) but I'm still not able to edit the file's customId though, is this working already?

As shown in the image, looks like I'm editing the metadata, but is not affecting the file's customId?

![image](https://github.com/pingdotgg/uploadthing/assets/39181767/f3811b16-be49-4311-b9fb-4f73b0e66d0b)
![image](https://github.com/pingdotgg/uploadthing/assets/39181767/9c447bb7-8d5b-4455-b1f3-9790bfd64e52)

I tried manually returning a customId just to see what happens, and I managed to see the metadata in my onUploadComplete, but the file is still not affected:

![image](https://github.com/pingdotgg/uploadthing/assets/39181767/248595e5-e6b1-4205-84b7-1211c42da68b)
![image](https://github.com/pingdotgg/uploadthing/assets/39181767/2dd806bd-6689-4b18-b1ee-767e256dff07)

**Comment by juliusmarminge** [comment]
try again - seems like last deploy we changed some stuff and missed the customId for certain uploads...

**Comment by januarionclx** [comment]
> try again now - seems like last deploy we changed some stuff and missed the customId for certain uploads...

It works now, thank you so much!

I may have misunderstood the use though, I thought I could upload different images with the same customId (as customId was a metadata, and not the primary key), looks like is not the case?

I'm getting an error saying my customId already exists.

Assuming is working correctly, I'm probably better off storing slugs/keys or something in my own DB, and relationships with users, as I wouldn't be able to filter files by metadata in uploadthing anyways, right?

I was planning on using customId to assign files to specific projects.

**Comment by juliusmarminge** [comment]
That's right, customIds are unique to an app. People wanted it since they wanted their own ids and also allows you to use it sort of like a KV-store since you'll know the id before uploading as opposed to the fileKeys which are generated by us out of your control.

It looks like you'll want to store the file metadata in your db with the relation to each project.

**Comment by januarionclx** [comment]
> That's right, customIds are unique to an app. People wanted it since they wanted their own ids and also allows you to use it sort of like a KV-store since you'll know the id before uploading as opposed to the fileKeys which are generated by us out of your control.
> 
> It looks like you'll want to store the file metadata in your db with the relation to each project.

Cool! I just checked upload thing's doc today and in the roadmap looks like you have folders, perhaps that'll help too but you're right, I'll probably stick to DB's relationships now, thanks! 🙏
