### ISSUE TITLE
[misc]: Files is uploading successfully but unable to get the onComplete response in front end using node,express and uploadthing.

### ISSUE THREAD

**Issue by pixaque** [pingdotgg/uploadthing#623]
### I understand that this issue may be closed if it should be filed in another category

- [X] I understand

### My issue

Hi,

I know it's not the right way to do it. But this is what I did to fix it.

set the isDev to true.

And in node_modules/uploadthing/express/index.cjs line no 139 added this line

"content-type": "application/json"

and everything is working fine even getting message to my front end as well.

Thank you for your help.

Please help me resolve this issue so it can ran successfully anywhere.

Regards,
Asad

**Comment by juliusmarminge** [comment]
Closed as completed through Discord
