### ISSUE TITLE
[Bug]: 404 page error when accepting invite to join organization

### ISSUE THREAD

**Issue by davidjgrant** [pingdotgg/uploadthing#628]
### What happened?

- My client created an account / organization
- Invited me to join as a developer
- When I opened the link in my email, it redirected me a 404 page

![image](https://github.com/pingdotgg/uploadthing/assets/5520778/69bea803-fead-4f4a-a338-248460c7dab5)

### What did you expect to happen?

- To login
- Join organization

### Version

https://clerk.uploadthing.com/v1/tickets/accept?_clerk_js_version=4.70.0&ticket=<TICKET NUMBER>

### Reproduction Steps

- logout of existing account
- accept invite to join organization
- get 404 page

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by davidjgrant** [comment]
- (edit) solved: I needed to have already been logged in with the same GitHub email that my client invited with.
- ToDo: Allow the user to join the organization without logging in.

**Comment by markflorkowski** [comment]
Seems to be a bug with Clerk, our auth provider. I am working with them to get this sorted out. Thanks again for the report!

**Comment by markflorkowski** [comment]
This should now be resolved.

**Comment by markflorkowski** [comment]
Fix caused other issues, has been reverted, so we are back to having this problem.

**Comment by markflorkowski** [comment]
OK, should *actually* be fixed now
