### ISSUE TITLE
[bug]: "Err fetch failed" after successful file upload

### ISSUE THREAD

**Issue by brandoshizzle** [pingdotgg/uploadthing#629]
### Provide environment information

```bash
System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 AMD Ryzen 5 3600 6-Core Processor
    Memory: 11.17 GB / 31.95 GB
  Binaries:
    Node: 21.4.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD      
    npm: 10.2.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 121.0.6167.185
    Edge: Chromium (121.0.2277.128)
    Internet Explorer: 11.0.19041.3636
  npmPackages:
    @uploadthing/react: ^6.2.4 => 6.2.4
    typescript: ^5 => 5.3.3
    uploadthing: ^6.4.1 => 6.4.1
```

### Describe the bug

My application was working fine; however, after no discernable changes, it began giving me this error.
![image](https://github.com/pingdotgg/uploadthing/assets/15352578/28b816d8-519e-4d22-9e5b-3f89ec12eaac)

I click an UploadButton and select the file. It starts the upload, and the file appears in my UploadThing dashboard. However, it gives the above error and log output in my VSCode console. It does not return information about the uploaded file as expected, and does not seem to trigger the errorFormater or onUploadComplete.

The only thing I can think of that would be out of the norm is that I am using multi-tenant NextJS middleware. However, '/api/uploadthing' is a public route and I don't see any requests that would be causing this.

### Link to reproduction

Will create if more information is required

### To reproduce

Will create if more information is required.

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by markflorkowski** [comment]
So it looks like that `fetch failed` is occurring when we attempt to simulate the callback (since uploadthing cannot send a webhook to your local dev environment). 

Looking closer, the url that the UT package is trying to fetch looks a bit weird to me:

```
http://app.localhost:3000/api/uploadthing?slug=imageUploader
```

I am not sure how `http://app.localhost` would get resolved unless you have a custom entry in your HOSTS file, or something else going on. Are you setting the `config.callbackUrl` field in your `createRouteHandler()`?

**Comment by brandoshizzle** [comment]
Ah that makes sense, I haven't configured a custom callbackUrl for app.localhost (I'm using NextJS middleware to reroute /app to that subdomain). I'll give that a go soon here and report back.

**Comment by markflorkowski** [comment]
Just following up here @brandoshizzle -- any luck?

**Comment by markflorkowski** [comment]
Closing for now, feel free to reopen if you are still having issues.

**Comment by brandoshizzle** [comment]
Thanks for following up and sorry for the delay! The app subdomain was causing issues. I tried adding callbackUrl into the router config and ENV, but ultimately decided to just keep the domain routing easy for this project.

Thanks for your help and for the great product!
