### ISSUE TITLE
feat: Have the ability to pass a input prop to overwrite some of the condition

### ISSUE THREAD

**Issue by Semkoo** [pingdotgg/uploadthing#653]
### Describe the feature you'd like to request

First, this is an amazing and simple-to-use tool and I appreciate it as it helped jump-start start project that I am working on. 

But, I ran into a little problem. I only wanted to upload one file at a time, without letting people choose lots of files simultaneously by holding down the 'shift' key. So, I had to do a little trick to make it work the way I wanted.

Here's a simple example of what I did:

``` tsx
"use client";

import { useEffect } from "react";
import { UploadDropzone } from "~/utils/uploadthing";

// CustomUploadThing component with special settings
type CustomUploadThing = React.ComponentProps<typeof UploadDropzone> & {
  // Adding a custom option for one file at a time
  isMultiple?: boolean;
};

// CustomUploadThing function component
export function CustomUploadThing(props: CustomUploadThing) {
  // Using useEffect to update things when props change
  useEffect(() => {
    // Finding the input element
    const input = document.querySelector("#drop-zone input");

    // If we only want one file at a time...
    if (!props.isMultiple) {
      // Remove the 'multiple' option from the input
      input?.removeAttribute("multiple");
      // We could also change the button text here if needed
    }
  }, [props.isMultiple]);

  // Rendering our UploadDropzone component inside a div
  return (
    <div id="drop-zone">
      <UploadDropzone {...props} />
    </div>
  );
}
``` 

### Describe the solution you'd like to see

So I was hopping if there is the way we pass an inputProp into UploadDropzone so for example  

```tsx  
.... 
<UploadDropzone 
   ... 
   inputProps = {
      ....
     multiple: false 
    }
    />
....
``` 

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

**Comment by markflorkowski** [comment]
Hmm. There is also a bug here. it the endpoint only allows uploading a single file, the dropzone should not have the multiple prop on the input. The upload button component does this correctly.

**Comment by markflorkowski** [comment]
After thinking on this some more, I don't think that it makes sense to allow the override on the components. We want to promote configuring the accepted input (file types, size, quantity) on the file router, and the components will apply the equivalent restrictions "automatically".

I have a PR up now that will fix the behavior so that the filerouter config is respected by the components. 

If you have a use case where it makes sense to override from the frontend, I think it is reasonable enough for us to say that is an "advanced use case" and you should use our hooks to implement your own component.

**Comment by Semkoo** [comment]
> After thinking on this some more, I don't think that it makes sense to allow the override on the components. We want to promote configuring the accepted input (file types, size, quantity) on the file router, and the components will apply the equivalent restrictions "automatically".
> 
> I have a PR up now that will fix the behavior so that the filerouter config is respected by the components.
> 
> If you have a use case where it makes sense to override from the frontend, I think it is reasonable enough for us to say that is an "advanced use case" and you should use our hooks to implement your own component.

Hmm fair point, what about the ability to change the label text ?

Also another small quick question, I know the `onClientUploadComplete` returns an array of files would be possible to return as one if it is only one?

**Comment by markflorkowski** [comment]
> Hmm fair point, what about the ability to change the label text ?

https://docs.uploadthing.com/theming#content-customisation

> Also another small quick question, I know the onClientUploadComplete returns an array of files would be possible to return as one if it is only one?

instead of an array with one object you mean?

**Comment by juliusmarminge** [comment]
> Also another small quick question, I know the onClientUploadComplete returns an array of files would be possible to return as one if it is only one?

I believe that would be quite cumbersome to get right from a typescript perspective without a lot of gains

**Comment by Semkoo** [comment]
Ah okay I will close this since this has been solved on last merge
