### ISSUE TITLE
feat: Don't request github account email and allow unlinking it on account

### ISSUE THREAD

**Issue by Gunni** [pingdotgg/uploadthing#656]
### Describe the feature you'd like to request

I don't want you to have my github email and I want to unlink my github email from the account.

### Describe the solution you'd like to see

Don't ask for user email auth scope for github.

Or allow it to be removed by the user then just _ask_ for an email to use.

### Additional information

I use a custom email with all services.

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

**Comment by markflorkowski** [comment]
Will be looking into how we can support this. Currently does not appear possible with our auth provider, however we are working with them on a number of email-related behaviors that this could be considered part of.

**Comment by Gunni** [comment]
Still an issue.
