### ISSUE TITLE
[bug]: How Can I upload .xlsx and .docx files?

### ISSUE THREAD

**Issue by Firephoenix25** [pingdotgg/uploadthing#672]
### Provide environment information

```bash
System:
    OS: macOS 14.2.1
    CPU: (8) arm64 Apple M1
    Memory: 637.33 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.17.0 - /usr/local/bin/node
    npm: 9.6.7 - /usr/local/bin/npm
    bun: 1.0.22 - ~/.bun/bin/bun
  Browsers:
    Chrome: 122.0.6261.94
    Safari: 17.2.1
  npmPackages:
    @uploadthing/react: ^6.2.2 => 6.2.2 
    typescript: 5.3.3 => 5.3.3 
    uploadthing: ^6.3.3 => 6.3.3
```

### Describe the bug

My UploadThing works perfectly on my next js project but i don't see a way to select and upload file in "microsoft exel/ word" format....

I see in a config file that exist "text/csv" but is now enough for my clients

### Link to reproduction

https://github.com/Firephoenix25/isomorphic

### To reproduce

i don't think you need to reproduce because is not a bug i think...

fell free to ask me question about the project

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by markflorkowski** [comment]
You can use any valid mime-type as a key in your filerouter. [See here](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types) for a good resource to look them up.

**.docx :**
```
application/vnd.openxmlformats-officedocument.wordprocessingml.document
```

**.xlsx**
```
application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
```

**Comment by Firephoenix25** [comment]
thanks, helped a lot🔥

**Comment by joelrb** [comment]
Shouldn't this be one of those defaults without us adding mime types? It's a reality in business that we upload word documents, excel files, powerpoint, etc.. Thanks.
