### ISSUE TITLE
feat: Better upload button customization

### ISSUE THREAD

**Issue by ahkhanjani** [pingdotgg/uploadthing#682]
### Describe the feature you'd like to request

Currently when I set `content={{ button: "Anything" }}`, the loading percentage text will not show. Also the colored progress bar covers the text.

![Screenshot 2024-03-07 210550](https://github.com/pingdotgg/uploadthing/assets/72540492/b329c0db-9115-4a09-bc49-420179991d08)
This is supposed to be "Custom text".

Since the content field is not meant for customizing default values and completely replaces the button content, I think we need that alternative too. Because in my case, except for the default text, everything else is fine.

Also for allowed content specifically, I would like to have access to the configuration in case I want to change it. I'll provide an example in the next section.

### Describe the solution you'd like to see

```ts
<UploadButton
  endpoint="profilePictureUploader"
  somePropName={{
    button: "Custom button text",
	allowedContent: ([mime1, mime2]) => `${mime1.name} Max ${mime1.size}, ${mime2.name} Max ${mime2.size}.`
  }}
>
  Custom button text // this could be used instead
</UploadButton>
```

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

**Comment by markflorkowski** [comment]
Adding a `bug` label as well, since

> Also the colored progress bar covers the text.

should be considered a bug, IMO. 

if you manually apply a `z-index: 50` to the custom text, does it work correctly?

**Comment by ahkhanjani** [comment]
> if you manually apply a `z-index: 50` to the custom text, does it work correctly?

```ts
<UploadButton content={{ button: <span className="z-50">Custom text</span> }} />
```

If you mean this then yes it fixes it.

**Comment by ahkhanjani** [comment]
Could we possibly get the building blocks for an `UploadButton` and build one ourselves? The functionality can be in a wrapper but the UI in our control. This way you could get rid of the whole appearance object and Tailwind long prefixed class names. I don't know the internals so I'm not sure if it's doable. If UI components need a shared state the wrapper can have a context.

```tsx
<UploadButton>
	<UploadButtonLabel>Custom text</UploadButtonLabel>
	<AllowedContent>{([mime1]) => `${mime1.name}. Max ${mime1.size}`}</AllowedContent>
</UploadButton>
```

**Comment by markflorkowski** [comment]
The provided components are intended to be a quick drop-in that supports 99% of use cases, but if you need more granular 
 customization, I think it is probably better to build your own custom components using our hooks.

**Comment by ahkhanjani** [comment]
Hey there @markflorkowski,

I didn't think this issue was finished.

> ### Describe the solution you'd like to see
> ```ts
> <UploadButton
>   endpoint="profilePictureUploader"
>   somePropName={{
>     button: "Custom button text",
> 	allowedContent: ([mime1, mime2]) => `${mime1.name} Max ${mime1.size}, ${mime2.name} Max ${mime2.size}.`
>   }}
> >
>   Custom button text // this could be used instead
> </UploadButton>
> ```

Does this mean we'll never see this option?

**Comment by markflorkowski** [comment]
@ahkhanjani I believe that what you are asking for already exists in uploadthing. You can use the `content` prop, which will accept a function to generate the `allowedContent` text as follows:

```ts
<UploadButton
  content={{
    button({ ready }) {
      if (ready) return <div>Upload stuff</div>;
 
      return "Getting ready...";
    },
    allowedContent({ ready, fileTypes, isUploading }) {
      // do some stuff here to generate your text. 
    },
  }}
/>
```

if you need the endpoint config, you can get that via the `useUploadthing` hook:

```ts
const { permittedFileInfo } = useUploadThing("imageUploader");

// permittedFileInfo will be formatted as:
// {"slug":"imageUploader","config":{"image":{"maxFileSize":"4MB","maxFileCount":1,"contentDisposition":"inline"}}}
```

**Comment by ahkhanjani** [comment]
> @ahkhanjani I believe that what you are asking for already exists in uploadthing. You can use the `content` prop, which will accept a function to generate the `allowedContent` text as follows:

It's unfortunate that we have to override the whole existing behavior such as loading spinner, rather than just changing the button's default text. But I understand. Might not be something worth changing. We could use a bit of DX improvement though.

**Comment by markflorkowski** [comment]
I will discuss with the team, we might consider if you pass a string rather than a  component/function for it to just replace the text, but we would then need a way to access other states, and deciding which will get overridden gets complicated kinda fast.
