### ISSUE TITLE
feat: Option to replace previous file with the same name

### ISSUE THREAD

**Issue by ahkhanjani** [pingdotgg/uploadthing#683]
### Describe the feature you'd like to request

Sometimes we want to have a certain file with a unique signature with the ability to change its content. For example user profile pictures. The file name could always be a hash of user's ID. When updating it, a new URL will be issued but the file in the dashboard should be replaced (and the previous file in S3 automatically deleted). This will make sure we won't have unused profile pictures as users change them over time and it won't cause a huge amount of garbage. This would be great as an option inside the dashboard.

### Describe the solution you'd like to see

Already described

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

**Comment by juliusmarminge** [comment]
you can do this by simply deleting the old file on success?

```ts
const router = {
  profilePicture: f({ image: {} })
    .middleware(async ({ req }) => {
      const { userId } = await auth(req);

      return { userId };
    })
    .onUploadComplete(async ({ file, metadata }) => {
      const { userId } = metadata;
      const [{ image: oldImageUrl }] = await db.select().from(user).where({ userId });
      const [_, key] = oldImageUrl.split("/f/");
      await new UTApi().deleteFiles(key);
    })
}
```

**Comment by ahkhanjani** [comment]
> you can do this by simply deleting the old file on success?

From what I've experienced, an entry with the name is created in uploadthing dashboard before upload even starts, which blocks uploading in the first place. Is this not true?

**Comment by juliusmarminge** [comment]
we don't set any restrictions on file names being unique, so you should be able to upload 2 files with the same name and then delete the first one once the second has finished

**Comment by ahkhanjani** [comment]
> we don't set any restrictions on file names being unique, so you should be able to upload 2 files with the same name and then delete the first one once the second has finished

I see. I wonder why I was getting the duplicate error. I assume it was for when the file name had been saved in uploadthing dashboard but the file itself had not finished uploading yet. Since I had a bad connection it happened a few times. I will let you know if I can recreate it.

**Comment by ahkhanjani** [comment]
I figured out the problem. When renaming files in middleware, `UTFiles` symbol type requires a `customId` field which should be unique. Passing `null` fixes it.

I believe `customId` should be optional.

**Comment by markflorkowski** [comment]
It should be optional. Looking into why it isn't treated as such
