### ISSUE TITLE
[bug]: @uploadthing/react/dist leaves the filesystem root

### ISSUE THREAD

**Issue by MilanObrenovic** [pingdotgg/uploadthing#687]
### Provide environment information

```bash
System:
    OS: macOS 14.3.1
    CPU: (16) x64 Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz
    Memory: 1.84 GB / 40.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.11.0 - ~/.nvm/versions/node/v20.11.0/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.4 - ~/.nvm/versions/node/v20.11.0/bin/npm
    pnpm: 8.15.3 - /usr/local/bin/pnpm
  Browsers:
    Brave Browser: 122.1.63.165
    Chrome: 122.0.6261.112
    Safari: 17.3.1
  npmPackages:
    @uploadthing/react: ^6.3.4 => 6.3.4 
    typescript: ^5.4.2 => 5.4.2 
    uploadthing: ^6.5.2 => 6.5.2
```

### Describe the bug
```
...

  [cause]: [Error: Vc<FileSystemPath>("").join("../node_modules/@uploadthing/react/dist") leaves the filesystem root
  
  Debug info:
  - Execution of get_written_endpoint_with_issues failed
  - Execution of <AppEndpoint as Endpoint>::write_to_disk failed
  - Execution of Project::emit_all_output_assets failed
  - Execution of VersionedContentMap::insert_output_assets failed
  - Execution of all_assets_from_entries failed
  - Execution of AppEndpointOutput::output_assets failed
  - Execution of AppEndpoint::output failed
  - Execution of get_app_client_references_chunks failed
  - Execution of <DevChunkingContext as ChunkingContext>::chunk_group failed
  - Execution of graph_node_to_referenced_nodes failed
  - Execution of <CssModuleAsset as Module>::references failed
  - Execution of parse_css failed
  - Execution of <PostCssTransformedAsset as Asset>::content failed
  - Execution of PostCssTransformedAsset::process failed
  - Execution of dir_dependency failed
  - Execution of FileSystemPath::read_glob failed
  - Execution of FileSystemPath::join failed
  - Vc<FileSystemPath>("").join("../node_modules/@uploadthing/react/dist") leaves the filesystem root] {
    code: 'GenericFailure'
  }
}
```

### Link to reproduction

https://stackblitz.com/edit/github-1fpnbb?file=src%2Fapp%2Fapi%2Fuploadthing%2Froute.ts

### To reproduce

Use the latest version of uploadthing and @uploadthing/react , run the app and get the error

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by markflorkowski** [comment]
Repro seems to work just fine for me.
![image](https://github.com/pingdotgg/uploadthing/assets/11494384/456b0dbf-2050-482f-8994-612593f8182d)

 Running locally, I also don't get that error. 
![image](https://github.com/pingdotgg/uploadthing/assets/11494384/c2918c64-ffa7-492b-bd42-8ac44fc9b0b2)

**Comment by MilanObrenovic** [comment]
@markflorkowski 

https://github.com/pingdotgg/uploadthing/assets/56999235/e59b5051-603e-4806-a043-de91b874c445

i'll let the video speak for me

**Comment by markflorkowski** [comment]
The video is helpful for additional context though, thank you for that.

**Comment by MilanObrenovic** [comment]
> I am not saying the error doesn't exist, just that I can't fix something I cant consistently reproduce.
> 
> If you remove `--turbo` in your dev script does the error still happen?

hm, interesting. removing `--turbo` actually fixes this error. Try adding `--turbo`, you should see this error happen on the latest version of uploadthing, but not earlier. Seems like `@uploadthing/react: 6.3.4` and `uploadthing: 6.5.2` versions are not compatible with nextjs's `--turbo`.

thanks for feedback.

**Comment by markflorkowski** [comment]
Oddly it doesn't happen in stackblitz, will try locally in a little bit. 

Looking into what change we made that may have introduced this incompatibility. I saw that[ NX faced a similar issue](https://github.com/nrwl/nx/issues/19365) in the past.

**Comment by MilanObrenovic** [comment]
> Oddly it doesn't happen in stackblitz, will try locally in a little bit.
> 
> Looking into what change we made that may have introduced this incompatibility. I saw that[ NX faced a similar issue](https://github.com/nrwl/nx/issues/19365) in the past.

he mentioned he ran the development using `--turbo` flag just like me, perhaps this issue has been hiding the entire time for months even in older versions. but oddly enough as you saw in the video i dont get that error in previous 2 versions

**Comment by markflorkowski** [comment]
hmm.... Also not happening for me locally with turbo....

https://github.com/pingdotgg/uploadthing/assets/11494384/e669e1e3-3581-4da9-8dbe-da1bc4d0ec64

**Comment by markflorkowski** [comment]
can you try doing a clean install (remove `.next` and `/node_modules`) to see if the issue happens? I wonder if it is some odd package cache behaviour?

**Comment by MilanObrenovic** [comment]
> can you try doing a clean install (remove `.next` and `/node_modules`) to see if the issue happens? I wonder if it is some odd package cache behaviour?

i just tried:

- `rm -rf node_modules/`
- `rm -rf .next/`
- `rm -rf package-lock.json`
- `npm i`
- `npm run dev` (with turbo flag)

Same error happens. Its definitely the turbo flag for me

**Comment by markflorkowski** [comment]
Alright. Are you able to share the repo (or a zip) of the sample project you are using? I will continue trying to repro on my end, but at least we have narrowed it down a bit

**Comment by MilanObrenovic** [comment]
> Alright. Are you able to share the repo (or a zip) of the sample project you are using? I will continue trying to repro on my end, but at least we have narrowed it down a bit

i'm afraid not, the project is private and non open source right now. but i think it's not about the project, only uploadthing library is causing this issue, no other dependency. i'm using https://www.npmjs.com/package/next-auth?activeTab=versions specifically `5.0.0-beta.15` the "beta" version, not sure if this causes some side effects by impacting uploadthing in this weird way. all libraries, including the beta version of nextauth, work completely fine

**Comment by markflorkowski** [comment]
> but i think it's not about the project, only uploadthing library

Yeah, it's just that I can't repro it in my minimal environment:

```
"dependencies": {
    "@uploadthing/react": "6.3.4",
    "next": "14.1.3",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "uploadthing": "6.5.2"
  },
```

So I am wondering if it has to do with some interaction between deps.

**Comment by juliusmarminge** [comment]
This issue is fairly easy to repro (see https://github.com/juliusmarminge/turbo-leaves-fs) and has been concluded to be a deliberate decision from Turbo's side not to allow searching files outside of the project.

Will change our content configuration to be smarter and not so brute-forcy :)
