### ISSUE TITLE
[bug]: `FileEsque` resolves to `any` if `undici` is not in project

### ISSUE THREAD

**Issue by HugeLetters** [pingdotgg/uploadthing#695]
### Provide environment information

I've provided a stackBlitz repro below - I couldn't use your template since there seems to be some issues with workspace config, neither `npm i` or `pnpm i` work.

### Describe the bug

```ts
import { UTApi } from "uploadthing/server";
export const utapi = new UTApi({ apiKey: env.UPLOADTHING_SECRET });
utapi.uploadFiles()
```
parameter of this function is broken - I've narrowed down the issue to the fact that it uses `File` type from `undici` instead of WebAPI built-in one and undici is nowhere to be found in my dependency tree
```bash
pnpm ls undici --depth=Infinity
```
give no results at all

It seem you have undici as your devDependency - I've tried patching to include it as a regular dependency but that didn't seem to help.

Because of all this input type resolves to `any`

### Link to reproduction

https://stackblitz.com/edit/stackblitz-starters-cvkrdy?file=index.ts

### To reproduce

I think the repro is self-explanatory. Repro uses `npm` instead of `pnpm` so I don't think the issue is with the package manager.

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by juliusmarminge** [comment]
That's interesting... I assume the reason it works anyways for a majority of cases is that Next includes undici so it finds the type anyways... 

Will test and think on how to define the type to allow a variety of different File-ish types

**Comment by HugeLetters** [comment]
@juliusmarminge I use next@13.4.2 on my project FIY
