### ISSUE TITLE
docs: Upload rate limits

### ISSUE THREAD

**Issue by markomitranic** [pingdotgg/uploadthing#704]
### Area of Improvement

It seems that there are some rate limits for uploads in place. At least for the free tier. I've attempted uploading a shitton of files in succession, and have quickly hit a rate limit, after 10ish files.

I can't find any docs about it.

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR implementing the suggested changes!

**Comment by markflorkowski** [comment]
Can you share the specific error you are receiving?

**Comment by markflorkowski** [comment]
Closing for now without additional details/repro. Feel free to reopen with more information about the error you are encountering.

**Comment by markomitranic** [comment]
This isn’t a foss project, its a company, ain’t my job to debug and document. I pointed to a problem, you decide if it needs fixing…

**Comment by markflorkowski** [comment]
I can't repro the issue, and you did not give me enough information to debug it.
