### ISSUE TITLE
docs: Express Adapter doesnt explain why the slug is important

### ISSUE THREAD

**Issue by BatuhanCakir** [pingdotgg/uploadthing#712]
### Area of Improvement

In the Express adapter Docs where you create the router:
`import { createUploadthing, type FileRouter } from "uploadthing/express";
 
const f = createUploadthing();
 
export const uploadRouter = {
  videoAndImage: f({
    image: {
      maxFileSize: "4MB",
      maxFileCount: 4,
    },
    video: {
      maxFileSize: "16MB",
    },
  }).onUploadComplete((data) => {
    console.log("upload completed", data);
  }),
} satisfies FileRouter;
 
export type OurFileRouter = typeof uploadRouter;`

you create a router with a videoAndImage Slug, but this isnt explained when you got to react docs and just follow the tutorial.
where a different slug(imageUploader is used)

### Link to related docs

https://docs.uploadthing.com/backend-adapters/express

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR implementing the suggested changes!

**Comment by markflorkowski** [comment]
This seems like a mistake. The slugs should be consistent across examples.

**Comment by BatuhanCakir** [comment]
Yes and i think there should be small section to explain the slugs.

**Comment by markflorkowski** [comment]
I think that this link covers that: 
![image](https://github.com/pingdotgg/uploadthing/assets/11494384/489a2477-95f5-4854-8859-76d0f18cd467)

**Comment by markflorkowski** [comment]
Added some more details though, since it looks like we do that in the FE examples

**Comment by BatuhanCakir** [comment]
Yeah looks good now.
