### ISSUE TITLE
[Bug]: Usage Nanundefined

### ISSUE THREAD

**Issue by GoodPassiveMan** [pingdotgg/uploadthing#714]
### What happened?

I see `Nanundefined` value for usage in account dashboard `/dashboard` and in app dashboard`/dashboard/APP_ID`

<img width="410" alt="Screenshot 2024-03-16 at 14 34 01" src="https://github.com/pingdotgg/uploadthing/assets/32172971/d9a66a2f-775c-4fc5-ac2a-85c902cce55a">
<img width="262" alt="Screenshot 2024-03-16 at 14 30 54" src="https://github.com/pingdotgg/uploadthing/assets/32172971/c95f98cf-cf38-48fa-9b20-669e5a6bcaf9">

This is odd, because another project shows everything correctly

<img width="853" alt="Screenshot 2024-03-16 at 14 33 52" src="https://github.com/pingdotgg/uploadthing/assets/32172971/35cd22e2-7701-4335-b914-d090c9868c18">

### What did you expect to happen?

It should show valid usage value for all of my apps

### Version

6.5.0

### Reproduction Steps

- visit dashboard
- visit app dashboard

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by juliusmarminge** [comment]
hmm checked your app out and looks like there's something wrong with the quota - will fix it and look into the root cause why it happened
