### ISSUE TITLE
[bug]: PDF file uploads corrupted (Failed to load PDF document)

### ISSUE THREAD

**Issue by quuu** [pingdotgg/uploadthing#718]
### Provide environment information

```bash
System:
    OS: macOS 14.2.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 138.30 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.17.1 - ~/.nvm/versions/node/v18.17.1/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.6.7 - ~/.nvm/versions/node/v18.17.1/bin/npm
    pnpm: 8.4.0 - ~/Library/pnpm/pnpm
    bun: 1.0.30 - ~/.bun/bin/bun
  Browsers:
    Brave Browser: 95.1.31.88
    Chrome: 122.0.6261.129
    Edge: 122.0.2365.92
    Safari: 17.2.1
  npmPackages:
    @uploadthing/react: ^6.4.0 => 6.4.0
    typescript: ^5 => 5.3.3
    uploadthing: ^6.6.0 => 6.6.0
```

### Describe the bug

When uploading a PDF through the upload thing nextjs 14.1 pages router, the pdf shows successfully uploaded, but upon opening the file it shows "failed to load PDF document"
![CleanShot 2024-03-19 at 23 54 41@2x](https://github.com/pingdotgg/uploadthing/assets/32676955/49901666-3abe-4010-9b46-9149745a420d)

broken pdf file --> https://utfs.io/f/8fc2b2fb-a812-48ff-8c1f-1f78a4787e63-vwbqz5.pdf

when uploading the same PDF via  the UI it's fine, but consistently uploaded pdf's through my pages router API results in 

### Link to reproduction

https://stackblitz.com/edit/github-vtmabe?file=src/server/uploadthing.ts,.env

### To reproduce

Set the maxSize to be 16MB

Upload a PDF > 7 MB  (message me if you want the exact file)

was able to repro on the stackblitz as well

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by quuu** [comment]
> seems to be a bug in content type or content disposition headers. if you download the file and open it it does work, so at least the upload is not corrupt

How can I download it from the direct link? The normal download button isn't accessible because the file fails to load?

**Comment by juliusmarminge** [comment]
Right click page and "Save as"

**Comment by juliusmarminge** [comment]
We've fixed it on infra so future uploads should work fine.

If you want I can go and backport the fix on your pdfs?

**Comment by quuu** [comment]
> We've fixed it on infra so future uploads should work fine.
> 
> If you want I can go and backport the fix on your pdfs?

yes please if it's not too difficult :D

**Comment by juliusmarminge** [comment]
Should be good now
