### ISSUE TITLE
[bug]: unable to run dev with tailwind plugin on windows

### ISSUE THREAD

**Issue by mukund1606** [pingdotgg/uploadthing#719]
### Provide environment information

```bash
System:
    OS: Windows 11 10.0.22631
    CPU: (24) x64 13th Gen Intel(R) Core(TM) i7-13700HX
    Memory: 4.17 GB / 15.75 GB
  Binaries:
    Node: 20.11.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.22 - C:\Program Files\nodejs\yarn.CMD
    npm: 10.2.4 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.15.5 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Edge: Chromium (122.0.2365.92)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @uploadthing/react: 6.4.0 => 6.4.0
    typescript: ^5.4.3 => 5.4.3
    uploadthing: 6.6.0 => 6.6.0
```

### Describe the bug

# Issue:
I recently updated my packages and found that I am unable to run dev server or build my next.js app with latest version of uploadthing. Everything was working fine with older version of uploadthing.

### Package Manager Used: pnpm

# This is the error it is showing:-
![image](https://github.com/pingdotgg/uploadthing/assets/85615134/31e3fefd-236a-4666-ae97-ec13fc6765d6)
![image](https://github.com/pingdotgg/uploadthing/assets/85615134/d32e2f57-7e85-4cfe-9a7a-b7afe1d16ab4)

# But if I downgrade to older version my app compiles and works as intended.
![image](https://github.com/pingdotgg/uploadthing/assets/141871182/cef0b415-1aa9-4cb0-acf8-44a8a6b91bf1)

### Link to reproduction

https://github.com/mukund1606/uploadthing-compile-issue/tree/bug

## Steps to reproduce error
 - Update uploadthing from 6.5.2 -> 6.6.0
 - Update @uploadthing/react from 6.3.4 -> 6.4.0

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by juliusmarminge** [comment]
Fixed by https://github.com/pingdotgg/uploadthing/pull/715
