### ISSUE TITLE
[Bug]: Docs SolidStart guide broken url

### ISSUE THREAD

**Issue by barta-adrian** [pingdotgg/uploadthing#72]
### What happened?

On the Getting started page, the SolidStart guide url is not redirecting to the correct page:
```
Continue setting up with the [SolidStart guide](/solidstart/server)
```

should be:

```
Continue setting up with the [SolidStart guide](/solid)
``` 

### What did you expect to happen?

Redirect to the correct page :)

### Version

latest

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by markflorkowski** [comment]
Should be fixed now!
