### ISSUE TITLE
[bug]: onUploadError not working/available (6.6) 

### ISSUE THREAD

**Issue by moritzWa** [pingdotgg/uploadthing#723]
### Provide environment information

```bash
System:
    OS: macOS 14.3.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 59.70 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.17.0 - ~/.nvm/versions/node/v18.17.0/bin/node
    Yarn: 1.22.22 - ~/.nvm/versions/node/v18.17.0/bin/yarn
    npm: 9.6.7 - ~/.nvm/versions/node/v18.17.0/bin/npm
    pnpm: 8.15.5 - ~/.nvm/versions/node/v18.17.0/bin/pnpm
  Browsers:
    Chrome: 123.0.6312.58
    Safari: 17.3.1
  npmPackages:
    @uploadthing/react: ^6.4.0 => 6.4.0 
    typescript: ^5 => 5.3.2 
    uploadthing: ^6.6.0 => 6.6.0
```

### Describe the bug

I'm using the `Dropzone` component to upload files. I want to display the "One or more files are bigger than allowed for their type" error on the client (notifying the user that they cant upload that file size due to the `maxFileSize`)

If I add the `errorFormatter` I get this:
```
Error uploading file Unable to get presigned urls
  - Above error caused by: {
  error: 'One or more files are bigger than allowed for their type',
  data: [ { type: 'pdf', max: 4194304, actual: 17101326 } ]
}
```
I wrote in the ["Error Handling / Catching errors on the client"](https://docs.uploadthing.com/errors#catching-errors-on-the-client) docs section that I can use `onUploadError` to log the server error on the client, but both don't work: 

1. onUploadError property from useUploadthing hook 

```
Property 'onUploadError' does not exist on type '{ readonly startUpload: (files: File[], input?: undefined) => Promise<ClientUploadedFileData<null>[] | undefined>; readonly isUploading: boolean; readonly permittedFileInfo: { ...; } | undefined; }'.ts(2339)
```

2. onUploadError prop on UploadDropzone component

```
Type '{ children: ({ getRootProps, getInputProps, acceptedFiles }: DropzoneState) => Element; onUploadError: (error: Error) => void; multiple: false; onDrop: <T extends File>(acceptedFile: T[]) => Promise<{ id: string; dismiss: () => void; update: (props: ToasterToast) => void; } | undefined>; }' is not assignable to type 'IntrinsicAttributes & DropzoneProps & RefAttributes<DropzoneRef>'.
  Property 'onUploadError' does not exist on type 'IntrinsicAttributes & DropzoneProps & RefAttributes<DropzoneRef>'.
```

How can I log the error on the client?

(This issue might be related https://github.com/pingdotgg/uploadthing/issues/508, however it doesn't seem solved despite being marked as closed)

### Link to reproduction

https://github.com/moritzWa/ai-quote-finder

### To reproduce

1. clone repo: https://github.com/moritzWa/ai-quote-finder
2. npm i 
3. npm run dev

### Additional information

-

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by markflorkowski** [comment]
Can you update to the latest versions of `uploadthing` and `@uploadthing/react`. It seems like the versions in your package.json are out of date:
![image](https://github.com/pingdotgg/uploadthing/assets/11494384/da9f78a9-5497-47cb-b0af-36467d2da3dc)

**Comment by moritzWa** [comment]
@markflorkowski sorry, I just hadn't pushed my local changes.

**Comment by markflorkowski** [comment]
I just cloned your repo, bumped the versions, and tried adding an `onUploadError` to your call of `useUploadthing` and it seems happy (as far as TS is concerned). I don't want to go through and generate a bunch of api keys for stripe, openai, etc to test your repo, but it should work just fine.

I am guessing that you have a bad `node_modules` or `.next` cache.

**Comment by moritzWa** [comment]
Thanks - will try re-installing both.

**Comment by markflorkowski** [comment]
Let me know if you are still having an issue after deleting those two and running `npm i` again

**Comment by moritzWa** [comment]
Deleted both and ran `npm i` but still getting `Property 'onUploadError' does not exist on type...`

![image](https://github.com/pingdotgg/uploadthing/assets/42035131/12a2b80a-bbc5-4b91-8fa3-f3fbf0db60b2)

I also tried using the `UploadDropzone` from @uploadthing/react and here (I wrongly assumed this property also works on react-dropzone lol) the `onUploadError` property works but the `DropZone` itself is only working partially (not sure if I'm missing something. I definitely need to fix the theming): Clicking on `Choose files or drag and drop` does nothing.

![2024-03-21 15 16 44](https://github.com/pingdotgg/uploadthing/assets/42035131/0c03cc18-a257-4b4e-8d5f-34df8768a9d5)

Dragging something into it works though.

However, `onUploadError` finally successfully logged part of the error.

```
Error: Unable to get presigned urls
    at UploadThingError.fromResponse (index.js:346:16)
    at async eval (index.js:138:27)
    at async uploadFilesInternal (index.js:166:29)
    at async eval (button-client-Ry3i9W70.js:174:29)
```
 
This is not sufficient, as I want to tell the user what size their uploaded file was:

Is there any way this can give me the full error?

```
onUploadError={(error: Error) => {
          console.log(error)
        }}
```

**Comment by markflorkowski** [comment]
> Deleted both and ran npm i but still getting Property 'onUploadError' does not exist on type...

Ah, you need to pass it as part of the config:
```ts
const { startUpload } = useUploadThing(
    isSubscribed ? 'proPlanUploader' : 'freePlanUploader',{
      onUploadError: (error) => {
        console.error('Upload error:', error)
        toast({
          title: 'Something went wrong',
          description: 'Please try again later',
          variant: 'destructive',
        })
      }
    }
  )
  ```
  
> This is not sufficient, as I want to tell the user what size their uploaded file was.

I believe there should be [additional properties on the error](https://docs.uploadthing.com/errors#uploadthingerror) -- I think you would want `error.cause`

**Comment by markflorkowski** [comment]
> the DropZone itself is only working partially (not sure if I'm missing something. I definitely need to fix the theming): Clicking on Choose files or drag and drop does nothing.

Seems like our styles are missing, which may cause the element to not be clickable (and also messes up the appearance as you see. 

Since you're using tailwind, you should be able to use our helper to inject the styles:
https://docs.uploadthing.com/theming#how-to-theme

**Comment by moritzWa** [comment]
> I believe there should be [additional properties on the error](https://docs.uploadthing.com/errors#uploadthingerror) -- I think you would want error.cause

`error.cause` is empty. The full stringified error is:
```
{"code":"INTERNAL_SERVER_ERROR","data":{"message":"Unable to get presigned urls"},"cause":{}}
```

**Comment by markflorkowski** [comment]
> `error.cause` is empty. The full stringified error is: ...

It looks like you are not passing the cause to the client:
![image](https://github.com/pingdotgg/uploadthing/assets/11494384/c9875207-4fe1-42e1-bbb8-cba2de42c59f)

if you add it in the return in the `errorFormatter`, you should be able to access it on client.

**Comment by moritzWa** [comment]
> It looks like you are not passing the cause to the client:

hmm, this gives me this ts error:

```
Type '(err: UploadThingError<{ message: string; }>) => { message: string; cause: unknown; }' is not assignable to type '(err: UploadThingError<{ message: string; }>) => Json'.
  Type '{ message: string; cause: unknown; }' is not assignable to type 'Json'.
    Type '{ message: string; cause: unknown; }' is not assignable to type 'JsonObject'.
      Property 'cause' is incompatible with index signature.
        Type 'unknown' is not assignable to type 'JsonValue | JsonObject | JsonArray'.ts(2322)
```

**Comment by moritzWa** [comment]
Update:
- this successfully passes the cause to the client
- but after re-installing my node modules and building the next project, I still get this ts error (hat to ignore it)

**Comment by markflorkowski** [comment]
> Thanks! I wasn't aware this is the logic that passes the error to the client. hmm, this gives me this ts error:

This error is because we type the cause as `unknown`, you can serialize the cause using `JSON.stringify()` to resolve that error:

```ts
errorFormatter: (err) => {
    console.log('Error uploading file', err.message)
    console.log('  - Above error caused by:', err.cause)

    return {
      message: err.message,
      cause: JSON.stringify(err.cause),
    }
  }
  ```
  
  On the client you would need to re-parse it out. 
  
  Alternatively, you could typeguard in the error formatter, and parse out the specific info you are looking for.
