### ISSUE TITLE
ERROR! Failed to get presigned URLs

### ISSUE THREAD

**Issue by regardt-nel** [pingdotgg/uploadthing#73]
Filetype is set to blob and I tried uploading a PNG image.  Not sure if this is a bug, or just wrong config on my end for localhost. 

<img width="479" alt="image" src="https://github.com/pingdotgg/uploadthing/assets/50947477/aa7cf514-48ab-42c6-905f-0ea89d24b225">

**Comment by markflorkowski** [comment]
blob requires content-type to be `application/octet-stream` -- this may be a bug, as the field should probably coerce all content-types to `application/octet-stream`

**Comment by KyleMoran138** [comment]
I'm getting a similar issue, I have a pretty basic setup and no file type limitations or size limitations. Not sure what this is about.

**Comment by markflorkowski** [comment]
@KyleMoran138 Can you share what your router definition looks like?

**Comment by VincentAudette** [comment]
I had the same error make sure you have your api exposed. And I was missing the environment variables: UPLOADTHING_SECRET and UPLOADTHING_APP_ID

**Comment by t3dotgg** [comment]
Assuming this was missing env variables. Next release will have better errors for that. Re-open if you are able to provide a public repro

**Comment by claritise** [comment]
I am getting this issue only on a deployed vercel enviornment (made sure all env vars are set properly) but not locally.

**Comment by Saurabh772244** [comment]
@markflorkowski @t3dotgg I am also getting the same error when running locally. I have t3 stack. I have followed the instructions in the doc for the next app router.
` Error [TypeError]: resolver is not a function`

**Comment by JuanDa14** [comment]
> Filetype is set to blob and I tried uploading a PNG image. Not sure if this is a bug, or just wrong config on my end for localhost.
> 
> <img alt="image" width="479" src="https://user-images.githubusercontent.com/50947477/238378733-aa7cf514-48ab-42c6-905f-0ea89d24b225.png">

I get the same error when I want to upload a pdf, did you solve it?

**Comment by markflorkowski** [comment]
> I get the same error when I want to upload a pdf, did you solve it?

Can you confirm which version of Uploadthing you are using, and share what your router config looks like?

**Comment by Ngash01** [comment]
> Filetype is set to blob and I tried uploading a PNG image. Not sure if this is a bug, or just wrong config on my end for localhost.
> 
> <img alt="image" width="479" src="https://private-user-images.githubusercontent.com/50947477/238378733-aa7cf514-48ab-42c6-905f-0ea89d24b225.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3MTQ5MjcsIm5iZiI6MTcwMTcxNDYyNywicGF0aCI6Ii81MDk0NzQ3Ny8yMzgzNzg3MzMtYWE3Y2Y1MTQtNDhhYi00MmM2LTkwNWYtMGVhODlkMjRiMjI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA0VDE4MzAyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY3MzJlYTA3ODViZWM1NjJmNGQ5YjFlM2I4NTBjNGI1YmYxN2RiNzY4Yjk2ZjZlMDA4NjJhYjhiMDY4ZjIwY2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.v4w-HPhOx8wYmWbEMFYwZe7wOi6K1JBeVH8bsYm1dYE">

I actually had the exact same issue. If it occurs to you it's most probably due to a typo in your core.ts file. Mine was quite simple the maxFileCount object was set to a String instead of a Number. This is what I mean:
    ImageUploader: f({image: {maxFileCount: "1"}}) Instead of ImageUploader: f({image: { maxFileCount: 1}})

**Comment by astro-jets** [comment]
Im facing the same issue. When I upload files that are present on the server everything works fine but when I try to upload files that are not on the server I get that nasty error and I dont know how to solve it.
