### ISSUE TITLE
[Bug]: A bug while displaying no names on the dashboard

### ISSUE THREAD

**Issue by snat-s** [pingdotgg/uploadthing#744]
### What happened?

I don't have a name on my github account and it falls back to `null null`, I am not sure if this is expected behavior.

![image](https://github.com/pingdotgg/uploadthing/assets/65375294/144fc0b7-c96d-4d33-94b4-3ab0e6eea5f7)

### What did you expect to happen?

To not display anything instead of `null null`

### Version

The current version from `https://uploadthing.com/dashboard`.

### Reproduction Steps

Not having a name on the profile of the github account:
![image](https://github.com/pingdotgg/uploadthing/assets/65375294/151f0ef1-26df-41a0-a4d0-1d6500f63bb6)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by juliusmarminge** [comment]
What would you say is a better behavior here? Showing something like `<no name>`?

**Comment by snat-s** [comment]
that sounds pretty good.
