### ISSUE TITLE
[bug]: Fiber Failure

### ISSUE THREAD

**Issue by acosendey** [pingdotgg/uploadthing#777]
### Provide environment information

```bash
System:
    OS: Windows 11 10.0.26100
    CPU: (12) x64 11th Gen Intel(R) Core(TM) i5-11400 @ 2.60GHz
    Memory: 4.94 GB / 31.79 GB
  Binaries:
    Node: 20.12.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 10.5.1 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.0.2 - ~\AppData\Roaming\npm\pnpm.CMD
  Browsers:
    Edge: Chromium (125.0.2492.1)
    Internet Explorer: 11.0.26100.1
  npmPackages:
    @uploadthing/react: ^6.5.0 => 6.5.0
    typescript: ^5.4.5 => 5.4.5
    uploadthing: ^6.10.0 => 6.10.0
```

### Describe the bug

![image](https://github.com/pingdotgg/uploadthing/assets/99757811/59cafded-d33d-4a37-9c83-ade8207ee54a)

I've finished the t3gallery demo and it was working fine, but after the uploadthing update the demo stopped working.

### Link to reproduction

https://github.com/acosendey/logic-boards

### To reproduce

 ℹ UPLOADTHING 17:24:11  UploadThing dev server is now running!
 ⨯ UPLOADTHING 17:24:11  An error occured in your middleware function User does not have permission to upload
 ⨯ UPLOADTHING 17:24:11    at Object.eval [as middleware] (webpack-internal:///(rsc)/./src/app/api/uploadthing/core.ts:40:77)
 ⨯ UPLOADTHING 17:24:11    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Error uploading file User does not have permission to upload
  - Above error caused by: undefined

### Additional information

[My T3 gallery:](https://github.com/acosendey/logic-boards) Feel free to compare the T3 gallery with my repo. I can't see where I messed up, so any feedback is appreciated.

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by adesugbaa** [comment]
Same issue - the errors reported on the client is a generic message to report the issue/failure to UploadThing rather than the actual cause of the error. Had to revert to 6.9.0 to get errors although the message for file size exceeded is also strange - **Unable to get presigned urls**

**Comment by juliusmarminge** [comment]
Looking into this now

**Comment by juliusmarminge** [comment]
do you have a smaller repro? seems like your repo requires api keys for like 10 services

**Comment by juliusmarminge** [comment]
after removing some services i was able to upload successfully: 
![CleanShot 2024-05-06 at 15 09 41@2x](https://github.com/pingdotgg/uploadthing/assets/51714798/f56ea24b-eaac-4fa0-9d7d-521918e4cecc)

so a smaller repro with steps on how to run into the error would be appreicated

**Comment by D4nGuerrero** [comment]
> after removing some services i was able to upload successfully: ![CleanShot 2024-05-06 at 15 09 41@2x](https://private-user-images.githubusercontent.com/51714798/328189452-f56ea24b-eaac-4fa0-9d7d-521918e4cecc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwOTE4OTAsIm5iZiI6MTcxNTA5MTU5MCwicGF0aCI6Ii81MTcxNDc5OC8zMjgxODk0NTItZjU2ZWEyNGItZWFhYy00ZmEwLTlkN2QtNTIxOTE4ZTRjZWNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA3VDE0MTk1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQwZDg0NWYxZTA3YTExZTJlMTkzMTAwYWM0MGFkYmQ0ZTFhNzAzNjEyMTMyMzgzZThlODIzMmJlODg3MGM4MjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VbgNRZXo83IGZOeqssAzssF9MbPoJtd_rySDlJyZCII)
> 
> so a smaller repro with steps on how to run into the error would be appreicated

Intentionally upload an invalid type or size (to test onUploadError). Client gets generic message like [adesugbaa](https://github.com/adesugbaa) mentioned.
