### ISSUE TITLE
Usage of CUSTOM_INFRA_URL for self hosted solution

### ISSUE THREAD

**Issue by JayJamieson** [pingdotgg/uploadthing#78]
I found `CUSTOM_INFRA_URL` and managed to reverse engineer a compatible backend that works with core uploadthing client code. Would there be any issues with using `CUSTOM_INFRA_URL` point to my backend while still using upload thing client library?

**Comment by markflorkowski** [comment]
Nope none at all! We may change the name of that env var at some point in the future, but if we did it should be in the release notes.

**Comment by ynnelson** [comment]
Is there anything on the roadmap that would allow some sort of self hosting capabilities? I am thinking if I have a service that handles sensitive files that would need to be hosted in my own S3? because of a SOC2 constraint and what not?

**Comment by markflorkowski** [comment]
Not at this time. We are still evaluating the compliance landscape to see how much we can do without users needing to self-host, as doing such would significantly slow down our iteration and drive up support cost.

**Comment by ynnelson** [comment]
Makes sense, I guess that would mean uploadthing needing to be SOC2 certified. Thanks for answering, you guys have built a cool product.
We used secureframe to get our SOC2 quickly super straight forward process that connects directly to your AWS account.

**Comment by brrock** [comment]
I have made a self hosted version, it is coming very soon after https://github.com/pingdotgg/uploadthing/pull/1211 is merged
