### ISSUE TITLE
[bug]: Choose File button not working - spinning but never uploads the file.

### ISSUE THREAD

**Issue by lboone** [pingdotgg/uploadthing#782]
### Provide environment information

```bash
System:
    OS: macOS 14.4.1
    CPU: (10) arm64 Apple M2 Pro
    Memory: 251.14 MB / 16.00 GB
    Shell: 3.2.57 - /bin/sh
  Binaries:
    Node: 20.12.2 - /usr/local/bin/node
    npm: 10.5.0 - /usr/local/bin/npm
    pnpm: 9.0.6 - /usr/local/bin/pnpm
  Browsers:
    Chrome: 124.0.6367.92
    Safari: 17.4.1
  npmPackages:
    @uploadthing/react: ^6.5.1 => 6.5.1 
    typescript: ^5.4.2 => 5.4.5 
    uploadthing: ^6.10.1 => 6.10.1
```

### Describe the bug

I am following the "From 0 to Production..." tutorial from Theo -tg.gg on Youtube.  I followed all the steps to put the Choose Files(s) button on the client nav bar.  It works perfectly on the local client.  When I push the code to Vercel it builds successfully.  (Note I also made sure the environment variables are present in Vercel). However when I press the Choose File(s) button on the server version, the button shows the progress bar then the spinner, but it never stops spinning, it also never uploads the file.

Link to my git repository: [https://github.com/lboone/t3gallery](url)

### Link to reproduction

https://t3gallery-f4fefjbe9-lloyd-boones-projects.vercel.app/

### To reproduce

Click the "Choose Files" button in the top right of the navbar.  Select a file to upload, and it will just spin and not complete the upload.

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kret126** [comment]
https://docs.uploadthing.com/faq#my-callback-runs-in-development-but-not-in-production
