### ISSUE TITLE
docs: scrollbar moves up when typing in the search

### ISSUE THREAD

**Issue by dennisdotg** [pingdotgg/uploadthing#788]
### Area of Improvement

When you're scrolled down in the docs and then open the search and start typing the scrollbar moves up.

### Additional information

I wanted to try and fix this myself but I was unable to get the project running from my end. Most likely a skill issue :)

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR implementing the suggested changes!

**Comment by juliusmarminge** [comment]
hmm weird one... does this happen for other nextra sites?

Uploading CleanShot 2024-05-07 at 10.39.20.mp4…
