### ISSUE TITLE
[Bug]: Cannot import {UploadButton} from "@uploadthing/react"

### ISSUE THREAD

**Issue by thebishalniroula** [pingdotgg/uploadthing#80]
### What happened?

Cannot find module '@uploadthing/react' or its corresponding type declarations.

Version: 3.0.4

### What did you expect to happen?

I should have been able to import the UploadButton component as per official docs.

### Version

3.0.4

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by t3dotgg** [comment]
Do you have the codebase public? Restart the typescript server if you haven't already

**Comment by thebishalniroula** [comment]
Nevermind. Restarting the IDE seem to have fixed the issue.
