### ISSUE TITLE
feat: UTApi - getFileUrls should return the customId

### ISSUE THREAD

**Issue by Thiago-cpu** [pingdotgg/uploadthing#804]
### Describe the feature you'd like to request

When I retrieve a list of urls using the customIds, i receive a list with key and url, I don't have an easy way to say which customId belongs to the url retrieved.

### Describe the solution you'd like to see

```ts
const customIds = [...]
const images = await utapi
      .getFileUrls(customIds, {keyType: "customId"})
      .then((r) => new Map(r.data.map(d => ([d.customId, d.url])))); // currently we just have key and url,
```

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

**Comment by markflorkowski** [comment]
We're actually considering deprecating the `getFileUrls()` helper, as it is a bit of an anti-pattern, and we now supports URLs scoped to your app with `utfs.io`.

With the recent change, you can now also use your own customIds directly in the URL without having to make an API call to get the filekey for the url.

Valid URL patterns are:

`https://utfs.io/f/FILE_KEY` <-- how it's always been
`https://utfs.io/a/APP_ID/FILE_KEY`
`https://utfs.io/a/APP_ID/CUSTOM_ID`
