### ISSUE TITLE
Not really a bug but can I use the library without typescript? 

### ISSUE THREAD

**Issue by parameter** [pingdotgg/uploadthing#81]
If yes then can I get someone to help me understand what is done here please and how that would look like without ts 

`<UploadDropzone<OurFileRouter> `

Cheers friends

**Comment by juliusmarminge** [comment]
Sure - if it's JavaScript just omit the generic

`<UploadDropzone {{ props }} />`

**Comment by parameter** [comment]
Thnx. Ah o it's just a prop, nice1
