### ISSUE TITLE
feat: Custom domain with uploadthing

### ISSUE THREAD

**Issue by SolijonovDev** [pingdotgg/uploadthing#815]
### Describe the feature you'd like to request

Add the ability to add a custom domain

### Describe the solution you'd like to see

How can i add custom domain

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

**Comment by juliusmarminge** [comment]
in what regard? 

you can host your own worker that rewrites the requests to `https://utfs.io/a/APP_ID` and deploy that to your own domain. can you be more specific what you want?
