### ISSUE TITLE
[misc]: [Question] Fetching down files uploaded

### ISSUE THREAD

**Issue by marienjus** [pingdotgg/uploadthing#827]
### I understand that this issue may be closed if it should be filed in another category

- [X] I understand

### My issue

I have upload logic up and running, how do I call and retrieve a list of files? E.g for a particular user, or something along this...

**Comment by markflorkowski** [comment]
> how do I call and retrieve a list of files? E

UTAPI `listFiles` -- https://docs.uploadthing.com/api-reference/ut-api#listfiles

>  E.g for a particular user

That would be more likely something that you would need to handle in your own DB. eg. by storing the fileKeys associated with a user.
