### ISSUE TITLE
feat: add us-east-1 N. Virginia

### ISSUE THREAD

**Issue by versecafe** [pingdotgg/uploadthing#833]
### Describe the feature you'd like to request

Add support for US-East 1 to Upload Thing region options

<img width="1353" alt="image" src="https://github.com/pingdotgg/uploadthing/assets/147033096/75114dd4-8c50-400b-9e5d-a7f452ddaedf">

### Describe the solution you'd like to see

*

### Additional information

I'm not sure if there's a reason for not including it but it forces moving all infra to a different region if trying to keep all servers together.

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

**Comment by markflorkowski** [comment]
No particular reason, just picked a minimal subset of regions optimizing for cost and latency. I don't have my original test data anymore, but I found a report that seems to have come to similar conclusions. 
![image](https://github.com/pingdotgg/uploadthing/assets/11494384/ab25fe03-ae9c-4949-956e-ec86770d4e98)

I don't mind adding the additional region though, will add `east-1` to the list for the next time I add a batch of regions 👍

**Comment by versecafe** [comment]
Thanks! if possible could you ping me whenever the change is made?

**Comment by markflorkowski** [comment]
Yup, I will leave this open until the change is made 👍

**Comment by markflorkowski** [comment]
Closing in favor of #840 

@versecafe just wanted to get them all in one place, rather than having a bunch of separate issues. not added yet
