### ISSUE TITLE
[misc]: Vercel preview URLs make up all the top search results for upload thing docs

### ISSUE THREAD

**Issue by versecafe** [pingdotgg/uploadthing#835]
### I understand that this issue may be closed if it should be filed in another category

- [X] I understand

## DuckDuckGo

<img width="1394" alt="image" src="https://github.com/pingdotgg/uploadthing/assets/147033096/7302191c-6d97-4a68-8303-6f88e57d57fc">

<img width="1394" alt="image" src="https://github.com/pingdotgg/uploadthing/assets/147033096/4e622097-9043-4a39-ad7c-5660914ad26f">

## Bing

<img width="1394" alt="image" src="https://github.com/pingdotgg/uploadthing/assets/147033096/17898180-4db6-4c8f-a8ca-033e034aff09">

Since duckduckgo relies partially on bing this should be fixable with bing webmaster tools & making sure to declare canonical URLs on the primary URL, note this is not an Issue on google

**Comment by markflorkowski** [comment]
Argh... I thought we had fixed this... will try again to get this sorted.
