### ISSUE TITLE
feat: add ap-southeast-1 Singapore

### ISSUE THREAD

**Issue by sbkl** [pingdotgg/uploadthing#839]
### Describe the feature you'd like to request

add ap-southeast-1 Singapore

### Describe the solution you'd like to see

add ap-southeast-1 Singapore

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

**Comment by markflorkowski** [comment]
Closing in favor of #840
