### ISSUE TITLE
feat: Ability to export multiple images as a CSV or JSON

### ISSUE THREAD

**Issue by gbrrrl-no** [pingdotgg/uploadthing#842]
### Describe the feature you'd like to request

When browsing through multiple files in a project there's not easy way to just export all the files data. It'd be really nice to be able to get all the files names, links and sizes with a simples export button.

### Describe the solution you'd like to see

As of right now there already is a "select row" function used to delete many files at once. The solution I see is to use the same feature, but adding a "Export" menu item right above "Delete files".

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

**Comment by markflorkowski** [comment]
To confirm, you are not trying to download the actual files, just their data? ie what is shown in the table?

**Comment by markflorkowski** [comment]
Assuming that was the case, this feature is now available in the dash.
![image](https://github.com/pingdotgg/uploadthing/assets/11494384/bfa45d8b-9bc3-496d-9c64-0e55b8602748)
