### ISSUE TITLE
[Bug]: Charset not set properly

### ISSUE THREAD

**Issue by darklight9811** [pingdotgg/uploadthing#857]
### What happened?

When uploading a file with ãâá (etc), it bugs out on the file overview page.

![image](https://github.com/pingdotgg/uploadthing/assets/20667774/49b9fd20-681f-4224-81fe-f7af57ec36d9)

### What did you expect to happen?

To display the chars properly.

### Version

the version up on day 15/06/2024 of the dashboard

### Reproduction Steps

upload a file containing ãâáà

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by juliusmarminge** [comment]
What version of the SDK are you uploading from?

Tried with a dashboard upload and it worked for Swedish characters:

![CleanShot 2024-06-17 at 09 10 48@2x](https://github.com/pingdotgg/uploadthing/assets/51714798/caf75b69-51d0-4338-a00a-7bdb7c3f0e99)

![CleanShot 2024-06-17 at 09 10 41@2x](https://github.com/pingdotgg/uploadthing/assets/51714798/4057318d-6f00-41f6-a2b5-970b92585c25)
