### ISSUE TITLE
feat: rename files through gui

### ISSUE THREAD

**Issue by kp224** [pingdotgg/uploadthing#862]
### Describe the feature you'd like to request

the ability to rename files directly on the uploadthing website

### Describe the solution you'd like to see

a little text box that lets you rename a file...

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

**Comment by WiseyXD** [comment]
> ### Describe the feature you'd like to request
> the ability to rename files directly on the uploadthing website
> 
> ### Describe the solution you'd like to see
> a little text box that lets you rename a file...
> 
> ### Additional information
> _No response_
> 
> ### 👨‍👧‍👦 Contributing
> * [ ]  🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!



> Would like to hear more on the use-case here. Generally the dashboard is designed for quickly viewing content (and deleting in emergencies), ideally you'd use the API for things like this

can you explain what feature you need in dashboard ? my takeaway is to create a little text box to change the name of the file present is the dashboard 

![ds](https://github.com/pingdotgg/uploadthing/assets/113956956/f2aec728-120d-4e29-958e-f30cb7dbe97a)

to change the name of the above file is the feat required ?

**Comment by markflorkowski** [comment]
We understand that is what the OP is asking for, we are asking for clarification on _why_ they are asking for it.

**Comment by t3dotgg** [comment]
Closing, will re-open if OP responds with more context :)
