### ISSUE TITLE
[billing]: How do I pay for org plan instead of personal?

### ISSUE THREAD

**Issue by jcontini** [pingdotgg/uploadthing#882]
### I understand that this issue may be closed if it should be filed in another category

- [X] I understand

### My issue

Hi! I tried to make an organizational plan from the start, but it wouldn't let me until I made a paid plan on my personal account. 

So I bought the $10 a month plan on my personal account, and then I created an organization, but now the organization wants me to buy it again.

I just wanted to create an organization with a paid plan from the start, but now I have a free organization plan and a pro-personal plan. How can I transfer the paid license from my personal plan account to the organization account? It's all in the same email.

Thanks! Hope filing an issue is ok - I couldn't find a support option from the dashboard or docs.

**Comment by juliusmarminge** [comment]
the plans are not linked to your account, it's linked to the app, and we currently limit orgs to paid apps. So, after you've upgraded the app to a paid plan, you can create an org and transfer the app there by going to `settings`, then `transfer`

**Comment by markflorkowski** [comment]
What Julius said is correct, however this is good feedback to hear. I will put some time into thinking about how we can make it more clear/allow you as a user to create an app directly in an org within the checkout flow.

**Comment by jcontini** [comment]
Thanks @juliusmarminge @markflorkowski!

I transferred the plan to the org but was then taken to a 404 page `https://uploadthing.com/dashboard/koeyqm8ijj/settings`

Seems to have worked though so I'm good to go! Thank you.
