### ISSUE TITLE
[Bug]: `UTApi` is deleting the file but still able to directly access the file from its URL.

### ISSUE THREAD

**Issue by Abdullahiqbal2021** [pingdotgg/uploadthing#884]
### What happened?

I am using UTApi to delete my uploaded images. The images are deleted successfully and no longer appear in the dashboard. However, I can still directly access the deleted file from its previously stored URL.
> It also frees up space for my free tier. 🙂

### What did you expect to happen?

 The file should not be accessible via its URL after deletion.

### Version

Using
"@uploadthing/react": "^6.7.2",
"uploadthing": "^6.13.2"

### Reproduction Steps

Just follow your [docs](https://docs.uploadthing.com/api-reference/ut-api)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by markflorkowski** [comment]
@Abdullahiqbal2021 can you share your appId and an example of an affected file key ?

**Comment by Abdullahiqbal2021** [comment]
@markflorkowski this is the [repo](https://github.com/Abdullahiqbal2021/next-boiler-plate) i am working on and created a simple page to recreate issue.
My **UPLOADTHING_APP_ID** is
```bash
2bf2bglzre
```
and affected file is 
```bash
https://utfs.io/f/4733bc96-8510-4484-9543-d9a52d33f709-bjnd11.png
```

I am currently using **Chrome**. I thought it was some cache issue but i open the image link in firefox and was able to access the image.

The image seems to be deleted as it does not appear in dashboard any more but we can access it directly from its stored url.

**Comment by Abdullahiqbal2021** [comment]
@markflorkowski  I just access the above URL and file is not accessible. I think it take some time to delete the file but the file disappears from the dashboard immediately.

**Comment by markflorkowski** [comment]
> I think it take some time to delete the file but the file disappears from the dashboard immediately.

Yes, this is correct. We optimistically remove it from the dashboard, but in reality it can take probably up to 30 seconds for the file to actually be fully removed.

**Comment by Abdullahiqbal2021** [comment]
> > I think it take some time to delete the file but the file disappears from the dashboard immediately.
> 
> Yes, this is correct. We optimistically remove it from the dashboard, but in reality it can take probably up to 30 seconds for the file to actually be fully removed.

Thanks 👍
