### ISSUE TITLE
docs: Missing Code of Conduct

### ISSUE THREAD

**Issue by Bashamega** [pingdotgg/uploadthing#892]
### Area of Improvement

The repository is missing the code of conduct file.

Why add a code of conduct file?
A code of conduct to define community standards, signal a welcoming and inclusive project, and outline procedures for handling abuse.

You can learn more about it here: https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-code-of-conduct-to-your-project

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR implementing the suggested changes!

**Comment by markflorkowski** [comment]
Feel free to open a PR adding one for us to review. We have not had any issues with bad behavior yet, so it has not been a high priority to add one.
