### ISSUE TITLE
docs: Missing Contributing File

### ISSUE THREAD

**Issue by Bashamega** [pingdotgg/uploadthing#893]
### Area of Improvement

Hello:)

The contributing guide file is missing. It is nice to have one.

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR implementing the suggested changes!

**Comment by juliusmarminge** [comment]
https://github.com/pingdotgg/uploadthing#contributing

**Comment by Bashamega** [comment]
A separate `CONTRIBUTING.md` file is better. Here's why:

1. A separate file for contributing guidelines helps organize information better. The README.md can describe the project, its use, and features. The CONTRIBUTING.md can give detailed guidelines on how to contribute.
2. GitHub recognizes the CONTRIBUTING.md file. It gives a direct link to it when someone creates a new issue or pull request. This makes it more likely for contributors to see and read the guidelines.
3. A dedicated file lets you include detailed information without making the README.md messy. You can cover many aspects like coding standards how to set up the development environment, and how to submit pull requests.
4. A clear guide for contributors can inspire more people to help out. It gives step-by-step instructions and makes the whole process less scary.

Still, you can add a short part in your README.md that links to the CONTRIBUTING.md file. This way, people who start with the README.md will know about the rules for contributing.
