### ISSUE TITLE
style(website): add scroll bar to improve accessibility

### ISSUE THREAD

**Issue by MichaHuhn** [pingdotgg/uploadthing#894]
### I understand that this issue may be closed if it should be filed in another category

- [X] I understand

### My issue

The [uploadthing website](https://uploadthing.com) doesn't have a scroll bar in Chrome, Edge, and Opera GX.

It would be beneficial to add one to improve accessibility.

**Comment by markflorkowski** [comment]
Just merged a change that should bring back scrollbars. Let me know if it is better @MichaHuhn

**Comment by MichaHuhn** [comment]
Works perfectly. Thank you!

**Comment by MichaHuhn** [comment]
@markflorkowski
I just noticed that this change created a horizontal scroll bar.

The `w-screen` class on the `<body>` is probably causing this issue.
When I remove it, the horizontal scroll bar disappears.

(I didn't notice it a few minutes ago, because the lightgray scroll bar has a white background.)

**Comment by markflorkowski** [comment]
Good catch, just pushed up a fix, should be deployed shortly
