### ISSUE TITLE
feat: enhance listFiles api to return additional fields

### ISSUE THREAD

**Issue by kuizuo** [pingdotgg/uploadthing#899]
### Describe the feature you'd like to request

I noticed that the files in the dashboard show size and uploaded.

![image](https://github.com/user-attachments/assets/56b4f02d-d6a2-4c0f-ba6f-15b91e687e81)

but [listFiles](https://docs.uploadthing.com/api-reference/ut-api#listfiles) api doesn't have.

```ts
import { utapi } from "~/server/uploadthing.ts";
 
const files = await utapi.listFiles();
 
console.log(files);
/*
 * [
 *  {
 *    id: "7099d109-39ec-43fe-a887-4a4fd87cad88 ,
 *    customId: null, // whatever you set it to when uploading
 *    key: "2e0fdb64-9957-4262-8e45-f372ba903ac8_image.jpg",
 *    name: "image.jpg",
 *    status: "uploaded",
 *  }
 * ]
 */
```

### Describe the solution you'd like to see

I want to use the metadata field to return this additional information.  And through an option in the request body to decide whether to output

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

**Comment by markflorkowski** [comment]
We kind of expect you to store that information in your own DB, `listFiles` being more of a backup method, hence why it does not return much info. 

That said, after talking with the team, we are considering adding additional info to the return from this API. Do note however, we will likely be rate-limiting requests to this endpoint, as we still want to encourage storing this information on your own DB.

**Comment by SrBrahma** [comment]
@markflorkowski, would you recommend a simple cloud DB with a similar very easy setup for this info?
