### ISSUE TITLE
[Feat] Darkmode for dashboard

### ISSUE THREAD

**Issue by TheDevMinerTV** [pingdotgg/uploadthing#9]
![As a user I want to have a darkmode so that I don't burn my eyes out](https://github.com/pingdotgg/uploadthing/assets/29845135/249ecb62-c111-45e9-8a44-f955cc35e533)

**Comment by markflorkowski** [comment]
Theo caved. I am disappointed.

**Comment by TheDevMinerTV** [comment]
tyvm <3

**Comment by t3dotgg** [comment]
As of today, dark mode is available for all _paid_ users :)

**Comment by ahmad1702** [comment]
where do you get off

**Comment by mitchellston** [comment]
lol

**Comment by Pammota** [comment]
i also wish RGB mode to be added

**Comment by willi-bit** [comment]
A full colorwheel including 16 base color modes (expandable with a Tier 3 sub) should be in a premium plus plan, **OMW** to patenting this idea

**Comment by Kn0ax** [comment]
imagine paywalling a css option  
`background-color: black;`
what a devil money hungry company!!! 
how dare you Theo, how you could do this to us... 
my hearth now broken and my tears can't even visible on that white dashboard...

**Comment by Karlosbubi** [comment]
Get free dark mode : https://addons.mozilla.org/de/firefox/addon/darkreader/
xD

**Comment by Brenden2008** [comment]
It's only _10_ dollars a month, real devs can afford it! -Theo

**Comment by youngchief-btw** [comment]
Let's just appreciate the native dark mode exists at all :)

**Comment by ronanru** [comment]
If you want darkmode for free, check out my chrome extension - https://github.com/ronanru/uploadthing-darkmode

**Comment by TheShadowblast123** [comment]
Do you guys not have phones?

**Comment by ahmad1702** [comment]
I made this specifically as a result of the greedy, non-accessable, battery wasting, environment hating decisions made by this issue: [darkmodeisthe.best](https://www.darkmodeisthe.best/)

**Comment by Brenden2008** [comment]
Incredible
