### ISSUE TITLE
docs: vanilla react/ssr

### ISSUE THREAD

**Issue by nitedani** [pingdotgg/uploadthing#908]
### Area of Improvement

I would like to see vanilla React/React SSR under "Getting Started" in the docs.
Does this need implementation changes, or only docs?

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR implementing the suggested changes!

**Comment by markflorkowski** [comment]
I think it should just need docs. cc @juliusmarminge

**Comment by juliusmarminge** [comment]
You mean a combination of backend adapter + client lib?

**Comment by markflorkowski** [comment]
I think so. At least for common combos eg React/Express
