### ISSUE TITLE
docs: self hosted s3(minio)

### ISSUE THREAD

**Issue by nitedani** [pingdotgg/uploadthing#909]
### Area of Improvement

Either explain in the docs, why self-hosted s3(like minio) is not supported, or add support for it.

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR implementing the suggested changes!

**Comment by nitedani** [comment]
I see, this is a product and not only a library. 😅 I see self hosting will be an enterprise feature, so that explains why.

**Comment by allentown521** [comment]
A little confused about the documentation, is your project deploying an API
service? So why do we need to rely on some of the environment variables of
uploadthing?

Focus Apps ***@***.***> 于2025年6月30日周一 14:55写道：
