### ISSUE TITLE
[Bug]: Profile Page has padding-bottom styling issue

### ISSUE THREAD

**Issue by Jiansorge** [pingdotgg/uploadthing#911]
### What happened?

![image](https://github.com/user-attachments/assets/c9a33629-aadb-4b8e-aeef-582d0b352d6c)

### What did you expect to happen?

Text should not be overhanging modal component.

### Version

Firefox 128.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by markflorkowski** [comment]
Good catch. I'll take a look at that today.

**Comment by markflorkowski** [comment]
Fix has been merged.
