### ISSUE TITLE
feat: Upload a buffer / base64 with fetch / post

### ISSUE THREAD

**Issue by pguardiario** [pingdotgg/uploadthing#914]
### Describe the feature you'd like to request

I'd like to be able to post a buffer / base64 string to an endpoint instead of using the wrappers

### Describe the solution you'd like to see

```
fetch("/api/uploadBuffer", {
  headers: {"content-type": "application/json"},
  method: "POST",
  body: {
    name: "xxx.png",
    base64: "some base64 string"
  }
})
```

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

**Comment by markflorkowski** [comment]
Files are uploaded directly to storage, not through the API. You can already do it yourself without wrappers, just need to request a presigned URL via the API, and post to it. We're working on some docs that outline this more clearly so you don't need to figure it out from the package source: [WIP Docs](https://docs-uploadthing-git-docs-upload-files-pinglabs.vercel.app/uploading-files)
