### ISSUE TITLE
[bug]: OnUploadComplete is not called in expressjs server

### ISSUE THREAD

**Issue by vtcong21** [pingdotgg/uploadthing#920]
### Provide environment information

```bash
System:
    OS: Windows 11 10.0.22631
    CPU: (4) x64 Intel(R) Core(TM) i3-10110U CPU @ 2.10GHz
    Memory: 2.28 GB / 11.84 GB
  Binaries:
    Node: 18.17.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 9.6.7 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.22621.3527
```

### Describe the bug

The file is uploaded:
```
POST /api/uploadthing?actionType=upload&slug=courseThumbnail 200 1289.266 ms - 2452
```
But it seems like the OnUpLoadComplete is not called, im not sure that i config it right, please help me:
core.js:
```
import { createUploadthing } from "uploadthing/express";
import dotenv from 'dotenv';
dotenv.config();

const f = createUploadthing();


export const ourFileRouter = {
  courseThumbnail: f({
    image: { maxFileSize: "1MB", maxFileCount: 1 },
  }).onUploadComplete((response) => {
    // Log to check if the callback is triggered, but it is not called
    console.log('onUploadComplete callback triggered');

        return response;
  }),
  // courseAdvertisementVideo: f({
  //   video: { maxFileSize: "2MB", maxFileCount: 1 },
  // })
  //   .onUploadComplete(() => { }),
  // courseSectionFile: f(["text", "image", "video", "audio", "pdf"])
  //   .onUploadComplete(() => { }),
  // courseSectionVideo: f({ video: { maxFileSize: "2MB", maxFileCount: 1 } })
  //   .onUploadComplete(() => { }),
};
```
app.js:
```

app.use(
  "/api/uploadthing",
  createRouteHandler({
    router: ourFileRouter,
    config: {
      uploadthingId: process.env.UPLOADTHING_APP_ID,
      uploadthingSecret: process.env.UPLOADTHING_SECRET,
      //logLevel: "debug",
      
    }
    //secret: process.env.UPLOADTHING_SECRET,
  }),
);

```

### Link to reproduction

https://github.com/vtcong21/adb-21vp-lms/tree/gui-cong

### To reproduce

I'm not sure that i config it right, so i'm not sure it's a bug to reproduce.

### Additional information

The server is buit in expressjs, and the client is buit in vite reactjs, i know its not a good idea, just trying to test this package.

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by markflorkowski** [comment]
What does the `Status` column on the files table show in the Uploadthing dashboard?

**Comment by vtcong21** [comment]
The status shows "Uploaded". This issue is occurring in the local development environment, and i'm not sure if it happens in other environments.

**Comment by markflorkowski** [comment]
For local development, the callbacks should be simulated, so onUploadComplete should be firing. 🤔 

Are you seeing any logs in your server console like this?

`Failed to simulate callback for file 'YOUR_FILENAME'. Is your webhook configured correctly?`

**Comment by vtcong21** [comment]
Hmm, no i don't see any logs like that. I changed the logLevel to "debug", and everything looks really fine to me, but the callback didn't be called.

**Comment by akins-dev** [comment]
@vtcong21 were you able to fix it? I'm facing similar issue here.

**Comment by akins-dev** [comment]
> @vtcong21 were you able to fix it? I'm facing similar issue here.

Finally! For me, it was because `/api/uploadthing` was listed in my protected routes.

I just had to remove it, and voilà—it works!
