### ISSUE TITLE
[bug]: Cant use server stuff in middleware and UTApi 

### ISSUE THREAD

**Issue by Fesyse** [pingdotgg/uploadthing#931]
### Provide environment information

```bash
System:
    OS: Windows 10 10.0.19045
    CPU: (6) x64 Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz
    Memory: 3.18 GB / 15.94 GB
  Binaries:
    Node: 21.6.1 - C:\Program Files\nodejs\node.EXE      
    Yarn: 1.22.22 - C:\Program Files\nodejs\yarn.CMD     
    npm: 10.2.4 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.6.0 - C:\Program Files\nodejs\pnpm.CMD
    bun: 1.1.24 - ~\.bun\bin\bun.EXE
  Browsers:
    Edge: Spartan (5.1.19041.3803), Chromium (5.1.19041.3803), ChromiumDev (5.1.19041.3803)
  npmPackages:
    @uploadthing/react: ^6.7.2 => 6.7.2
    typescript: ^5.5.4 => 5.5.4
    uploadthing: ^6.13.2 => 6.13.2
```

### Describe the bug

When im trying to use `auth` function which is created by NextAuth, every time i route to any page it throws an error with packages not found:
```bash
 ⨯ ./node_modules/.pnpm/postgres@3.4.4/node_modules/postgres/src/connection.js:1:1
Module not found: Can't resolve 'net'
> 1 | import net from 'net'
    | ^^^^^^^^^^^^^^^^^^^^^
  2 | import tls from 'tls'
  3 | import crypto from 'crypto'
  4 | import Stream from 'stream'
  ```
and thats because this `middleware` function running not on server, but on the client instead
same thing happening with UTApi, because it runs not on the server it throws:
```bash
UploadThingError: The `utapi` can only be used on the server.
```

### Link to reproduction

https://github.com/Fesyse/tasklytic/tree/uploadthing-issue

### To reproduce

- Clone repository
- Create new local database with pgAdmin
- Create and paste this in `.env` file:
```env
DATABASE_URL="postgresql://postgres:<YOUR_DATABASE_PASSWORD>@localhost:5432/tasklytic"

# Next Auth
# You can generate a new secret on the command line with:
# openssl rand -base64 32
# https://next-auth.js.org/configuration/options#secret
NEXTAUTH_SECRET=""
NEXTAUTH_URL="http://localhost:3000"

# Next Auth Discord Provider
DISCORD_CLIENT_ID=""
DISCORD_CLIENT_SECRET=""
# Next Auth Google Provider
GOOGLE_CLIENT_ID=""
GOOGLE_CLIENT_SECRET=""
# Next Auth Github Provider
GITHUB_CLIENT_ID=""
GITHUB_CLIENT_SECRET=""

# Uploadthing
UPLOADTHING_SECRET=""
UPLOADTHING_APP_ID=""
```
- Run dev server with `bun dev` or `pnpm dev`
- Go to any page

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by t3dotgg** [comment]
Took a quick look at your repo, it seems like you have a fundamental misunderstanding about the difference between client and server code. Lots of examples where you're calling client-specific code in server files and vice versa. Nothing here is an UploadThing issue

**Comment by Fesyse** [comment]
Hello, thank you for your responding. Yea actually its was my fault, in Providers client component i put NextSSRPlugin with fileRouter by accidently, removing it solved problem. Sorry about that
