### ISSUE TITLE
[misc]: Really slow upload on a small file

### ISSUE THREAD

**Issue by LeoCaprile** [pingdotgg/uploadthing#934]
### I understand that this issue may be closed if it should be filed in another category

- [X] I understand

### My issue

I'm want to use uploadthing for an intensive image uploading app, but I'm concern about the speed of the uploads, there's a reason why it takes **6 seconds**  to upload a **1.6kb image** ?

The request
![image](https://github.com/user-attachments/assets/4c0e14a4-c997-447f-99b2-ac7d5ea3fe99)

The image in UT dashboard.
![image](https://github.com/user-attachments/assets/b72b498a-96de-4b57-a853-41b58b2e9627)

The implementation
![image](https://github.com/user-attachments/assets/d0f978b9-8fea-4f59-b34f-7a0699592c60)

Please tell me if I'm doing something wrong, thanks for the help!

**Comment by markflorkowski** [comment]
Hmm, not sure why it would be so slow using the serverside UTApi functions. Will try to repro locally 👀

**Comment by markflorkowski** [comment]
FWIW, the UTApi functions are more intended for use cases where the files are generated serverside, and we primarily recommend handling client-side uploads with a `fileRouter` and whichever client-side helpers make sense in your use case. 

That said, the server-side function should not be that slow, looking into that now.

**Comment by markflorkowski** [comment]
Was able to repro similar behavior locally, ~4s for a 7kb file. Same upload took less than a second using elysia server [example we provide](https://github.com/pingdotgg/uploadthing/blob/f5e080e2c6b29031995b9b1e0f21cadfc37ce213/examples/backend-adapters/package.json#L14) (using react client, and `fileRouter` pattern)

Only difference being that one uploads from the client, vs the other which ingests the file to the server, then uploads it 🤔

**Comment by LeoCaprile** [comment]
I think this here is were the router is throwing, 

https://github.com/pingdotgg/uploadthing/blob/f5e080e2c6b29031995b9b1e0f21cadfc37ce213/packages/uploadthing/src/internal/validate-request-input.ts#L194

**Comment by LeoCaprile** [comment]
Oh ok, I think I get it now, so I need to use the UT react client in order to make it work.

So what if I need to use it on the server and create my own endpoint implementation, isn't the `UTApi` function made for that? and if so, why is so slow?

**Comment by markflorkowski** [comment]
> @markflorkowski so the UTApi is more slow because it ingest the files to the server and then uploads to UT?

No, I am still unsure why it is slower. It shouldn't be. 

> So what if I need to use it on the server and create my own endpoint implementation, isn't the UTApi function made for that?

Yes, the UTApi is intended for uploading from the serverside. If your product is an api that others are hitting and uploading files to, or you are modifying files before storing them, it makes sense to use the UTApi functions.

If instead, your product is a web app, where your users are uploading files from within said app, it makes more sense to use our client adapters, and the `fileRouter`. 

> If so, why is so slow?

Still investigating this.

**Comment by LeoCaprile** [comment]
> > @markflorkowski so the UTApi is more slow because it ingest the files to the server and then uploads to UT?
> 
> No, I am still unsure why it is slower. It shouldn't be.
> 
> > So what if I need to use it on the server and create my own endpoint implementation, isn't the UTApi function made for that?
> 
> Yes, the UTApi is intended for uploading from the serverside. If your product is an api that others are hitting and uploading files to, or you are modifying files before storing them, it makes sense to use the UTApi functions.
> 
> If instead, your product is a web app, where your users are uploading files from within said app, it makes more sense to use our client adapters, and the `fileRouter`.
> 
> > If so, why is so slow?
> 
> Still investigating this.

Thanks

**Comment by LeoCaprile** [comment]
Hey @markflorkowski, I decided to do the nextjs app router implementation instead of my own server, its almost the same time, it takes almost 6 secondish to upload an image of 1.7kb, could be because im located in south america?

Here's the browser network tab:

![image](https://github.com/user-attachments/assets/6a5a1f93-0d2c-4652-bc2a-516316ca8d80)

**Comment by markflorkowski** [comment]
In this case the long time is likely due to polling (on by default), if you are not using data returned from a serverside `onUploadComplete` on the client, you can add[ `skipPolling` option ](https://docs.uploadthing.com/api-reference/react#configuration)to the components/hook to have the client treat the upload as complete without waiting for your backend server to be hit with our webhook. When v7 is released, this will be a non-issue as the entire flow of files is changed.

**Comment by markflorkowski** [comment]
@LeoCaprile -- Just following up on this, now that V7 is live, have you had a chance to give it a try to see if the performance is any better?

**Comment by AhmedBaset** [comment]
> This issue has been closed because it has not had any activity for 5 days since being marked as stale.

I don't think this issue should be closed. A 10kb file takes +3 seconds

**Comment by markflorkowski** [comment]
@AhmedBaset  - Can you repro this behaviour on the latest v7 versions of uploadthing?

**Comment by gerkim62** [comment]
I stumpled across this issue in v7.2.0 of uploadthing
 `const response = await utapi.uploadFiles([image]);`
 
 is taking ages. am using express

**Comment by sekmet** [comment]
![image](https://github.com/user-attachments/assets/fcb7978b-f256-4963-a961-bee60f48b369)
Same here, I'm using the REST API. The upload is not finished, keep uploading state forever!

**Comment by markflorkowski** [comment]
> ![image](https://github.com/user-attachments/assets/fcb7978b-f256-4963-a961-bee60f48b369)
> 
> Same here, I'm using the REST API. The upload is not finished, keep uploading state forever!

This looks more like what happens when your server can't be reached by our servers for the incomplete callback. In this case it will stay in the "uploading" state until a timeout is reached (1 day I believe), then transition to "failed"

**Comment by markflorkowski** [comment]
> I stumpled across this issue in v7.2.0 of uploadthing `const response = await utapi.uploadFiles([image]);`
> 
> is taking ages. am using express

Can you enable debug logs and share the output for a test file upload, it should have timing data so we can narrow down what in the upload process is slow.

**Comment by mahdinazmi** [comment]
@sekmet 
Did you solve?

**Comment by mahdinazmi** [comment]
> ![image](https://private-user-images.githubusercontent.com/3760421/391397437-fcb7978b-f256-4963-a961-bee60f48b369.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0NzcwNTksIm5iZiI6MTczMzQ3Njc1OSwicGF0aCI6Ii8zNzYwNDIxLzM5MTM5NzQzNy1mY2I3OTc4Yi1mMjU2LTQ5NjMtYTk2MS1iZWU2MGY0OGIzNjkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMDZUMDkxOTE5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmEzMTBiZjM3MzEyYTNmYWE1NWMzYmU1MTExMTNjNGNiMjEwM2RjMDcwNWFjZTMyNjk1ODNiOWI2YjJjNjA1ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.FFhoE4Di2Eqr7X4K-BjaVloctyj6wsT7k6oodayPKFQ) Same here, I'm using the REST API. The upload is not finished, keep uploading state forever!

Did you solve?

**Comment by mahdinazmi** [comment]
> This looks more like what happens when your server can't be reached by our servers for the incomplete callback. In this case it will stay in the "uploading" state until a timeout is reached (1 day I believe), then transition to "failed"

So basically we can't use rest api in a nextjs app? I am currently testing locally as below so that I can upload, but it gets stuck in uploading
![Uploading 2024-12-06 13_05_45-Window.png…]()

**Comment by mahdinazmi** [comment]
> > ![image](https://private-user-images.githubusercontent.com/3760421/391397437-fcb7978b-f256-4963-a961-bee60f48b369.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0NzgxNTIsIm5iZiI6MTczMzQ3Nzg1MiwicGF0aCI6Ii8zNzYwNDIxLzM5MTM5NzQzNy1mY2I3OTc4Yi1mMjU2LTQ5NjMtYTk2MS1iZWU2MGY0OGIzNjkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMDZUMDkzNzMyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDI5YzIwNmZkNmE4MjQ0YmZkNzE4ZjY4ZTI4MDNmYTliODg5MTJhZDQ5ZTM5ZTgzNTU3ZTE0MTc4YTUzNzc3NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.kTMU9NnJqqJMKpTh8VzNiaG1CxaC6Bs2p-yGY--PeK0)
> > Same here, I'm using the REST API. The upload is not finished, keep uploading state forever!
> 
> This looks more like what happens when your server can't be reached by our servers for the incomplete callback. In this case it will stay in the "uploading" state until a timeout is reached (1 day I believe), then transition to "failed"

So basically we can't use rest api in a nextjs app? I am currently testing locally as below so that I can upload, but it gets stuck in uploading

![Uploading 2024-12-06 13_05_45-Window.png…]()

**Comment by markflorkowski** [comment]
> So basically we can't use rest api in a nextjs app? I am currently testing locally as below so that I can upload, but it gets stuck in uploading

You should be able to, though we do offer a native NextJS implementation that makes things much easier than having to manually interact with the api. 

That said, I can't really tell what you are doing from your screenshot. What is the value of UPLOADTHING_API_URL?
