### ISSUE TITLE
docs: Add example values for REST api

### ISSUE THREAD

**Issue by ljrahn** [pingdotgg/uploadthing#957]
### Area of Improvement

For the REST API documentation, all of the examples only contain required fields, but not examples for values. As someone who is not intimately familiar with all the terms used throughout the rest of the documentation, it would make it simpler to see an example value eg:

POST deleteFiles. What is files? Is it an array of urls? What are customIds?

### Link to related docs

https://docs.uploadthing.com/api-reference/openapi-spec

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR implementing the suggested changes!

**Comment by markflorkowski** [comment]
Good callout, will need to check if the tool we use for generating those docs supports this or if we will need to build something to support it.

**Comment by chankwongyin** [comment]
Any updates?

**Comment by nikitimi** [comment]
I'm having hard time integrating the REST API on my application, I'll just use UTApi at the mean time...
