### ISSUE TITLE
[bug]: Files stuck while uploading 

### ISSUE THREAD

**Issue by DevTGhosh** [pingdotgg/uploadthing#959]
### Provide environment information

```bash
System:
    OS: macOS 14.6.1
    CPU: (10) arm64 Apple M2 Pro
    Memory: 91.36 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.11.0 - ~/.nvm/versions/node/v20.11.0/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 10.2.4 - ~/.nvm/versions/node/v20.11.0/bin/npm
    pnpm: 9.4.0 - /opt/homebrew/bin/pnpm
    bun: 1.1.26 - ~/.bun/bin/bun
  Browsers:
    Chrome: 128.0.6613.138
    Firefox Nightly: 132.0a1
    Safari: 17.6
  npmPackages:
    @uploadthing/react: ^7.0.1 => 7.0.1
    typescript: ^5.5.4 => 5.5.4
    uploadthing: ^7.0.1 => 7.0.1
```

### Describe the bug

Sometimes when uploading files the button will go to 110% then then just get stuck. I can see the presigned url get generated but nothing happens. I have to wait 2-3 mins sometimes or refresh the page for it to work. 

https://github.com/user-attachments/assets/35c9f9f9-b2c6-451d-9953-039fa98625b5

### Link to reproduction

https://github.com/pingdotgg/uploadthing/tree/95319f2334e3c634eaccbae30b084bf50f2419d9/examples/with-clerk-remix

### To reproduce

Haven't been able to consistently reproduce this error but it happens often. Let me know if you need more info. I am using the remix version of the app. I am using the remix example from your repo. 

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by juliusmarminge** [comment]
can you provide the network inspection tab when this happens? what responses do you get on the requests to `<REGION>.ingest.uploadthing.com`?

**Comment by juliusmarminge** [comment]
Hey can you see if you can still replicate this? I believe this is caused by the same issue as #962 which should hopefully be fixed
