### ISSUE TITLE
[Bug]: Homepage issue

### ISSUE THREAD

**Issue by irtaza9** [pingdotgg/uploadthing#96]
### What happened?

Hey @t3dotgg, I mentioned this issue at uploadthing channel over discord but their is no progress till now. Should I do a PR by myself? Check the image.

![image](https://github.com/pingdotgg/uploadthing/assets/98938307/cc972b43-f450-4c83-a825-20ae058d41f0)

check this or close this issue.

### What did you expect to happen?

As I know, @t3dotgg will call me for a PR to resolve this, simple.

### Version

BETA

### Reproduction Steps

By fixing the css

### Reproduction Repository

rn, a big no!

![image](https://github.com/pingdotgg/uploadthing/assets/98938307/316d6077-774b-4606-8a14-66e7bac965a3)

I've removed some media queries which are causing this issue.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by markflorkowski** [comment]
I don't think those are the only cause of the issue: 
![image](https://github.com/pingdotgg/uploadthing/assets/11494384/e9437718-0303-41a3-b6a1-1f0708dd4d60)

You can also see it very faintly in your original screenshot:
![image](https://github.com/pingdotgg/uploadthing/assets/11494384/9d5f1a53-2a0a-4d09-8e5d-936ace1f6b88)

I am only able to repro this on particularly weird window sizes, so I am not *too* concerned by it, but if you do manage to track down the cause, I'll be happy to make the required change on the marketing site.

**Comment by irtaza9** [comment]
I thing the padding media query is putting the space, check the below ss and share your feedback on it.

![image](https://github.com/pingdotgg/uploadthing/assets/98938307/531e7994-a4c3-4048-8180-79f0243a2083)

Output:
![image](https://github.com/pingdotgg/uploadthing/assets/98938307/149054f9-7c0d-4dba-8441-1325c06ec5f6)

**Comment by markflorkowski** [comment]
That looks like it does it, going to make that change right now.

**Comment by markflorkowski** [comment]
Just pushed changes, should deploy in a few minutes 👍

**Comment by irtaza9** [comment]
Thank you. Pl share the link of exact directory where you add these changes. It is difficult for me to get the actual file of home page in the project.

**Comment by markflorkowski** [comment]
They're in a separate (private) repository.
