### ISSUE TITLE
[Bug]: Delete selected files

### ISSUE THREAD

**Issue by miguelvelasquezdev** [pingdotgg/uploadthing#98]
### What happened?

Hi, I know that it's not the repo where the dashboard is deployed, but I found a strange bug.

When I select multiple files, it doesn’t let me delete them (just works if I delete them separately).

Also after I delete them separately, the button has some bug...

<img width="913" alt="Screenshot 2023-05-25 at 2 10 43 PM" src="https://github.com/pingdotgg/uploadthing/assets/59978150/9ff6f927-2760-4b5d-b588-e76a24463e1a">

### What did you expect to happen?

Let me delete multiple files at once

### Version

3.0.5

### Reproduction Steps

1.  have more than 1 file.
2. select multiple files and press the "Delete selected" button.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by markflorkowski** [comment]
I have a PR up right now that makes a lot of changes to the files table, which should hopefully fix this as well. Hoping to get that merged today or tomorrow!

**Comment by miguelvelasquezdev** [comment]
Thank you!
