### ISSUE TITLE
docs: OpenAPI HTTP1.1 example code is invalid

### ISSUE THREAD

**Issue by EmilyNyx** [pingdotgg/uploadthing#983]
### Area of Improvement

When choosing HTTP/1.1 HTTP for your client library, the example code provided for the endpoints starts with "POST /v7/getAppInfo 1.1", which is invalid and should read "POST /v7/getAppInfo HTTP/1.1" (this is true for all endpoints, I just grabbed one at random as an example)

Using the example code directly as copied from the copy button, will result in a 404 response.

### Link to related docs

https://docs.uploadthing.com/api-reference/openapi-spec

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR implementing the suggested changes!

**Comment by marclave** [comment]
hey @EmilyNyx thanks for reporting this!

something we need to fix on our end https://github.com/scalar/scalar :) 

will make an issue there as well!
