### ISSUE TITLE
feat: Specify allowed file extensions directly on component (allow user overload of accept field)

### ISSUE THREAD

**Issue by raunakdoesdev** [pingdotgg/uploadthing#992]
### Describe the feature you'd like to request

Allow user overload of `accept` field in the input component instead of pulling from MIME type.

### Describe the solution you'd like to see

Add a prop to the UploadButton and other relevant components allowing the user to override the accept field generated from MIME types.

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

**Comment by juliusmarminge** [comment]
When would this be useful? The check is gonna fail on server side anyway?
