### ISSUE TITLE
feat: [OpenAPI] Add example values to Test Request Body

### ISSUE THREAD

**Issue by chankwongyin** [pingdotgg/uploadthing#995]
### Describe the feature you'd like to request

Add example values to the Body via "Test Request". 

### Describe the solution you'd like to see

After click "Test Request", there will be example values on the body just like Swagger UI "Try it out".

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

**Comment by juliusmarminge** [comment]
Duplicate #957
